package com.motionecosystem.participantdocumentation;
import com.motionecosystem.identityaccess.api.SpecialistAuthorizationPort.*; import io.swagger.v3.oas.annotations.*; import io.swagger.v3.oas.annotations.security.SecurityRequirement; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.math.BigDecimal; import java.time.LocalDate; import java.util.*; import lombok.RequiredArgsConstructor; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.oauth2.jwt.Jwt; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/specialist/clients/{participantId}/records") @SecurityRequirement(name="oidc") @RequiredArgsConstructor class ParticipantDocumentationController {
 private final ParticipantDocumentationService service;
 @GetMapping("/interviews") @PreAuthorize("hasRole('SPECIALIST')") @Operation(operationId="listParticipantDocumentationInterviews") List<ParticipantDocumentationService.InterviewView> interviews(@AuthenticationPrincipal Jwt j,@PathVariable UUID participantId,@RequestParam ProfessionalRole actingContext){return service.list(j.getSubject(),participantId,new ActingContext(actingContext));}
 @PostMapping("/interviews") @PreAuthorize("hasRole('SPECIALIST')") @Operation(operationId="startParticipantDocumentationInterview") ParticipantDocumentationService.InterviewView start(@AuthenticationPrincipal Jwt j,@PathVariable UUID participantId,@RequestParam ProfessionalRole actingContext,@RequestHeader("Idempotency-Key") String key){return service.start(j.getSubject(),participantId,new ActingContext(actingContext),key);}
 @GetMapping("/interviews/{interviewId}") @PreAuthorize("hasRole('SPECIALIST')") @Operation(operationId="getParticipantDocumentationInterview") ParticipantDocumentationService.InterviewView interview(@AuthenticationPrincipal Jwt j,@PathVariable UUID participantId,@PathVariable UUID interviewId,@RequestParam ProfessionalRole actingContext){return service.get(j.getSubject(),participantId,interviewId,new ActingContext(actingContext));}
 @PutMapping("/interviews/{interviewId}") @PreAuthorize("hasRole('SPECIALIST')") @Operation(operationId="saveParticipantDocumentationInterviewDraft") ParticipantDocumentationService.InterviewView save(@AuthenticationPrincipal Jwt j,@PathVariable UUID participantId,@PathVariable UUID interviewId,@RequestParam ProfessionalRole actingContext,@Valid @RequestBody SaveInterviewRequest r){return service.save(j.getSubject(),participantId,interviewId,new ActingContext(actingContext),r.expectedVersion,r.answers.stream().map(AnswerRequest::command).toList());}
 @PostMapping("/interviews/{interviewId}/complete") @PreAuthorize("hasRole('SPECIALIST')") @Operation(operationId="completeParticipantDocumentationInterview") ParticipantDocumentationService.InterviewView complete(@AuthenticationPrincipal Jwt j,@PathVariable UUID participantId,@PathVariable UUID interviewId,@RequestParam ProfessionalRole actingContext,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody ParticipantDocumentationVersionRequest r){return service.complete(j.getSubject(),participantId,interviewId,new ActingContext(actingContext),key,r.expectedVersion);}
 @GetMapping("/notes") @PreAuthorize("hasRole('SPECIALIST')") @Operation(operationId="listParticipantDocumentationNotes") List<ParticipantDocumentationService.NoteView> notes(@AuthenticationPrincipal Jwt j,@PathVariable UUID participantId,@RequestParam ProfessionalRole actingContext){return service.notes(j.getSubject(),participantId,new ActingContext(actingContext));}
 @PostMapping("/notes") @PreAuthorize("hasRole('SPECIALIST')") @Operation(operationId="createParticipantDocumentationNote") ParticipantDocumentationService.NoteView create(@AuthenticationPrincipal Jwt j,@PathVariable UUID participantId,@RequestParam ProfessionalRole actingContext,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody NoteRequest r){return service.create(j.getSubject(),participantId,new ActingContext(actingContext),key,r.command());}
 @GetMapping("/notes/{noteId}") @PreAuthorize("hasRole('SPECIALIST')") @Operation(operationId="getParticipantDocumentationNote") ParticipantDocumentationService.NoteView note(@AuthenticationPrincipal Jwt j,@PathVariable UUID participantId,@PathVariable UUID noteId,@RequestParam ProfessionalRole actingContext){return service.note(j.getSubject(),participantId,noteId,new ActingContext(actingContext));}
 @PutMapping("/notes/{noteId}") @PreAuthorize("hasRole('SPECIALIST')") @Operation(operationId="updateParticipantDocumentationNote") ParticipantDocumentationService.NoteView update(@AuthenticationPrincipal Jwt j,@PathVariable UUID participantId,@PathVariable UUID noteId,@RequestParam ProfessionalRole actingContext,@Valid @RequestBody UpdateNoteRequest r){return service.update(j.getSubject(),participantId,noteId,new ActingContext(actingContext),r.expectedVersion,r.command());}
 @PostMapping("/notes/{noteId}/finalise") @PreAuthorize("hasRole('SPECIALIST')") @Operation(operationId="finaliseParticipantDocumentationNote") ParticipantDocumentationService.NoteView finalise(@AuthenticationPrincipal Jwt j,@PathVariable UUID participantId,@PathVariable UUID noteId,@RequestParam ProfessionalRole actingContext,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody ParticipantDocumentationVersionRequest r){return service.finalise(j.getSubject(),participantId,noteId,new ActingContext(actingContext),key,r.expectedVersion);}
 @PostMapping("/notes/{noteId}/archive") @PreAuthorize("hasRole('SPECIALIST')") @Operation(operationId="archiveParticipantDocumentationNote") ParticipantDocumentationService.NoteView archive(@AuthenticationPrincipal Jwt j,@PathVariable UUID participantId,@PathVariable UUID noteId,@RequestParam ProfessionalRole actingContext,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody ParticipantDocumentationVersionRequest r){return service.archive(j.getSubject(),participantId,noteId,new ActingContext(actingContext),key,r.expectedVersion);}
 record ParticipantDocumentationVersionRequest(@NotNull @PositiveOrZero Long expectedVersion){} record SaveInterviewRequest(@NotNull @PositiveOrZero Long expectedVersion,@NotNull List<@Valid AnswerRequest> answers){} record AnswerRequest(@NotBlank @Size(max=80) String code,@Size(max=4000) String textValue,BigDecimal numberValue,LocalDate dateValue,List<@Size(max=120) String> selections){ParticipantDocumentationService.Answer command(){return new ParticipantDocumentationService.Answer(code,textValue,numberValue,dateValue,selections);}} record NoteRequest(@NotBlank @Size(max=50) String category,@NotBlank @Size(max=160) String title,@NotBlank @Size(max=8000) String content,UUID appointmentId){ParticipantDocumentationService.NoteCommand command(){return new ParticipantDocumentationService.NoteCommand(category,title,content,appointmentId);}} record UpdateNoteRequest(@NotNull @PositiveOrZero Long expectedVersion,@NotBlank @Size(max=50) String category,@NotBlank @Size(max=160) String title,@NotBlank @Size(max=8000) String content,UUID appointmentId){ParticipantDocumentationService.NoteCommand command(){return new ParticipantDocumentationService.NoteCommand(category,title,content,appointmentId);}}
}
