package com.motionecosystem.exercisesets.infrastructure;

import java.time.Clock;
import java.time.Instant;
import java.util.*;
import tools.jackson.core.JacksonException;
import tools.jackson.databind.ObjectMapper;
import com.motionecosystem.exercisecatalog.api.ExerciseCatalogQueryPort;
import com.motionecosystem.anatomyreference.api.AnatomyReferenceQueryPort;
import com.motionecosystem.exercisecatalog.api.ExerciseCatalogQueryPort.PublishedExerciseVersionSnapshot;
import com.motionecosystem.exercisesets.api.ExerciseSetDtos;
import com.motionecosystem.exercisesets.api.ExerciseSetDtos.*;
import com.motionecosystem.exercisesets.domain.ExerciseSetModel.*;
import com.motionecosystem.identityaccess.api.CurrentAccount;
import com.motionecosystem.identityaccess.api.CurrentAccountService;
import com.motionecosystem.identityaccess.api.ProfileType;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service @RequiredArgsConstructor
public class ExerciseSetService {
    private final ExerciseSetRepository sets; private final ExerciseSetVersionRepository versions; private final ExerciseSetAnalysisRunRepository analysisRuns; private final ExerciseSetAnatomyAnalysisRunRepository anatomyAnalysisRuns;
    private final ExerciseCatalogQueryPort catalog; private final AnatomyReferenceQueryPort anatomyReference; private final CurrentAccountService accounts; private final Clock clock; private final ObjectMapper json;

    @Transactional public SetView create(String subject) {
        CurrentAccount actor = specialist(subject); Instant now=clock.instant();
        var set=new ExerciseSetEntities.ExerciseSetEntity(); set.id=UUID.randomUUID(); set.ownerAccountId=actor.id(); set.createdAt=now; set.updatedAt=now; sets.save(set);
        var version=newVersion(set.id, 1, actor.id(), VariantKind.BASE, null, now); versions.save(version); return setView(set);
    }
    @Transactional(readOnly=true) public List<SetView> list(String subject) { UUID owner=specialist(subject).id(); return sets.findByOwnerAccountIdOrderByCreatedAtDesc(owner).stream().map(this::setView).toList(); }
    @Transactional(readOnly=true) public SetView get(String subject, UUID setId) { return setView(owned(subject,setId)); }
    @Transactional(readOnly=true) public VersionView version(String subject, UUID setId, UUID versionId) { owned(subject,setId); return view(requireVersion(versionId,setId)); }
    @Transactional(readOnly=true) public VersionView currentDraft(String subject, UUID setId) { owned(subject,setId); return view(versions.findFirstByExerciseSetIdAndStatusOrderByVersionNumberDesc(setId,VersionStatus.DRAFT).orElseThrow(()->notFound("DRAFT_NOT_FOUND","draft not found"))); }
    @Transactional(readOnly=true) public VersionView latestPublished(String subject, UUID setId) { owned(subject,setId); return view(versions.findFirstByExerciseSetIdAndStatusOrderByVersionNumberDesc(setId,VersionStatus.PUBLISHED).orElseThrow(()->notFound("PUBLISHED_NOT_FOUND","published version not found"))); }
    @Transactional(readOnly=true) public AnalysisView analysis(String subject, UUID setId, UUID versionId) { owned(subject,setId); var version=requireVersion(versionId,setId); if(version.status == VersionStatus.DRAFT) return analyze(version, true); return storedRun(version.id).map(this::storedAnalysis).orElseThrow(()->conflict("ANALYSIS_NOT_AVAILABLE","versionId","historical version has no persisted analysis")); }
    @Transactional(readOnly=true) public AnatomyAnalysisView anatomy(String subject, UUID setId, UUID versionId) { owned(subject,setId); var version=requireVersion(versionId,setId); if(version.status == VersionStatus.DRAFT) return analyzeAnatomy(version, true); return storedAnatomyRun(version.id).map(this::storedAnatomy).orElseThrow(()->conflict("ANATOMY_ANALYSIS_NOT_AVAILABLE","versionId","historical version has no persisted anatomy analysis")); }
    @Transactional(readOnly=true) public List<VersionSummary> listVersions(String subject, UUID setId) { owned(subject,setId); return versions.findByExerciseSetIdOrderByVersionNumberDesc(setId).stream().map(v -> new VersionSummary(v.id,v.versionNumber,v.status,v.title,v.profile,v.variantKind,v.variantOfVersionId)).toList(); }

    @Transactional public VersionView updateMetadata(String subject, UUID setId, UUID versionId, MetadataRequest request) {
        var version=editable(subject,setId,versionId,request.expectedVersion()); version.profile=request.profile(); version.title=nullable(request.title(),160); version.description=nullable(request.description(),2000); version.targetLevel=nullable(request.targetLevel(),32); version.tags=json(request.tags()==null?List.of():request.tags()); return flushedView(version);
    }
    @Transactional public VersionView addItem(String subject, UUID setId, UUID versionId, ItemRequest request) {
        var version=editable(subject,setId,versionId,request.expectedVersion()); PublishedExerciseVersionSnapshot snapshot=catalog.findPublishedVersion(request.exerciseVersionId()).orElseThrow(()->bad("EXERCISE_VERSION_NOT_PUBLISHED","exerciseVersionId","exercise version must be published"));
        var item=new ExerciseSetEntities.ExerciseSetItemEntity(); item.id=UUID.randomUUID(); item.version=version; item.exerciseVersionId=snapshot.versionId(); item.phase=request.phase(); item.position=version.items.size()+1; item.canonicalName=snapshot.canonicalName(); item.exerciseVersionNumber=snapshot.versionNumber(); item.profileSchemaVersion=snapshot.profileSchemaVersion(); item.movementPatterns=json(snapshot.movementPatterns().stream().map(Enum::name).sorted().toList()); item.requiredEquipment=json(snapshot.requiredEquipment().stream().sorted().toList()); item.anatomySnapshot=json(anatomySnapshot(snapshot)); item.participantInstruction=nullable(request.participantInstruction(),2000); item.specialistInstruction=nullable(request.specialistInstruction(),2000); item.dose=dose(item,request.dose()); version.items.add(item); return flushedView(version);
    }
    @Transactional public VersionView updateItem(String subject, UUID setId, UUID versionId, UUID itemId, ItemRequest request) {
        var version=editable(subject,setId,versionId,request.expectedVersion()); var item=item(version,itemId); PublishedExerciseVersionSnapshot snapshot=catalog.findPublishedVersion(request.exerciseVersionId()).orElseThrow(()->bad("EXERCISE_VERSION_NOT_PUBLISHED","exerciseVersionId","exercise version must be published"));
        item.exerciseVersionId=snapshot.versionId(); item.phase=request.phase(); item.canonicalName=snapshot.canonicalName(); item.exerciseVersionNumber=snapshot.versionNumber(); item.profileSchemaVersion=snapshot.profileSchemaVersion(); item.movementPatterns=json(snapshot.movementPatterns().stream().map(Enum::name).sorted().toList()); item.requiredEquipment=json(snapshot.requiredEquipment().stream().sorted().toList()); item.anatomySnapshot=json(anatomySnapshot(snapshot)); item.participantInstruction=nullable(request.participantInstruction(),2000); item.specialistInstruction=nullable(request.specialistInstruction(),2000); item.dose=dose(item,request.dose()); return flushedView(version);
    }
    @Transactional public VersionView moveItem(String subject, UUID setId, UUID versionId, MoveRequest request) { var version=editable(subject,setId,versionId,request.expectedVersion()); if(request.targetPosition()<1||request.targetPosition()>version.items.size()) throw bad("INVALID_POSITION","targetPosition","position is outside the item range"); var item=item(version,request.itemId()); version.items.remove(item); version.items.add(request.targetPosition()-1,item); int offset=version.items.size(); for(int i=0;i<version.items.size();i++) version.items.get(i).position=offset+i+1; versions.flush(); renumber(version); return flushedView(version); }
    @Transactional public VersionView removeItem(String subject, UUID setId, UUID versionId, UUID itemId, long expectedVersion) { var version=editable(subject,setId,versionId,expectedVersion); version.items.remove(item(version,itemId)); versions.flush(); renumber(version); return flushedView(version); }
    @Transactional public VersionView publish(String subject, UUID setId, UUID versionId, long expectedVersion) { owned(subject,setId); var version=requireVersion(versionId,setId); if(expectedVersion!=version.version) throw conflict("OPTIMISTIC_LOCK","expectedVersion","draft was changed by another request"); if(version.status!=VersionStatus.DRAFT) throw bad("VERSION_NOT_EDITABLE","versionId","only a draft can be edited"); validatePublication(version); var analysis=analyze(version, true); var anatomy=analyzeAnatomy(version, true); version.status=VersionStatus.PUBLISHED; version.publishedAt=clock.instant(); persistAnalysis(version, analysis); persistAnatomyAnalysis(version, anatomy); return flushedView(version); }
    @Transactional public VersionView nextDraft(String subject, UUID setId, UUID sourceVersionId) { owned(subject,setId); var source=requireVersion(sourceVersionId,setId); if(source.status!=VersionStatus.PUBLISHED) throw bad("SOURCE_NOT_PUBLISHED","sourceVersionId","only a published version can be copied"); var draft=copy(source,nextNumber(setId),specialist(subject).id(),source.variantKind,source.variantOfVersionId); versions.save(draft); return flushedView(draft); }
    @Transactional public VersionView variantDraft(String subject, UUID setId, UUID sourceVersionId, CreateVariantRequest request) { owned(subject,setId); if(request.variantKind()==VariantKind.BASE) throw bad("INVALID_VARIANT","variantKind","variant draft must be SHORT or MINIMUM"); var source=requireVersion(sourceVersionId,setId); if(source.status!=VersionStatus.PUBLISHED) throw bad("SOURCE_NOT_PUBLISHED","sourceVersionId","source must be published"); var draft=copy(source,nextNumber(setId),specialist(subject).id(),request.variantKind(),source.id); versions.save(draft); return flushedView(draft); }
    @Transactional public VersionView retire(String subject, UUID setId, UUID versionId) { owned(subject,setId); var version=requireVersion(versionId,setId); if(version.status!=VersionStatus.PUBLISHED) throw bad("VERSION_NOT_PUBLISHED","versionId","only published versions can be retired"); version.status=VersionStatus.RETIRED; version.retiredAt=clock.instant(); return flushedView(version); }

    private ExerciseSetEntities.ExerciseSetVersionEntity newVersion(UUID setId,int number,UUID author,VariantKind kind,UUID source,Instant now){ var v=new ExerciseSetEntities.ExerciseSetVersionEntity();v.id=UUID.randomUUID();v.exerciseSetId=setId;v.versionNumber=number;v.status=VersionStatus.DRAFT;v.authorAccountId=author;v.variantKind=kind;v.variantOfVersionId=source;v.createdAt=now;v.updatedAt=now;return v; }
    private ExerciseSetEntities.ExerciseSetVersionEntity copy(ExerciseSetEntities.ExerciseSetVersionEntity source,int number,UUID author,VariantKind kind,UUID lineage){ var result=newVersion(source.exerciseSetId,number,author,kind,lineage,clock.instant());result.profile=source.profile;result.title=source.title;result.description=source.description;result.targetLevel=source.targetLevel;result.tags=source.tags; for(var old:source.items){var item=new ExerciseSetEntities.ExerciseSetItemEntity();item.id=UUID.randomUUID();item.version=result;item.exerciseVersionId=old.exerciseVersionId;item.phase=old.phase;item.position=old.position;item.canonicalName=old.canonicalName;item.exerciseVersionNumber=old.exerciseVersionNumber;item.profileSchemaVersion=old.profileSchemaVersion;item.movementPatterns=old.movementPatterns;item.requiredEquipment=old.requiredEquipment;item.anatomySnapshot=old.anatomySnapshot;item.participantInstruction=old.participantInstruction;item.specialistInstruction=old.specialistInstruction;item.dose=copyDose(item,old.dose);result.items.add(item);}return result; }
    private ExerciseSetEntities.DoseEntity dose(ExerciseSetEntities.ExerciseSetItemEntity item,Dose d){ validateDose(d); ExerciseSetEntities.DoseEntity e=switch(d){case StrengthDose x->new ExerciseSetEntities.StrengthDoseEntity();case IsometricDose x->new ExerciseSetEntities.IsometricDoseEntity();case MobilityDose x->new ExerciseSetEntities.MobilityDoseEntity();case StretchDose x->new ExerciseSetEntities.StretchDoseEntity();case BreathingDose x->new ExerciseSetEntities.BreathingDoseEntity();case AerobicDose x->new ExerciseSetEntities.AerobicDoseEntity();};e.id=UUID.randomUUID();e.item=item; switch(d){case StrengthDose x->{e.sets=x.sets();e.reps=x.reps();e.repMin=x.repMin();e.repMax=x.repMax();e.restSeconds=x.restSeconds();e.tempo=x.tempo();e.loadValue=x.loadValue();e.loadUnit=x.loadUnit();e.rpe=x.rpe();e.rir=x.rir();e.side=x.side();}case IsometricDose x->{e.sets=x.sets();e.holdSeconds=x.holdSeconds();e.restSeconds=x.restSeconds();e.intensity=x.intensity();e.side=x.side();}case MobilityDose x->{e.reps=x.reps();e.durationSeconds=x.durationSeconds();e.rangeTarget=x.rangeTarget();e.side=x.side();e.tempo=x.tempo();}case StretchDose x->{e.holdSeconds=x.holdSeconds();e.repetitions=x.repetitions();e.side=x.side();e.intensity=x.intensity();}case BreathingDose x->{e.durationSeconds=x.durationSeconds();e.cycles=x.cycles();e.rhythm=x.rhythm();}case AerobicDose x->{e.durationSeconds=x.durationSeconds();e.distanceMeters=x.distanceMeters();e.intensity=x.intensity();e.zone=x.zone();e.rpe=x.rpe();}} return e; }
    private ExerciseSetEntities.DoseEntity copyDose(ExerciseSetEntities.ExerciseSetItemEntity item,ExerciseSetEntities.DoseEntity old){ Dose d=toDose(old);return dose(item,d); }
    private void validateDose(Dose d){ if(d==null)throw bad("DOSE_REQUIRED","dose","dose is required"); switch(d){case StrengthDose x->{positive(x.sets(),"sets");if(x.reps()==null&&(x.repMin()==null||x.repMax()==null))throw bad("INVALID_DOSE","dose","strength needs reps or range");positiveIf(x.reps(),"reps");positiveIf(x.repMin(),"repMin");positiveIf(x.repMax(),"repMax");if(x.repMin()!=null&&x.repMax()!=null&&x.repMin()>x.repMax())throw bad("INVALID_DOSE","dose","rep range is invalid");nonnegative(x.restSeconds(),"restSeconds");rpe(x.rpe());if(x.rir()!=null&&(x.rir()<0||x.rir()>10))throw bad("INVALID_DOSE","dose","RIR must be 0..10");}case IsometricDose x->{positive(x.sets(),"sets");positive(x.holdSeconds(),"holdSeconds");nonnegative(x.restSeconds(),"restSeconds");}case MobilityDose x->{if(x.reps()==null&&x.durationSeconds()==null)throw bad("INVALID_DOSE","dose","mobility needs reps or duration");positiveIf(x.reps(),"reps");positiveIf(x.durationSeconds(),"durationSeconds");if(blank(x.rangeTarget()))throw bad("INVALID_DOSE","dose","mobility needs range target");}case StretchDose x->{positive(x.holdSeconds(),"holdSeconds");positive(x.repetitions(),"repetitions");if(x.side()==null)throw bad("INVALID_DOSE","dose","stretch needs side");}case BreathingDose x->{if(x.durationSeconds()==null&&x.cycles()==null)throw bad("INVALID_DOSE","dose","breathing needs duration or cycles");positiveIf(x.durationSeconds(),"durationSeconds");positiveIf(x.cycles(),"cycles");}case AerobicDose x->{positive(x.durationSeconds(),"durationSeconds");positiveIf(x.distanceMeters(),"distanceMeters");rpe(x.rpe());}} }
    private void validatePublication(ExerciseSetEntities.ExerciseSetVersionEntity v){for(int i=0;i<v.items.size();i++){var item=v.items.get(i);if(item.position!=i+1)throw bad("INVALID_SEQUENCE","items["+i+"].position","item positions must be contiguous");if(item.exerciseVersionId==null||item.dose==null)throw bad("INVALID_ITEM","items["+i+"]","item needs an exercise version and dose");validateDose(toDose(item.dose));}if(v.variantKind==VariantKind.BASE&&v.variantOfVersionId!=null)throw bad("INVALID_VARIANT","variantOfVersionId","base cannot have source");if(v.variantKind!=VariantKind.BASE){if(v.variantOfVersionId==null)throw bad("INVALID_VARIANT","variantOfVersionId","variant needs source");var source=versions.findWithItemsById(v.variantOfVersionId).orElseThrow(()->bad("INVALID_VARIANT","variantOfVersionId","variant source does not exist"));if(!source.exerciseSetId.equals(v.exerciseSetId)||source.status!=VersionStatus.PUBLISHED)throw bad("INVALID_VARIANT","variantOfVersionId","variant source must be a published version of the same set");Set<UUID> seen=new HashSet<>();for(var current=source;current.variantOfVersionId!=null;){if(!seen.add(current.id)||current.id.equals(v.id))throw bad("VARIANT_CYCLE","variantOfVersionId","variant provenance must not contain a cycle");current=versions.findWithItemsById(current.variantOfVersionId).orElseThrow(()->bad("INVALID_VARIANT","variantOfVersionId","variant source does not exist"));}}}
    private Dose toDose(ExerciseSetEntities.DoseEntity e){ return switch(e){case ExerciseSetEntities.StrengthDoseEntity x->new StrengthDose(x.sets,x.reps,x.repMin,x.repMax,x.restSeconds,x.tempo,x.loadValue,x.loadUnit,x.rpe,x.rir,x.side);case ExerciseSetEntities.IsometricDoseEntity x->new IsometricDose(x.sets,x.holdSeconds,x.restSeconds,x.intensity,x.side);case ExerciseSetEntities.MobilityDoseEntity x->new MobilityDose(x.reps,x.durationSeconds,x.rangeTarget,x.side,x.tempo);case ExerciseSetEntities.StretchDoseEntity x->new StretchDose(x.holdSeconds,x.repetitions,x.side,x.intensity);case ExerciseSetEntities.BreathingDoseEntity x->new BreathingDose(x.durationSeconds,x.cycles,x.rhythm);case ExerciseSetEntities.AerobicDoseEntity x->new AerobicDose(x.durationSeconds,x.distanceMeters,x.intensity,x.zone,x.rpe);default->throw new IllegalStateException("unknown dose");}; }
    private VersionView flushedView(ExerciseSetEntities.ExerciseSetVersionEntity version) { version.updatedAt=clock.instant(); versions.flush(); return view(version); }
    private VersionView view(ExerciseSetEntities.ExerciseSetVersionEntity v){return new VersionView(v.id,v.exerciseSetId,v.versionNumber,v.status,v.profile,v.title,v.description,v.targetLevel,strings(v.tags),v.variantKind,v.variantOfVersionId,v.createdAt,v.publishedAt,v.retiredAt,v.version,v.items.stream().map(i->new ItemView(i.id,i.exerciseVersionId,i.phase,i.position,new ExerciseSnapshot(i.canonicalName,i.exerciseVersionNumber,i.profileSchemaVersion,strings(i.movementPatterns),strings(i.requiredEquipment)),toDose(i.dose),i.participantInstruction,i.specialistInstruction)).toList(), storedRun(v.id).map(this::storedAnalysis).orElse(null));}
    private AnalysisView analyze(ExerciseSetEntities.ExerciseSetVersionEntity version, boolean draft) { var result=new ExerciseSetAnalyzer().analyze(version,draft); return new AnalysisView(result.status(),result.policyVersion(),result.analyzedLockVersion(),clock.instant(),result.draft(),result.published(),result.metrics(),result.findings()); }
    private AnatomyAnalysisView analyzeAnatomy(ExerciseSetEntities.ExerciseSetVersionEntity version, boolean draft) {
        var snapshots=new HashMap<UUID, ExerciseSetAnalyzer.ItemAnatomySnapshot>();
        for (var item : version.items) { var snapshot=anatomySnapshot(item); if (snapshot != null) snapshots.put(item.id, snapshot); }
        var result=new ExerciseSetAnalyzer().analyzeAnatomy(version,draft,snapshots);
        return new AnatomyAnalysisView(result.policyVersion(),result.analyzedLockVersion(),clock.instant(),result.draft(),result.published(),result.completeness(),result.channels(),result.directStructureExposures(),result.movementPatterns(),result.findings(),result.missing(),result.aggregatedStructureExposures(),result.mappingCompleteness(),result.unmappedStructures(),result.unmappedCount(),result.visualMappingVersion(),result.visualMappingCompleteness(),result.visualConcentrationPolicyVersion(),result.visualRegionExposures());
    }
    private void persistAnalysis(ExerciseSetEntities.ExerciseSetVersionEntity version, AnalysisView analysis) { var run=new ExerciseSetEntities.ExerciseSetAnalysisRunEntity(); run.id=UUID.randomUUID();run.version=version;run.policyVersion=analysis.policyVersion();run.analyzedLockVersion=analysis.analyzedLockVersion();run.analyzedAt=analysis.analyzedAt();run.status=analysis.status().name();run.itemCount=analysis.metrics().itemCount();run.estimatedSeconds=analysis.metrics().estimatedSeconds();run.timeConfidence=analysis.metrics().timeConfidence();run.equipmentTransitions=analysis.metrics().equipmentTransitions();run.doseKindSwitches=analysis.metrics().doseKindSwitches(); int ordinal=1; for(var f:analysis.findings()){var x=new ExerciseSetEntities.ExerciseSetAnalysisFindingEntity();x.id=UUID.randomUUID();x.run=run;x.findingOrdinal=ordinal++;x.code=f.code();x.ruleVersion=f.ruleVersion();x.severity=f.severity();x.category=f.category();x.messageKey=f.messageKey();x.explanation=f.explanation();x.itemIds=json(f.itemIds());x.phase=f.phase();x.field=f.field();x.action=f.action();x.blocking=false;run.findings.add(x);} version.analysisRun=run; }
    private AnalysisView storedAnalysis(ExerciseSetEntities.ExerciseSetAnalysisRunEntity run) { var findings=run.findings.stream().map(f->new AnalysisFinding(f.code,f.ruleVersion,advisorySeverity(f.severity),f.category,f.messageKey,f.explanation,uuidList(f.itemIds),f.phase,f.field,f.action,false)).toList(); return new AnalysisView(advisoryStatus(run.status, findings),run.policyVersion,run.analyzedLockVersion,run.analyzedAt,false,true,new AnalysisMetrics(run.itemCount,run.estimatedSeconds,run.timeConfidence,run.equipmentTransitions,run.doseKindSwitches),findings); }
    private void persistAnatomyAnalysis(ExerciseSetEntities.ExerciseSetVersionEntity version, AnatomyAnalysisView analysis) { var run=new ExerciseSetEntities.ExerciseSetAnatomyAnalysisRunEntity();run.id=UUID.randomUUID();run.version=version;run.policyVersion=analysis.policyVersion();run.analyzedLockVersion=analysis.analyzedLockVersion();run.analyzedAt=analysis.analyzedAt();run.result=json(new AnatomyAnalysisView(analysis.policyVersion(),analysis.analyzedLockVersion(),analysis.analyzedAt(),false,true,analysis.completeness(),analysis.channels(),analysis.directStructureExposures(),analysis.movementPatterns(),analysis.findings(),analysis.missing(),analysis.aggregatedStructureExposures(),analysis.mappingCompleteness(),analysis.unmappedStructures(),analysis.unmappedCount(),analysis.visualMappingVersion(),analysis.visualMappingCompleteness(),analysis.visualConcentrationPolicyVersion(),analysis.visualRegionExposures()));version.anatomyAnalysisRun=run; }
    private Optional<ExerciseSetEntities.ExerciseSetAnatomyAnalysisRunEntity> storedAnatomyRun(UUID versionId) { return anatomyAnalysisRuns.findByVersionId(versionId); }
    private AnatomyAnalysisView storedAnatomy(ExerciseSetEntities.ExerciseSetAnatomyAnalysisRunEntity run) { try { return json.readValue(run.result, AnatomyAnalysisView.class); } catch (Exception e) { throw new IllegalStateException("corrupt anatomy analysis", e); } }
    private ExerciseSetAnalyzer.ItemAnatomySnapshot anatomySnapshot(PublishedExerciseVersionSnapshot snapshot) {
        var structureIds = snapshot.contributions().stream().map(c -> c.anatomicalStructureId()).filter(Objects::nonNull).collect(java.util.stream.Collectors.toSet());
        var mappings = anatomyReference.visualMappings(structureIds);
        return new ExerciseSetAnalyzer.ItemAnatomySnapshot(snapshot.versionId(), snapshot.versionNumber(), snapshot.profileSchemaVersion(),
                snapshot.movementPatterns().stream().map(Enum::name).sorted().toList(), snapshot.contributions().stream().map(c -> {
                    var paths = c.anatomicalStructureId() == null ? List.<ExerciseSetAnalyzer.ItemAnatomyPath>of() : anatomyReference.ancestorPaths(c.anatomicalStructureId()).stream()
                            .map(path -> new ExerciseSetAnalyzer.ItemAnatomyPath(path.steps().stream()
                                    .map(step -> new ExerciseSetAnalyzer.ItemAnatomyStructure(step.structure().id(), step.structure().code(), step.structure().type().name())).toList())).toList();
                    var mapping = mappings.get(c.anatomicalStructureId());
                    var visual = mapping == null ? null : new ExerciseSetAnalyzer.ItemVisualMapping(mapping.mappingVersion(), mapping.regions().stream()
                            .map(region -> new ExerciseSetAnalyzer.ItemVisualRegion(region.id(), region.code(), region.displayName(), region.viewName(),
                                    region.layerName(), region.labelKey(), region.parentRegionId(), region.displayOrder(), region.status())).toList());
                    return new ExerciseSetAnalyzer.ItemAnatomyContribution(c.id(), c.anatomicalStructureId(), c.anatomicalStructureCode(), c.anatomicalStructureType(), c.role().name(), c.loadChannel().name(), c.coefficientLow(), c.coefficientHigh(), c.confidenceClass(), c.evidenceGrade(), c.calculationRole()==ExerciseCatalogQueryPort.CalculationRoleValue.ALLOCATION, c.variantCondition(), c.sideRule().name(), c.evidence().stream().map(e -> new AnatomyEvidence(e.id(),e.citation(),e.sourceUri(),e.evidenceGrade())).toList(), paths, visual);
                }).toList());
    }
    private ExerciseSetAnalyzer.ItemAnatomySnapshot anatomySnapshot(ExerciseSetEntities.ExerciseSetItemEntity item) { try { var snapshot=json.readValue(item.anatomySnapshot, ExerciseSetAnalyzer.ItemAnatomySnapshot.class); return snapshot == null || snapshot.sourceExerciseVersionId() == null ? null : snapshot; } catch (Exception e) { throw new IllegalStateException("corrupt exercise set item anatomy snapshot", e); } }
    private Optional<ExerciseSetEntities.ExerciseSetAnalysisRunEntity> storedRun(UUID versionId) { return analysisRuns.findByVersionId(versionId); }
    private SetView setView(ExerciseSetEntities.ExerciseSetEntity set){return new SetView(set.id,set.visibility,set.ownerAccountId,set.createdAt,versions.findByExerciseSetIdOrderByVersionNumberDesc(set.id).stream().map(v->new VersionSummary(v.id,v.versionNumber,v.status,v.title,v.profile,v.variantKind,v.variantOfVersionId)).toList());}
    private ExerciseSetEntities.ExerciseSetEntity owned(String subject,UUID id){var set=sets.findById(id).orElseThrow(()->notFound("SET_NOT_FOUND","exercise set not found"));if(!set.ownerAccountId.equals(specialist(subject).id()))throw forbidden("SET_ACCESS_DENIED","exercise set belongs to another specialist");return set;}
    private ExerciseSetEntities.ExerciseSetVersionEntity editable(String subject,UUID setId,UUID versionId,Long expected){owned(subject,setId);var v=requireVersion(versionId,setId);if(v.status!=VersionStatus.DRAFT)throw bad("VERSION_NOT_EDITABLE","versionId","only a draft can be edited");if(expected!=null&&expected!=v.version)throw conflict("OPTIMISTIC_LOCK","expectedVersion","draft was changed by another request");return v;}
    private ExerciseSetEntities.ExerciseSetVersionEntity requireVersion(UUID id,UUID setId){var v=versions.findWithItemsById(id).orElseThrow(()->notFound("VERSION_NOT_FOUND","exercise set version not found"));if(!v.exerciseSetId.equals(setId))throw notFound("VERSION_NOT_FOUND","exercise set version not found");return v;}
    private ExerciseSetEntities.ExerciseSetItemEntity item(ExerciseSetEntities.ExerciseSetVersionEntity v,UUID id){return v.items.stream().filter(x->x.id.equals(id)).findFirst().orElseThrow(()->notFound("ITEM_NOT_FOUND","item not found"));}
    private int nextNumber(UUID setId){return Math.toIntExact(versions.countByExerciseSetId(setId)+1);}
    private void renumber(ExerciseSetEntities.ExerciseSetVersionEntity v){for(int i=0;i<v.items.size();i++)v.items.get(i).position=i+1;}
    private CurrentAccount specialist(String subject){var a=accounts.requireActive(subject);if(a.profileType()!=ProfileType.SPECIALIST)throw forbidden("SPECIALIST_REQUIRED","specialist profile is required");return a;}
    private String json(Object value){try{return json.writeValueAsString(value);}catch(JacksonException e){throw new IllegalStateException(e);}}
    private List<String> strings(String value){try{return json.readValue(value,json.getTypeFactory().constructCollectionType(List.class,String.class));}catch(Exception e){throw new IllegalStateException("corrupt exercise set snapshot",e);}}
    private List<UUID> uuidList(String value){try{return json.readValue(value,json.getTypeFactory().constructCollectionType(List.class,UUID.class));}catch(Exception e){throw new IllegalStateException("corrupt analysis evidence",e);}}
    private static AnalysisStatus advisoryStatus(String storedStatus,List<AnalysisFinding> findings){return switch(storedStatus){case "NO_SUGGESTIONS", "VALID" -> findings.isEmpty()?AnalysisStatus.NO_SUGGESTIONS:AnalysisStatus.SUGGESTIONS_AVAILABLE;case "SUGGESTIONS_AVAILABLE", "VALID_WITH_SUGGESTIONS", "VALID_WITH_WARNINGS", "BLOCKED" -> AnalysisStatus.SUGGESTIONS_AVAILABLE;default -> AnalysisStatus.ANALYSIS_UNAVAILABLE;};} private static FindingSeverity advisorySeverity(FindingSeverity severity){return severity==FindingSeverity.BLOCKING?FindingSeverity.SUGGESTION:severity;} private static String nullable(String x,int max){if(x==null)return null;var v=x.trim();if(v.length()>max)throw bad("INVALID_TEXT",null,"text is too long");return v.isEmpty()?null:v;} private static boolean blank(String x){return x==null||x.isBlank();} private static void positive(Integer x,String field){if(x==null||x<=0)throw bad("INVALID_DOSE",field,field+" must be positive");}private static void positiveIf(Integer x,String field){if(x!=null&&x<=0)throw bad("INVALID_DOSE",field,field+" must be positive");}private static void nonnegative(Integer x,String field){if(x!=null&&x<0)throw bad("INVALID_DOSE",field,field+" must not be negative");}private static void rpe(java.math.BigDecimal x){if(x!=null&&(x.compareTo(java.math.BigDecimal.ZERO)<0||x.compareTo(java.math.BigDecimal.TEN)>0))throw bad("INVALID_DOSE","rpe","RPE must be 0..10");}
    private static ExerciseSetProblem bad(String code,String field,String message){return new ExerciseSetProblem(HttpStatus.BAD_REQUEST,code,field,message);}private static ExerciseSetProblem conflict(String code,String field,String message){return new ExerciseSetProblem(HttpStatus.CONFLICT,code,field,message);}private static ExerciseSetProblem forbidden(String code,String message){return new ExerciseSetProblem(HttpStatus.FORBIDDEN,code,null,message);}private static ExerciseSetProblem notFound(String code,String message){return new ExerciseSetProblem(HttpStatus.NOT_FOUND,code,null,message);}
    public static class ExerciseSetProblem extends ResponseStatusException { public final String code,field; ExerciseSetProblem(HttpStatus s,String code,String field,String msg){super(s,msg);this.code=code;this.field=field;} }
}
