import { ChangeDetectionStrategy, Component, ElementRef, afterNextRender, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { Title } from '@angular/platform-browser';
import { ApiFacade } from '../core/api.facade';
import { catalogLabel } from './catalog-labels';

@Component({selector:'app-catalog-detail-page', imports:[RouterLink, MatButtonModule], changeDetection:ChangeDetectionStrategy.OnPush, styleUrl:'./catalog.page.scss', template:`<main class="catalog panel" #main tabindex="-1"><a mat-button routerLink="/catalog" [queryParams]="back()">← Wróć do wyników</a>@if (loading()) {<p aria-live="polite">Ładowanie ćwiczenia…</p>} @else if (notFound()) {<h1>Nie znaleziono ćwiczenia</h1><p role="alert">Ta wersja nie jest opublikowana lub nie istnieje.</p>} @else if (error()) {<h1>Nie udało się pobrać ćwiczenia</h1><p role="alert">Spróbuj ponownie.</p><button mat-button (click)="load()">Ponów</button>} @else if (detail()) {<h1>{{detail().canonicalName}}</h1><p class="version">Opublikowana wersja {{detail().versionNumber}}</p><section><h2>Klasyfikacja</h2><p>{{detail().movementPatterns?.map(label).join(' · ')}} · {{label(detail().technicalLevel)}} · {{label(detail().environment)}}</p></section><section><h2>Instrukcja wykonania</h2><p>{{detail().instruction}}</p></section><section><h2>Wymagany sprzęt</h2><p>{{detail().requiredEquipment?.length ? detail().requiredEquipment.join(', ') : 'Brak specjalnego sprzętu'}}</p></section><section><h2>Anatomia i profil obciążenia</h2><ul>@for (a of detail().anatomyContributions; track a.code) {<li><strong>{{a.displayName}}</strong> — {{label(a.role)}}, {{a.coefficientLow}}–{{a.coefficientHigh}}; {{a.contributionBand}}.</li>} @empty {<li>Brak danych anatomicznych.</li>}</ul><h3>Charakterystyki obciążenia</h3><ul>@for (c of detail().loadCharacteristics; track c.characteristicType + c.movementPlane) {<li>{{label(c.characteristicType)}} · {{label(c.movementPlane)}} · {{label(c.contractionType)}}</li>}</ul></section><details><summary>Dowody</summary><ul>@for (e of detail().evidence; track e.citation) {<li>{{e.citation}} <small>{{e.evidenceGrade}}</small> @if(e.sourceUri){<a [href]="e.sourceUri" target="_blank" rel="noopener">Źródło</a>}</li>} @empty {<li>Brak przypisanych cytacji.</li>}</ul></details>}</main>`})
export class CatalogDetailPage { private readonly api=inject(ApiFacade).catalog as any; private readonly route=inject(ActivatedRoute); private readonly title=inject(Title); readonly detail=signal<any>(null); readonly loading=signal(true); readonly error=signal(false); readonly notFound=signal(false); label=catalogLabel; constructor(){ afterNextRender(()=>document.querySelector('main')?.focus()); this.load(); } back(){return this.route.snapshot.queryParams;} async load(){this.loading.set(true);this.error.set(false);this.notFound.set(false);try{const d=await this.api.version({versionId:this.route.snapshot.paramMap.get('versionId')!});this.detail.set(d);this.title.setTitle(`${d.canonicalName} | Moves`);}catch(e:any){this.notFound.set(e?.response?.status===404);this.error.set(e?.response?.status!==404);}finally{this.loading.set(false);}} }
