import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { ApiFacade } from '../core/api.facade';
import { VersionCommand, VersionCommandEnvironmentEnum, VersionCommandStimulusTypeEnum } from '../api/generated/src';

const PATTERNS = ['SQUAT', 'HINGE', 'PUSH', 'PULL', 'LUNGE', 'CARRY', 'ROTATION', 'LOCOMOTION', 'BREATHING', 'MOBILITY', 'OTHER'];
const EQUIPMENT = ['BODYWEIGHT', 'MAT', 'WALL', 'CHAIR'];

@Component({selector: 'app-exercise-catalog-new-page', imports: [FormsModule, RouterLink, MatButtonModule], changeDetection: ChangeDetectionStrategy.OnPush, template: `
<section class="panel"><a mat-button routerLink="/admin/exercise-catalog">← Katalog</a><h1>Dodaj ćwiczenie</h1><p>Utworzone ćwiczenie pozostaje szkicem do czasu publikacji.</p>
<form (ngSubmit)="create()"><label>Nazwa <input class="app-native-control" name="name" [(ngModel)]="name" required /></label><label>Instrukcja <textarea class="app-native-control" name="instruction" [(ngModel)]="instruction" required rows="5"></textarea></label><label>Wzorce ruchowe <select class="app-native-control" multiple name="patterns" [(ngModel)]="patterns">@for (x of movementPatterns; track x) {<option [value]="x">{{x}}</option>}</select></label><label>Typ bodźca <select class="app-native-control" name="stimulus" [(ngModel)]="stimulus">@for (x of stimuli; track x) {<option [value]="x">{{x}}</option>}</select></label><label>Profil zmęczenia <select class="app-native-control" name="fatigue" [(ngModel)]="fatigue"><option>LOW</option><option>MODERATE</option><option>HIGH</option></select></label><label>Poziom techniczny <select class="app-native-control" name="level" [(ngModel)]="level"><option>FOUNDATIONAL</option><option>INTERMEDIATE</option><option>ADVANCED</option></select></label><label>Środowisko <select class="app-native-control" name="environment" [(ngModel)]="environment">@for (x of environments; track x) {<option [value]="x">{{x}}</option>}</select></label><label>Wymagany sprzęt <select class="app-native-control" multiple name="equipment" [(ngModel)]="equipment">@for (x of equipmentOptions; track x) {<option [value]="x">{{x}}</option>}</select></label><label>Referencja do materiału <input class="app-native-control" name="media" [(ngModel)]="mediaReference" /></label><button mat-flat-button [disabled]="creating()">{{creating() ? 'Tworzenie…' : 'Utwórz szkic'}}</button></form>@if (error()) {<p role="alert">{{error()}}</p>}</section>`})
export class ExerciseCatalogNewPage {
  private readonly api = inject(ApiFacade).catalogAdmin; private readonly router = inject(Router);
  readonly creating = signal(false); readonly error = signal(''); readonly movementPatterns = PATTERNS; readonly equipmentOptions = EQUIPMENT; readonly stimuli = Object.values(VersionCommandStimulusTypeEnum); readonly environments = Object.values(VersionCommandEnvironmentEnum);
  name = ''; instruction = ''; patterns = ['OTHER']; equipment: string[] = []; stimulus = 'STRENGTH'; fatigue = 'MODERATE'; level = 'FOUNDATIONAL'; environment = 'ANY'; mediaReference = '';
  async create() { if (!this.name.trim() || !this.instruction.trim()) return; this.creating.set(true); this.error.set(''); try { const version = await this.api.createEditorialExercise({catalogCreateRequest: {canonicalName: this.name.trim(), version: this.command()}}); if (version.versionId) await this.router.navigate(['/admin/exercise-catalog', version.versionId]); } catch { this.error.set('Nie udało się utworzyć szkicu. Sprawdź wymagane pola.'); } finally { this.creating.set(false); } }
  private command(): VersionCommand { return {instruction: this.instruction.trim(), mediaReference: this.mediaReference.trim() || undefined, movementPatterns: new Set(this.patterns) as VersionCommand['movementPatterns'], stimulusType: this.stimulus as VersionCommand['stimulusType'], fatigueProfile: this.fatigue as VersionCommand['fatigueProfile'], technicalLevel: this.level as VersionCommand['technicalLevel'], environment: this.environment as VersionCommand['environment'], requiredEquipment: new Set(this.equipment)}; }
}
