import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { ApiFacade } from '../core/api.facade';
import { VersionCommand } from '../api/generated/src';
import { ExerciseCatalogMultiChoiceComponent } from './exercise-catalog-multi-choice.component';
import { environmentOptions, equipmentOptionsFor, fatigueOptions, movementPatternOptions, stimulusOptions, technicalLevelOptions } from './exercise-catalog-options';

@Component({selector: 'app-exercise-catalog-new-page', imports: [FormsModule, RouterLink, MatButtonModule, ExerciseCatalogMultiChoiceComponent], changeDetection: ChangeDetectionStrategy.OnPush, template: `
<section class="panel exercise-editor"><a mat-button routerLink="/admin/exercise-catalog">← Katalog</a><h1>Dodaj ćwiczenie</h1><p>Utworzone ćwiczenie pozostaje szkicem do czasu publikacji.</p>
<form #form="ngForm" (ngSubmit)="create()"><section><h2>Podstawowe informacje</h2><div class="editor-grid"><label class="wide">Nazwa * <input class="app-native-control" name="name" [(ngModel)]="name" required #nameControl="ngModel" /></label>@if ((nameControl.touched || submitted) && nameControl.invalid) {<p class="field-error">Nazwa jest wymagana.</p>}<label class="wide">Instrukcja * <textarea class="app-native-control" name="instruction" [(ngModel)]="instruction" required rows="5" #instructionControl="ngModel"></textarea></label>@if ((instructionControl.touched || submitted) && instructionControl.invalid) {<p class="field-error">Instrukcja jest wymagana.</p>}<label class="wide">Referencja do materiału <input class="app-native-control" name="media" [(ngModel)]="mediaReference" /></label></div></section>
<section><h2>Klasyfikacja</h2><div class="editor-grid"><app-exercise-catalog-multi-choice class="wide" name="patterns" label="Wzorce ruchowe" [options]="movementPatternOptions" [selection]="patterns" (selectionChange)="patterns = $event" /><label>Typ bodźca <select class="app-native-control" name="stimulus" [(ngModel)]="stimulus"><option [ngValue]="undefined">Wybierz…</option>@for (option of stimulusOptions; track option.value) {<option [value]="option.value">{{option.label}}</option>}</select></label><label>Profil zmęczenia <select class="app-native-control" name="fatigue" [(ngModel)]="fatigue"><option [ngValue]="undefined">Wybierz…</option>@for (option of fatigueOptions; track option.value) {<option [value]="option.value">{{option.label}}</option>}</select></label><label>Poziom techniczny <select class="app-native-control" name="level" [(ngModel)]="level"><option [ngValue]="undefined">Wybierz…</option>@for (option of technicalLevelOptions; track option.value) {<option [value]="option.value">{{option.label}}</option>}</select></label></div></section>
<section><h2>Warunki wykonania</h2><div class="editor-grid"><label>Środowisko <select class="app-native-control" name="environment" [(ngModel)]="environment"><option [ngValue]="undefined">Wybierz…</option>@for (option of environmentOptions; track option.value) {<option [value]="option.value">{{option.label}}</option>}</select></label><app-exercise-catalog-multi-choice class="wide" name="equipment" label="Wymagany sprzęt" [options]="equipmentOptions" [selection]="equipment" [allowCustom]="true" (selectionChange)="equipment = $event" /></div></section><button mat-flat-button [disabled]="creating()">{{creating() ? 'Tworzenie…' : 'Utwórz szkic'}}</button></form>@if (error()) {<p role="alert">{{error()}}</p>}</section>`})
export class ExerciseCatalogNewPage {
  private readonly api = inject(ApiFacade).catalogAdmin; private readonly router = inject(Router);
  readonly creating = signal(false); readonly error = signal(''); readonly movementPatternOptions = movementPatternOptions; readonly stimulusOptions = stimulusOptions; readonly fatigueOptions = fatigueOptions; readonly technicalLevelOptions = technicalLevelOptions; readonly environmentOptions = environmentOptions;
  get equipmentOptions() { return equipmentOptionsFor(this.equipment); }
  submitted = false; name = ''; instruction = ''; patterns: string[] = []; equipment: string[] = []; stimulus: VersionCommand['stimulusType']; fatigue: VersionCommand['fatigueProfile']; level: VersionCommand['technicalLevel']; environment: VersionCommand['environment']; mediaReference = '';
  async create() { this.submitted = true; if (!this.name.trim() || !this.instruction.trim()) return; this.creating.set(true); this.error.set(''); try { const version = await this.api.createEditorialExercise({catalogCreateRequest: {canonicalName: this.name.trim(), version: this.command()}}); if (version.versionId) await this.router.navigate(['/admin/exercise-catalog', version.versionId]); } catch { this.error.set('Nie udało się utworzyć szkicu. Sprawdź wymagane pola.'); } finally { this.creating.set(false); } }
  private command(): VersionCommand { return {instruction: this.instruction.trim(), mediaReference: this.mediaReference.trim() || undefined, movementPatterns: new Set(this.patterns) as VersionCommand['movementPatterns'], stimulusType: this.stimulus, fatigueProfile: this.fatigue, technicalLevel: this.level, environment: this.environment, requiredEquipment: new Set(this.equipment)}; }
}
