import {ChangeDetectionStrategy, Component, HostListener, inject, signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute, RouterLink} from '@angular/router';
import {MatButtonModule} from '@angular/material/button';
import {EditorialDetail, ExerciseImportApi, ExerciseImportApiError} from '../core/exercise-import.api';
import {EXERCISE_VERSION_STATUS_LABELS} from './exercise-review.page';

const LABELS: Record<string, string> = {CONTENT:'Treść', TECHNIQUE:'Technika', ANATOMY_EXPOSURE:'Anatomia i ekspozycja', LICENSE:'Licencja', MEDIA:'Materiały', REVIEW_CONTENT_REQUIRED:'Wymagana recenzja treści', REVIEW_TECHNIQUE_REQUIRED:'Wymagana recenzja techniki', REVIEW_ANATOMY_EXPOSURE_REQUIRED:'Wymagana recenzja anatomii i ekspozycji', REVIEW_LICENSE_REQUIRED:'Wymagana recenzja licencji', REVIEW_MEDIA_REQUIRED:'Wymagana recenzja materiałów', LOAD_CHARACTERISTIC_REQUIRED:'Brakuje profilu obciążenia', ANATOMY_EXPOSURE_REQUIRED:'Brakuje anatomii', EVIDENCE_REQUIRED:'Brakuje dowodów', UNRESOLVED_IMPORT_ISSUES:'Są nierozwiązane problemy importu', TWO_INDEPENDENT_REVIEWERS_REQUIRED:'Wymaganych jest dwóch niezależnych recenzentów'};
@Component({selector:'app-exercise-review-detail-page', imports:[FormsModule, RouterLink, MatButtonModule], changeDetection:ChangeDetectionStrategy.OnPush,
template:`<section class="panel"><a mat-button routerLink="/admin/exercise-review">← Wróć do kolejki</a>
@if (loading()) { <p aria-live="polite">Ładowanie szkicu…</p> } @else if (error()) { <p role="alert">{{error()}}</p><button mat-stroked-button (click)="load()">Spróbuj ponownie</button> } @else if (detail(); as d) {
<header><h1>{{d.editor.version.canonicalName}}</h1><p>{{status(d.editor.version.status)}} · wersja {{d.editor.version.versionNumber}}</p>@if (d.importMetadata) {<p class="muted">Źródło: {{d.importMetadata.sourceRecordKey || 'import'}} · rekord {{d.importMetadata.rowNumber}}</p>}</header>
@if(message()){<p aria-live="polite" [class.error]="isError()">{{message()}}</p>}<section><h2>Podstawowe dane</h2>@if(editing()){<form (submit)="save($event)"><label>Nazwa<input name="canonicalName" required [value]="d.editor.version.canonicalName"></label><label>Instrukcja<textarea name="instruction" required>{{d.editor.version.instruction}}</textarea></label><label>Wzorce ruchowe<input name="movementPatterns" required [value]="d.editor.version.movementPatterns.join(', ')"></label><label>Stimulus type<input name="stimulusType" required [value]="d.editor.version.stimulusType"></label><label>Fatigue profile<input name="fatigueProfile" required [value]="d.editor.version.fatigueProfile"></label><label>Poziom techniczny<input name="technicalLevel" required [value]="d.editor.version.technicalLevel"></label><label>Środowisko<input name="environment" required [value]="d.editor.version.environment"></label><label>Sprzęt<input name="requiredEquipment" [value]="d.editor.version.requiredEquipment.join(', ')"></label><button mat-flat-button>Zapisz korektę</button><button mat-button type="button" (click)="editing.set(false)">Anuluj</button></form>} @else {<p>{{d.editor.version.instruction}}</p><p>Wzorce: {{d.editor.version.movementPatterns.join(', ')}}. Sprzęt: {{d.editor.version.requiredEquipment.join(', ') || 'Brak'}}.</p>@if(!readonly()){<button mat-stroked-button (click)="editing.set(true)">Edytuj</button>}}</section>
<section><h2>Profil obciążenia</h2><ul>@for (x of d.editor.loadCharacteristics; track $index) {<li>{{x['movementPlane']}} · {{x['contractionType']}} · {{x['rangeOfMotion']}} · {{x['characteristicType']}}</li>} @empty {<li>Brak profilu obciążenia.</li>}</ul></section><section><h2>Anatomia</h2><ul>@for (x of d.editor.contributions; track x['id']) {<li>{{x['anatomicalStructureId']}} · {{x['role']}} · {{x['loadChannel']}} · {{x['contributionBand']}} · {{x['confidenceClass']}} · {{x['evidenceGrade']}}</li>} @empty {<li>Brak wkładów anatomicznych.</li>}</ul></section><section><h2>Dowody</h2><ul>@for (x of d.editor.evidence; track x['id']) {<li>{{x['citation']}} · {{x['evidenceGrade']}} @if(x['sourceUri']) {<a [href]="safeUri(x['sourceUri'])" target="_blank" rel="noopener noreferrer">Źródło</a>}</li>} @empty {<li>Brak dowodów.</li>}</ul></section>
@if(d.importProblems.length){<section><h2>Problemy importu</h2><ul>@for(p of d.importProblems;track p.code+p.message){<li><strong>{{p.severity}}</strong>: {{p.message}} <span class="muted">{{p.field}}</span></li>}</ul></section>}<section><h2>Recenzje</h2><ul>@for(x of d.review.unmetRequirements;track x){<li>{{label(x)}}</li>}@empty{<li>Wszystkie wymagania są spełnione.</li>}</ul>@if(!readonly()){<label>Komentarz recenzenta<textarea #comment></textarea></label>@for(area of reviewAreas(d);track area){<div class="area"><strong>{{label(area)}}</strong><button mat-stroked-button (click)="review(area,'APPROVED',comment.value)">Zatwierdź obszar</button><button mat-button (click)="review(area,'CHANGES_REQUESTED',comment.value)">Poproś o korektę</button></div>}}@if(d.review.readyToPublish){<button mat-flat-button (click)="publish()">Opublikuj ćwiczenie</button>}@else{<button mat-flat-button disabled aria-describedby="publish-requirements">Opublikuj ćwiczenie</button><span id="publish-requirements" class="muted">Publikacja będzie możliwa po spełnieniu wymagań.</span>}</section><section><h2>Historia i diff</h2><p>Poprzednia wersja: {{d.diff?.['currentPublishedSemanticSha256'] ? 'dostępna' : 'brak'}}</p></section><details><summary>Szczegóły techniczne</summary><p>Checksum szkicu: {{d.diff?.['draftSemanticSha256']}}</p></details>@if(readonly()){<p>Wersja jest opublikowana i nie można jej zmieniać.</p><a mat-flat-button [routerLink]="['/catalog',d.editor.version.exerciseVersionId]">Zobacz w katalogu</a>}
}</section>`, styles:[`label{display:grid;gap:.25rem;margin:.5rem 0}input,textarea{max-width:100%;min-height:2.5rem}textarea{min-height:7rem}.area{display:flex;gap:.5rem;align-items:center;flex-wrap:wrap;margin:.5rem 0}.error{color:#b3261e}@media(max-width:320px){button{max-width:100%}}`]
})
export class ExerciseReviewDetailPage {
 protected readonly detail=signal<EditorialDetail|null>(null); protected readonly loading=signal(true); protected readonly error=signal(''); protected readonly message=signal(''); protected readonly isError=signal(false); protected readonly editing=signal(false); protected readonly readonly=signal(false); private id=''; private readonly api=inject(ExerciseImportApi); private readonly route=inject(ActivatedRoute);
 constructor(){this.id=this.route.snapshot.paramMap.get('versionId')||'';this.load();} @HostListener('window:beforeunload',['$event']) unload(event:BeforeUnloadEvent):void{if(this.editing()){event.preventDefault();event.returnValue=true;}}
 protected load():void{if(!this.id){this.loading.set(false);this.error.set('Nie znaleziono szkicu.');return;}this.loading.set(true);this.error.set('');void this.api.editorialDetail(this.id).then(d=>{this.detail.set(d);this.readonly.set(d.editor.version.status==='PUBLISHED');}).catch(e=>this.error.set(e instanceof ExerciseImportApiError&&e.status===403?'Nie masz uprawnień do tego szkicu.':'Nie udało się pobrać szczegółów szkicu.')).finally(()=>this.loading.set(false));}
 protected save(event:SubmitEvent):void{event.preventDefault();const d=this.detail();if(!d)return;const f=new FormData(event.currentTarget as HTMLFormElement);const v=(n:string)=>String(f.get(n)||'').trim();const current=d.editor.version;void this.api.updateEditorialDraft(this.id,{canonicalName:v('canonicalName'),expectedVersion:d.review.version,version:{instruction:v('instruction'),mediaReference:current.mediaReference,movementPatterns:v('movementPatterns').split(',').map(x=>x.trim()).filter(Boolean),stimulusType:v('stimulusType'),fatigueProfile:v('fatigueProfile'),technicalLevel:v('technicalLevel'),environment:v('environment'),requiredEquipment:v('requiredEquipment').split(',').map(x=>x.trim()).filter(Boolean)}}).then(()=>{this.message.set('Korekta została zapisana.');this.isError.set(false);this.editing.set(false);this.load();}).catch(e=>{this.isError.set(true);this.message.set(e instanceof ExerciseImportApiError&&e.status===409?'Dane zmieniły się w międzyczasie. Pobrano aktualną wersję.':e instanceof Error?e.message:'Nie udało się zapisać korekty.');if(e instanceof ExerciseImportApiError&&e.status===409)this.load();});}
 protected review(area:string,decision:string,comment:string):void{const d=this.detail();if(!d)return;void this.api.review(this.id,area,decision,comment,d.review.version).then(()=>{this.message.set('Zapisano decyzję recenzenta.');this.isError.set(false);this.load();}).catch(e=>{this.isError.set(true);this.message.set(e instanceof Error?e.message:'Nie udało się zapisać recenzji.');});} protected publish():void{const d=this.detail();if(!d)return;void this.api.publish(this.id,d.review.version).then(()=>{this.message.set('Ćwiczenie zostało opublikowane.');this.isError.set(false);this.load();}).catch(e=>{this.isError.set(true);this.message.set(e instanceof Error?e.message:'Nie udało się opublikować ćwiczenia.');});}
 protected status(v:string):string{return EXERCISE_VERSION_STATUS_LABELS[v]??v;} protected label(v:string):string{return LABELS[v]??v;} protected reviewAreas(d:EditorialDetail):string[]{return d.review.requiredAreas;} protected safeUri(value:unknown):string|null{const uri=String(value||'');return /^https?:\/\//.test(uri)?uri:null;}
}
