import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { ApiFacade } from '../core/api.facade';
import { EditorialCapabilities, ExerciseEditorialEditorView, ExerciseEditorialVersionView, ResponseError, VersionCommand } from '../api/generated/src';
import { editorialStatusLabel } from './editorial-status.presentation';

@Component({selector: 'app-exercise-catalog-admin-detail-page', imports: [FormsModule, RouterLink, MatButtonModule], changeDetection: ChangeDetectionStrategy.OnPush, template: `
<section class="panel"><a mat-button routerLink="/admin/exercise-catalog">← Katalog redakcyjny</a>@if (loading()) {<p aria-live="polite">Ładowanie…</p>} @else if (error()) {<p role="alert">{{error()}}</p>} @else if (editor(); as e) {<h1>{{e.version?.canonicalName}}</h1><p>Wersja {{e.version?.versionNumber}} · {{statusLabel(e.version?.status)}}</p>
@if (can('EDIT')) {<form (ngSubmit)="save(e)"><h2>Podstawowe</h2><label>Nazwa <input name="name" [(ngModel)]="name" required /></label><label>Instrukcja <textarea name="instruction" [(ngModel)]="instruction" required></textarea></label><button mat-flat-button>Zapisz szkic</button></form>} @else {<h2>Podstawowe</h2><p>{{e.version?.instruction}}</p>}
<details><summary>Zaawansowane: obciążenie</summary><p>{{e.loadCharacteristics?.length || 0}} charakterystyk.</p></details><details><summary>Zaawansowane: anatomia</summary><p>{{e.contributions?.length || 0}} wkładów.</p></details><details><summary>Dowody</summary><p>{{e.evidence?.length || 0}} źródeł.</p></details>
<h2>Historia wersji</h2><ul>@for (v of versions(); track v.versionId) {<li>Wersja {{v.versionNumber}} · {{statusLabel(v.status)}}</li>}</ul>
<div aria-live="polite">@if (message()) { {{message()}} }</div><div>@if (can('SUBMIT_REVIEW')) {<button mat-stroked-button (click)="action('submitReview')">Przekaż do recenzji</button>} @if (can('REQUEST_CHANGES')) {<button mat-stroked-button (click)="action('requestChanges')">Poproś o zmiany</button>} @if (can('PUBLISH')) {<button mat-flat-button (click)="publish()">Opublikuj</button>} @if (can('WITHDRAW')) {<button mat-stroked-button (click)="action('withdraw')">Wycofaj</button>} @if (can('CREATE_NEXT_VERSION')) {<button mat-stroked-button (click)="next(e)">Utwórz kolejną wersję</button>}</div>}</section>`})
export class ExerciseCatalogAdminDetailPage {
  private readonly api = inject(ApiFacade).catalogAdmin; private readonly id = inject(ActivatedRoute).snapshot.paramMap.get('versionId') ?? '';
  readonly editor = signal<ExerciseEditorialEditorView | null>(null); readonly versions = signal<ExerciseEditorialVersionView[]>([]); readonly capabilities = signal<EditorialCapabilities>({availableActions: []}); readonly loading = signal(true); readonly error = signal(''); readonly message = signal(''); name=''; instruction='';
  readonly statusLabel = editorialStatusLabel;
  constructor() { this.load(); }
  can(action: string) { return this.capabilities().availableActions?.includes(action); }
  async load() { this.loading.set(true); this.error.set(''); try { const editor = await this.api.getEditorialExerciseEditor({versionId: this.id}); if (!editor.version?.exerciseId) throw new Error('Missing exercise id'); this.editor.set(editor); this.name=editor.version.canonicalName ?? ''; this.instruction=editor.version.instruction ?? ''; const [versions, capabilities] = await Promise.all([this.api.listEditorialExerciseVersions({exerciseId: editor.version.exerciseId}), this.api.getEditorialExerciseCapabilities({versionId: this.id})]); this.versions.set(versions); this.capabilities.set(capabilities); } catch (error: unknown) { this.error.set(error instanceof ResponseError && error.response.status === 403 ? 'Brak uprawnień do redakcji katalogu.' : 'Nie udało się pobrać wersji.'); } finally { this.loading.set(false); } }
  async save(editor: ExerciseEditorialEditorView) { const version = editor.version; const expectedVersion = this.capabilities().expectedVersion; if (!version || expectedVersion === undefined) return; try { await this.api.updateEditorialExerciseContent({versionId:this.id, draftUpdateCommand:{canonicalName:this.name, expectedVersion, version:this.command(version)}}); this.message.set('Szkic zapisany.'); await this.load(); } catch { this.message.set('Nie udało się zapisać zmian.'); } }
  async action(action: 'submitReview' | 'requestChanges' | 'withdraw') { try { if (action === 'submitReview') await this.api.submitEditorialExerciseForReview({versionId:this.id}); else if (action === 'requestChanges') await this.api.requestEditorialExerciseChanges({versionId:this.id}); else await this.api.withdrawEditorialExercise({versionId:this.id}); this.message.set('Stan wersji został zmieniony.'); await this.load(); } catch { this.message.set('Nie udało się zmienić stanu wersji.'); } }
  async publish() { const expectedVersion = this.capabilities().expectedVersion; if (expectedVersion === undefined) return; try { await this.api.publishEditorialExercise({versionId:this.id, publishRequest:{expectedVersion}}); this.message.set('Wersja opublikowana.'); await this.load(); } catch { this.message.set('Publikacja nie jest jeszcze możliwa.'); } }
  async next(editor: ExerciseEditorialEditorView) { const source = editor.version; if (!source?.exerciseId) return; try { const version = await this.api.createEditorialExerciseVersion({exerciseId:source.exerciseId, versionCommand:this.command(source)}); if (version.versionId) window.location.assign('/admin/exercise-catalog/' + version.versionId); } catch { this.message.set('Nie udało się utworzyć kolejnej wersji.'); } }
  private command(version: ExerciseEditorialVersionView): VersionCommand { return {instruction: version.instruction, mediaReference: version.mediaReference, movementPatterns: version.movementPatterns as VersionCommand['movementPatterns'], stimulusType: version.stimulusType as VersionCommand['stimulusType'], fatigueProfile: version.fatigueProfile as VersionCommand['fatigueProfile'], technicalLevel: version.technicalLevel as VersionCommand['technicalLevel'], environment: version.environment as VersionCommand['environment'], requiredEquipment: version.requiredEquipment}; }
}
