import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { ApiFacade } from '../core/api.facade';
import { AnatomicalStructureSnapshot, ContributionCommand, EditorialCapabilities, ExerciseEditorialEditorView, ExerciseEditorialVersionView, LoadCharacteristicCommand, LoadCharacteristicCommandCharacteristicTypeEnum, LoadCharacteristicCommandContractionTypeEnum, LoadCharacteristicCommandMovementPlaneEnum, LoadCharacteristicCommandRangeOfMotionEnum, ResponseError, VersionCommand } from '../api/generated/src';
import { editorialStatusLabel } from './editorial-status.presentation';
import { ExerciseCatalogMultiChoiceComponent } from './exercise-catalog-multi-choice.component';
import { environmentOptions, equipmentOptionsFor, fatigueOptions, movementPatternOptions, stimulusOptions, technicalLevelOptions } from './exercise-catalog-options';

const readinessLabels: Record<string, string> = { PROFILE_SCHEMA_V2_REQUIRED: 'zapisz aktualny profil wersji', MOVEMENT_PATTERN_REQUIRED: 'wybierz co najmniej jeden wzorzec ruchowy', STIMULUS_TYPE_REQUIRED: 'wybierz typ bodźca', FATIGUE_PROFILE_REQUIRED: 'wybierz profil zmęczenia', TECHNICAL_LEVEL_REQUIRED: 'wybierz poziom techniczny', ENVIRONMENT_REQUIRED: 'wybierz środowisko', LOAD_CHARACTERISTIC_REQUIRED: 'dodaj charakterystykę obciążenia', ANATOMY_CONTRIBUTION_REQUIRED: 'dodaj wkład anatomiczny', CONTRIBUTION_EVIDENCE_REQUIRED: 'przypisz dowód do każdego wkładu anatomicznego', PUBLISHED_ANATOMY_REQUIRED: 'wybierz opublikowaną strukturę anatomiczną', ALLOCATION_BRANCH_CONFLICT: 'usuń nakładające się gałęzie alokacji', UNRESOLVED_IMPORT_ISSUES: 'rozwiąż problemy importu' };

@Component({selector: 'app-exercise-catalog-admin-detail-page', imports: [FormsModule, RouterLink, MatButtonModule, ExerciseCatalogMultiChoiceComponent], changeDetection: ChangeDetectionStrategy.OnPush, template: `
<section class="panel"><a mat-button routerLink="/admin/exercise-catalog">← Katalog</a>
@if (loading()) {<p aria-live="polite">Ładowanie…</p>} @else if (error()) {<p role="alert">{{error()}}</p><button mat-stroked-button (click)="load()">Spróbuj ponownie</button>} @else if (editor(); as e) {
<h1>{{e.version?.canonicalName}}</h1><p>Wersja {{e.version?.versionNumber}} · {{statusLabel(e.version?.status)}}</p>@if (message()) {<p aria-live="polite" [class.error]="messageError()">{{message()}}</p>}
@if (editable()) {<form class="exercise-editor" (ngSubmit)="save(e)"><section><h2>Podstawowe informacje</h2><div class="editor-grid"><label class="wide">Nazwa * <input class="app-native-control" name="name" [(ngModel)]="name" required #nameControl="ngModel" /></label>@if ((nameControl.touched || submitted) && nameControl.invalid) {<p class="field-error">Nazwa jest wymagana.</p>}<label class="wide">Instrukcja * <textarea class="app-native-control" name="instruction" [(ngModel)]="instruction" rows="5" required #instructionControl="ngModel"></textarea></label>@if ((instructionControl.touched || submitted) && instructionControl.invalid) {<p class="field-error">Instrukcja jest wymagana.</p>}<label class="wide">Referencja do materiału <input class="app-native-control" name="media" [(ngModel)]="mediaReference" /></label></div></section><section><h2>Klasyfikacja</h2><div class="editor-grid"><app-exercise-catalog-multi-choice class="wide" name="patterns" label="Wzorce ruchowe" [options]="movementPatternOptions" [selection]="patterns" (selectionChange)="patterns = $event" /><label>Typ bodźca <select class="app-native-control" name="stimulus" [(ngModel)]="stimulus"><option [ngValue]="undefined">Wybierz…</option>@for (option of stimulusOptions; track option.value) {<option [value]="option.value">{{option.label}}</option>}</select></label><label>Profil zmęczenia <select class="app-native-control" name="fatigue" [(ngModel)]="fatigue"><option [ngValue]="undefined">Wybierz…</option>@for (option of fatigueOptions; track option.value) {<option [value]="option.value">{{option.label}}</option>}</select></label><label>Poziom techniczny <select class="app-native-control" name="level" [(ngModel)]="level"><option [ngValue]="undefined">Wybierz…</option>@for (option of technicalLevelOptions; track option.value) {<option [value]="option.value">{{option.label}}</option>}</select></label></div></section><section><h2>Warunki wykonania</h2><div class="editor-grid"><label>Środowisko <select class="app-native-control" name="environment" [(ngModel)]="environment"><option [ngValue]="undefined">Wybierz…</option>@for (option of environmentOptions; track option.value) {<option [value]="option.value">{{option.label}}</option>}</select></label><app-exercise-catalog-multi-choice class="wide" name="equipment" label="Wymagany sprzęt" [options]="equipmentOptions" [selection]="equipment" [allowCustom]="true" (selectionChange)="equipment = $event" /></div></section><button mat-flat-button [disabled]="saving()">Zapisz szkic</button></form>} @else {<h2>Podstawowe dane i media</h2><p>{{e.version?.instruction}}</p><p>Materiał: {{e.version?.mediaReference || 'brak'}}</p>}
<details open><summary>Profil obciążenia</summary>@if (editable()) {@for (load of loads; track $index) {<div><label>Typ <select class="app-native-control" [name]="'type'+$index" [(ngModel)]="load.characteristicType">@for (x of characteristicTypes; track x) {<option [value]="x">{{x}}</option>}</select></label><label>Płaszczyzna <select class="app-native-control" [name]="'plane'+$index" [(ngModel)]="load.movementPlane">@for (x of movementPlanes; track x) {<option [value]="x">{{x}}</option>}</select></label><label>Skurcz <select class="app-native-control" [name]="'contraction'+$index" [(ngModel)]="load.contractionType">@for (x of contractionTypes; track x) {<option [value]="x">{{x}}</option>}</select></label><label>Zakres <select class="app-native-control" [name]="'range'+$index" [(ngModel)]="load.rangeOfMotion">@for (x of ranges; track x) {<option [value]="x">{{x}}</option>}</select></label><button mat-button type="button" (click)="removeLoad($index)">Usuń</button></div>}<button mat-button type="button" (click)="addLoad()">Dodaj charakterystykę</button><button mat-stroked-button (click)="saveLoads()">Zapisz profil obciążenia</button>} @else {<ul>@for (load of e.loadCharacteristics ?? []; track $index) {<li>{{load.characteristicType}} · {{load.movementPlane}} · {{load.contractionType}} · {{load.rangeOfMotion}}</li>}</ul>}</details>
<details open><summary>Dowody</summary><ul>@for (item of e.evidence ?? []; track item.id) {<li>{{item.citation}} · {{item.evidenceGrade}} @if (editable()) {<button mat-button (click)="editEvidence(item)">Edytuj</button><button mat-button (click)="removeEvidence(item.id)">Usuń</button>}</li>} @empty {<li>Brak dowodów.</li>}</ul>@if (editable()) {<label>Cytowanie <input class="app-native-control" name="citation" [(ngModel)]="citation" /></label><label>Stopień dowodu <input class="app-native-control" name="grade" [(ngModel)]="evidenceGrade" /></label><label>Adres źródła <input class="app-native-control" name="source" [(ngModel)]="sourceUri" /></label><button mat-stroked-button (click)="saveEvidence()">{{editingEvidenceId() ? 'Zapisz dowód' : 'Dodaj dowód'}}</button>}</details>
<details open><summary>Anatomia</summary><ul>@for (item of e.contributions ?? []; track item.id) {<li>{{item.anatomicalStructureId}} · {{item.role}} · {{item.loadChannel}} @if (editable()) {<button mat-button (click)="editContribution(item)">Edytuj</button><button mat-button (click)="removeContribution(item.id)">Usuń</button>}</li>} @empty {<li>Brak wkładów anatomicznych.</li>}</ul>@if (editable()) {<label>Wyszukaj opublikowaną strukturę <input class="app-native-control" name="anatomyQuery" [(ngModel)]="anatomyQuery" (input)="searchAnatomy()" /></label><ul>@for (structure of structures(); track structure.id) {<li><button mat-button (click)="selectStructure(structure)">{{structure.displayName}}</button></li>}</ul>@if (selectedStructure() || editingContribution()) {<p>Wybrano: {{selectedStructure()?.displayName || editingContribution()?.anatomicalStructureId}}</p><label>Rola <select class="app-native-control" name="role" [(ngModel)]="role"><option>PRIMARY</option><option>SECONDARY</option><option>STABILIZER</option></select></label><label>Kanał <select class="app-native-control" name="channel" [(ngModel)]="loadChannel"><option>DYN_EXU</option><option>ISO_SEC</option><option>IMPACT_CONTACTS</option><option>ENDURANCE_MIN_ZONE</option></select></label><label>Współczynnik od <input class="app-native-control" type="number" min="0" max="1" step="0.000001" name="coefficientLow" [(ngModel)]="coefficientLow" /></label><label>do <input class="app-native-control" type="number" min="0" max="1" step="0.000001" name="coefficientHigh" [(ngModel)]="coefficientHigh" /></label><label>Dowody <select class="app-native-control" multiple name="contributionEvidence" [(ngModel)]="contributionEvidenceIds">@for (evidence of e.evidence ?? []; track evidence.id) {<option [value]="evidence.id">{{evidence.citation}}</option>}</select></label><button mat-stroked-button (click)="saveContribution()">{{editingContribution() ? 'Zapisz wkład' : 'Dodaj wkład'}}</button>}}</details>
<details><summary>Pochodzenie i problemy importu</summary><p>Informacje o imporcie są dostępne w rekordzie wymagającym uwagi; po korekcie i utworzeniu szkicu nie wymagają akceptacji recenzenta.</p></details>
<h2>Gotowość do publikacji</h2><ul>@for (missing of capabilities().readiness?.unmetRequirements ?? []; track missing) {<li>{{readinessLabel(missing)}}</li>} @empty {<li>Wymagania są spełnione.</li>}</ul>
<h2>Historia wersji</h2><ul>@for (v of versions(); track v.versionId) {<li>Wersja {{v.versionNumber}} · {{statusLabel(v.status)}}</li>}</ul>
<p>@if (can('PUBLISH')) {<button mat-flat-button (click)="publish()">Opublikuj</button>} @if (can('WITHDRAW')) {<button mat-stroked-button (click)="withdraw()">Wycofaj</button>} @if (can('CREATE_NEXT_VERSION')) {<button mat-stroked-button (click)="next(e)">Utwórz kolejną wersję</button>} @if (can('DELETE')) {<button mat-button (click)="deleteDraft()">Usuń początkowy szkic</button>} @else if (capabilities().deleteBlockReason) {<span class="muted">Usunięcie niedostępne: {{capabilities().deleteBlockReason}}</span>}</p>
}</section>`})
export class ExerciseCatalogAdminDetailPage {
  private readonly api = inject(ApiFacade).catalogAdmin; private readonly anatomy = inject(ApiFacade).anatomyReferenceAdmin; private readonly router = inject(Router); private readonly id = inject(ActivatedRoute).snapshot.paramMap.get('versionId') ?? '';
  readonly editor = signal<ExerciseEditorialEditorView | null>(null); readonly versions = signal<ExerciseEditorialVersionView[]>([]); readonly capabilities = signal<EditorialCapabilities>({availableActions: []}); readonly loading = signal(true); readonly error = signal(''); readonly message = signal(''); readonly messageError = signal(false); readonly saving = signal(false); readonly structures = signal<AnatomicalStructureSnapshot[]>([]); readonly selectedStructure = signal<AnatomicalStructureSnapshot | null>(null); readonly editingEvidenceId = signal<string | null>(null); readonly editingContribution = signal<any | null>(null);
  submitted = false; name=''; instruction=''; patterns: string[] = []; stimulus: VersionCommand['stimulusType']; fatigue: VersionCommand['fatigueProfile']; level: VersionCommand['technicalLevel']; environment: VersionCommand['environment']; equipment: string[] = []; mediaReference=''; loads: LoadCharacteristicCommand[] = []; citation=''; evidenceGrade=''; sourceUri=''; anatomyQuery=''; role='PRIMARY'; loadChannel='DYN_EXU'; coefficientLow = 0; coefficientHigh = 1; contributionEvidenceIds: string[] = [];
  readonly characteristicTypes = Object.values(LoadCharacteristicCommandCharacteristicTypeEnum); readonly movementPlanes = Object.values(LoadCharacteristicCommandMovementPlaneEnum); readonly contractionTypes = Object.values(LoadCharacteristicCommandContractionTypeEnum); readonly ranges = Object.values(LoadCharacteristicCommandRangeOfMotionEnum); readonly movementPatternOptions = movementPatternOptions; readonly stimulusOptions = stimulusOptions; readonly fatigueOptions = fatigueOptions; readonly technicalLevelOptions = technicalLevelOptions; readonly environmentOptions = environmentOptions;
  get equipmentOptions() { return equipmentOptionsFor(this.equipment); }
  readonly statusLabel = editorialStatusLabel; readonly readinessLabel = (value: string) => readinessLabels[value] ?? value;
  constructor() { void this.load(); }
  can(action: string) { return this.capabilities().availableActions?.includes(action) ?? false; } editable() { return this.can('EDIT'); }
  async load() { this.loading.set(true); this.error.set(''); try { const editor = await this.api.getEditorialExerciseEditor({versionId: this.id}); if (!editor.version?.exerciseId) throw new Error('missing exercise'); this.editor.set(editor); this.populate(editor.version); const [versions, capabilities] = await Promise.all([this.api.listEditorialExerciseVersions({exerciseId: editor.version.exerciseId}), this.api.getEditorialExerciseCapabilities({versionId: this.id})]); this.versions.set(versions); this.capabilities.set(capabilities); } catch (e) { this.error.set(e instanceof ResponseError && e.response.status === 403 ? 'Brak uprawnień do redakcji katalogu.' : 'Nie udało się pobrać wersji.'); } finally { this.loading.set(false); } }
  async save(editor: ExerciseEditorialEditorView) { this.submitted = true; const expectedVersion = this.expected(); if (!this.name.trim() || !this.instruction.trim() || !editor.version || expectedVersion === undefined) return; await this.run(() => this.api.updateEditorialExerciseContent({versionId: this.id, draftUpdateCommand: {canonicalName: this.name.trim(), expectedVersion, version: this.command()}}), 'Szkic zapisany.'); }
  addLoad() { this.loads = [...this.loads, {characteristicType: 'DYNAMIC', movementPlane: 'SAGITTAL', contractionType: 'CONCENTRIC', rangeOfMotion: 'FULL'}]; }
  removeLoad(index: number) { this.loads = this.loads.filter((_, current) => current !== index); }
  async saveLoads() { const expectedVersion = this.expected(); if (expectedVersion === undefined || !this.loads.length || this.loads.some(item => !item.characteristicType || !item.movementPlane || !item.contractionType || !item.rangeOfMotion)) { this.fail('Każda charakterystyka wymaga czterech pól.'); return; } await this.run(() => this.api.replaceEditorialLoadCharacteristics({versionId: this.id, loadCharacteristicCommand: this.loads, expectedVersion}), 'Profil obciążenia zapisany.'); }
  editEvidence(item: any) { this.editingEvidenceId.set(item.id ?? null); this.citation=item.citation ?? ''; this.evidenceGrade=item.evidenceGrade ?? ''; this.sourceUri=item.sourceUri ?? ''; }
  async saveEvidence() { const expectedVersion = this.expected(); if (expectedVersion === undefined) return; const evidenceId = this.editingEvidenceId(); const command = {citation: this.citation, evidenceGrade: this.evidenceGrade, sourceUri: this.sourceUri}; await this.run(() => evidenceId ? this.api.updateEditorialEvidence({versionId: this.id, evidenceId, evidenceUpdateCommand: {...command, expectedVersion}}) : this.api.addEditorialEvidence({versionId: this.id, expectedVersion, evidenceCommand: command}), evidenceId ? 'Dowód zapisany.' : 'Dowód dodany.'); this.editingEvidenceId.set(null); }
  async removeEvidence(evidenceId?: string) { const expectedVersion = this.expected(); if (!evidenceId || expectedVersion === undefined) return; await this.run(() => this.api.deleteEditorialEvidence({versionId: this.id, evidenceId, expectedVersion}), 'Dowód usunięty.'); }
  async searchAnatomy() { this.structures.set(await this.anatomy.listPublishedAnatomicalStructures({query: this.anatomyQuery, limit: 10})); }
  selectStructure(structure: AnatomicalStructureSnapshot) { this.selectedStructure.set(structure); }
  editContribution(item: any) { this.editingContribution.set(item); this.role=item.role ?? 'PRIMARY'; this.loadChannel=item.loadChannel ?? 'DYN_EXU'; this.coefficientLow=item.coefficientLow ?? 0; this.coefficientHigh=item.coefficientHigh ?? 1; this.contributionEvidenceIds=(item.evidence ?? []).map((evidence: any) => evidence.id).filter(Boolean); }
  async saveContribution() { const expectedVersion = this.expected(); const current = this.editingContribution(); const structure = this.selectedStructure(); const anatomicalStructureId = current?.anatomicalStructureId ?? structure?.id; if (!anatomicalStructureId || expectedVersion === undefined || !this.contributionEvidenceIds.length || this.coefficientLow < 0 || this.coefficientHigh > 1 || this.coefficientLow > this.coefficientHigh) { this.fail('Wybierz dowód i podaj przedział od 0 do 1 (maks. sześć miejsc po przecinku).'); return; } const contribution: ContributionCommand = {anatomicalStructureId, role: this.role as never, loadChannel: this.loadChannel as never, contributionBand: current?.contributionBand ?? 'MODERATE', calculationRole: current?.calculationRole ?? 'DESCRIPTIVE_ONLY', sideRule: current?.sideRule ?? 'NOT_APPLICABLE', coefficientLow: this.coefficientLow, coefficientHigh: this.coefficientHigh, confidenceClass: current?.confidenceClass, evidenceGrade: current?.evidenceGrade, variantCondition: current?.variantCondition, evidenceSourceIds: new Set(this.contributionEvidenceIds)}; await this.run(() => current?.id ? this.api.updateEditorialContribution({versionId: this.id, contributionId: current.id, contributionUpdateCommand: {expectedVersion, contribution}}) : this.api.addEditorialContribution({versionId: this.id, expectedVersion, contributionCommand: contribution}), current?.id ? 'Wkład anatomiczny zapisany.' : 'Wkład anatomiczny dodany.'); this.editingContribution.set(null); }
  async removeContribution(contributionId?: string) { const expectedVersion = this.expected(); if (!contributionId || expectedVersion === undefined) return; await this.run(() => this.api.deleteEditorialContribution({versionId: this.id, contributionId, expectedVersion}), 'Wkład anatomiczny usunięty.'); }
  async publish() { const expectedVersion = this.expected(); if (expectedVersion === undefined) return; await this.run(() => this.api.publishEditorialExercise({versionId: this.id, publishRequest: {expectedVersion}}), 'Wersja opublikowana.'); }
  async withdraw() { await this.run(() => this.api.withdrawEditorialExercise({versionId: this.id}), 'Wersja wycofana.'); }
  async next(editor: ExerciseEditorialEditorView) { const version = editor.version; if (!version?.exerciseId) return; try { const next = await this.api.createEditorialExerciseVersion({exerciseId: version.exerciseId, versionCommand: this.command()}); if (next.versionId) await this.router.navigate(['/admin/exercise-catalog', next.versionId]); } catch { this.fail('Nie udało się utworzyć kolejnej wersji.'); } }
  async deleteDraft() { const expectedVersion = this.expected(); if (expectedVersion === undefined || !confirm('Usunąć wyłącznie początkowy szkic bez referencji?')) return; try { await this.api.deleteEditorialInitialDraft({versionId: this.id, deleteDraftRequest: {expectedVersion}}); await this.router.navigate(['/admin/exercise-catalog']); } catch { this.fail('Nie można usunąć szkicu. Mógł przestać spełniać warunki bezpiecznego usunięcia.'); } }
  private populate(version: ExerciseEditorialVersionView) { this.submitted=false; this.name=version.canonicalName ?? ''; this.instruction=version.instruction ?? ''; this.patterns=Array.from(version.movementPatterns ?? []); this.stimulus=version.stimulusType; this.fatigue=version.fatigueProfile; this.level=version.technicalLevel; this.environment=version.environment; this.equipment=Array.from(version.requiredEquipment ?? []); this.mediaReference=version.mediaReference ?? ''; this.loads=(this.editor()?.loadCharacteristics ?? []).map(item => ({characteristicType:item.characteristicType, movementPlane:item.movementPlane, contractionType:item.contractionType, rangeOfMotion:item.rangeOfMotion})); }
  private command(): VersionCommand { return {instruction: this.instruction.trim(), mediaReference: this.mediaReference.trim() || undefined, movementPatterns: new Set(this.patterns) as VersionCommand['movementPatterns'], stimulusType: this.stimulus, fatigueProfile: this.fatigue, technicalLevel: this.level, environment: this.environment, requiredEquipment: new Set(this.equipment)}; }
  private expected() { return this.capabilities().expectedVersion; }
  private async run(action: () => Promise<unknown>, success: string) { try { await action(); this.message.set(success); this.messageError.set(false); await this.load(); } catch (e) { this.fail(e instanceof ResponseError && e.response.status === 409 ? 'Dane zmieniły się w międzyczasie. Wersja została odświeżona; sprawdź zmiany i spróbuj ponownie.' : 'Operacja nie powiodła się. Sprawdź wymagane dane.'); if (e instanceof ResponseError && e.response.status === 409) await this.load(); } }
  private fail(text: string) { this.message.set(text); this.messageError.set(true); }
}
