import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';
import { FormArray, FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { RouterLink } from '@angular/router';
import { ProfileTypeRequestProfileTypeEnum, SlotRequestDayOfWeekEnum, type StateProfileTypeEnum } from '../api/generated/src';

export type ProgressStep = { label: string; state: 'complete' | 'current' | 'blocked' | 'upcoming' };
export type ProfileValue = { displayName: string; specialistKind: string; timeZoneId: string };

@Component({ selector: 'app-onboarding-progress', standalone: true, template: `<ol class="onboarding-progress" aria-label="Postęp onboardingu">@for (step of steps; track step.label) { <li [class]="step.state" [attr.aria-current]="step.state === 'current' ? 'step' : null"><span aria-hidden="true">{{ step.state === 'complete' ? '✓' : step.state === 'blocked' ? '!' : '' }}</span>{{ step.label }}</li> }</ol>`, styles: [`.onboarding-progress { display:grid; grid-template-columns:repeat(4,1fr); gap:.5rem; list-style:none; padding:0; margin:0; } li { min-height:44px; padding:.65rem; border-radius:.75rem; color:var(--muted); border:1px solid var(--line); font-size:.86rem; } li.current { color:var(--ink); border-color:var(--accent); background:#76d7c422; font-weight:700; } li.complete { color:var(--ink); } li.blocked { color:var(--ink); border-color:#e4ab50; } li span { margin-right:.35rem; } @media (max-width:480px) { .onboarding-progress { grid-template-columns:repeat(2,1fr); } }`], changeDetection: ChangeDetectionStrategy.OnPush })
export class OnboardingProgressComponent { @Input({ required: true }) steps: ProgressStep[] = []; }

@Component({ selector: 'app-onboarding-profile-type', standalone: true, imports: [MatButtonModule, MatCardModule], template: `<mat-card class="onboarding-card"><mat-card-header><mat-card-title><h2 tabindex="-1">Wybierz typ profilu</h2></mat-card-title></mat-card-header><mat-card-content><p>Wybór zapisze się dopiero po wybraniu „Kontynuuj”.</p><div class="role-options"><button mat-stroked-button type="button" [class.selected]="selected === types.Participant" [attr.aria-pressed]="selected === types.Participant" (click)="selected = types.Participant">Uczestnik</button><button mat-stroked-button type="button" [class.selected]="selected === types.Specialist" [attr.aria-pressed]="selected === types.Specialist" (click)="selected = types.Specialist">Specjalista</button></div></mat-card-content><mat-card-actions><button mat-flat-button type="button" [disabled]="!selected || busy" (click)="continue.emit(selected!)">Kontynuuj</button></mat-card-actions></mat-card>`, styles: [`.role-options { display:flex; flex-wrap:wrap; gap:.75rem; } .selected { border-color:var(--accent); background:#76d7c422; }`], changeDetection: ChangeDetectionStrategy.OnPush })
export class OnboardingProfileTypeComponent { protected readonly types = ProfileTypeRequestProfileTypeEnum; @Input() busy = false; @Output() readonly continue = new EventEmitter<ProfileTypeRequestProfileTypeEnum>(); protected selected?: ProfileTypeRequestProfileTypeEnum; }

@Component({ selector: 'app-onboarding-legal-blocker', standalone: true, imports: [MatCardModule], template: `<mat-card class="onboarding-card legal-blocker" role="alert"><mat-card-header><mat-card-title><h2 tabindex="-1">Dokumenty</h2></mat-card-title></mat-card-header><mat-card-content><p>Nie możemy bezpiecznie pokazać dokumentów do akceptacji: w aplikacji nie ma zatwierdzonych publicznych treści ani adresów dokumentów.</p></mat-card-content></mat-card>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class OnboardingLegalBlockerComponent {}

@Component({ selector: 'app-onboarding-basic-profile', standalone: true, imports: [ReactiveFormsModule, MatButtonModule, MatCardModule, MatFormFieldModule, MatInputModule, MatSelectModule], template: `<mat-card class="onboarding-card"><mat-card-header><mat-card-title><h2 tabindex="-1">Dane profilu</h2></mat-card-title></mat-card-header><mat-card-content><form class="form-grid" [formGroup]="form" (ngSubmit)="saved.emit(form.getRawValue())"><mat-form-field><mat-label>Nazwa wyświetlana</mat-label><input matInput formControlName="displayName" autocomplete="name"></mat-form-field>@if (profileType === 'SPECIALIST') { <mat-form-field><mat-label>Rodzaj specjalisty</mat-label><mat-select formControlName="specialistKind"><mat-option value="TRAINER">Trener</mat-option><mat-option value="PHYSIOTHERAPIST">Fizjoterapeuta</mat-option></mat-select></mat-form-field> } @if (profileType === 'PARTICIPANT') { <mat-form-field><mat-label>Strefa czasowa</mat-label><input matInput formControlName="timeZoneId" autocomplete="off"></mat-form-field> }<div class="full"><button mat-flat-button type="submit" [disabled]="form.invalid || busy">Zapisz profil</button></div></form></mat-card-content></mat-card>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class OnboardingBasicProfileComponent { @Input({ required: true }) form!: FormGroup<{ displayName: FormControl<string>; specialistKind: FormControl<string>; timeZoneId: FormControl<string> }>; @Input() profileType?: StateProfileTypeEnum; @Input() busy = false; @Output() readonly saved = new EventEmitter<ProfileValue>(); }

@Component({ selector: 'app-onboarding-availability', standalone: true, imports: [ReactiveFormsModule, MatButtonModule, MatCardModule, MatFormFieldModule, MatInputModule, MatSelectModule], template: `<mat-card class="onboarding-card"><mat-card-header><mat-card-title><h2 tabindex="-1">Dostępność cykliczna</h2></mat-card-title></mat-card-header><mat-card-content><p>Dodaj wszystkie powtarzalne terminy, w których jesteś dostępny/a.</p><form [formGroup]="form" (ngSubmit)="saved.emit()"><div formArrayName="slots" class="availability-list">@for (slot of slots.controls; track $index; let index = $index) { <fieldset [formGroupName]="index"><legend>Termin {{ index + 1 }}</legend><mat-form-field><mat-label>Dzień</mat-label><mat-select formControlName="dayOfWeek">@for (day of days; track day.value) { <mat-option [value]="day.value">{{ day.label }}</mat-option> }</mat-select></mat-form-field><mat-form-field><mat-label>Od</mat-label><input matInput type="time" formControlName="startTime"></mat-form-field><mat-form-field><mat-label>Do</mat-label><input matInput type="time" formControlName="endTime"></mat-form-field><mat-form-field><mat-label>Strefa czasowa</mat-label><input matInput formControlName="timeZone" autocomplete="off"></mat-form-field><button mat-button type="button" (click)="remove.emit(index)" [disabled]="slots.length === 1">Usuń termin</button></fieldset> }</div><div class="availability-actions"><button mat-stroked-button type="button" (click)="add.emit()">Dodaj termin</button><button mat-flat-button type="submit" [disabled]="form.invalid || busy">Zapisz dostępność</button></div></form></mat-card-content></mat-card>`, styles: [`.availability-list { display:grid; gap:1rem; } fieldset { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:.5rem; border:1px solid var(--line); border-radius:.75rem; } .availability-actions { display:flex; flex-wrap:wrap; gap:.75rem; margin-top:1rem; } @media (max-width:680px) { fieldset { grid-template-columns:1fr 1fr; } } @media (max-width:360px) { fieldset { grid-template-columns:1fr; } .availability-actions button { width:100%; } }`], changeDetection: ChangeDetectionStrategy.OnPush })
export class OnboardingAvailabilityComponent { @Input({ required: true }) form!: FormGroup<{ slots: FormArray }>; @Input() busy = false; @Output() readonly add = new EventEmitter<void>(); @Output() readonly remove = new EventEmitter<number>(); @Output() readonly saved = new EventEmitter<void>(); protected readonly days = [{ value: SlotRequestDayOfWeekEnum.Monday, label: 'Poniedziałek' }, { value: SlotRequestDayOfWeekEnum.Tuesday, label: 'Wtorek' }, { value: SlotRequestDayOfWeekEnum.Wednesday, label: 'Środa' }, { value: SlotRequestDayOfWeekEnum.Thursday, label: 'Czwartek' }, { value: SlotRequestDayOfWeekEnum.Friday, label: 'Piątek' }, { value: SlotRequestDayOfWeekEnum.Saturday, label: 'Sobota' }, { value: SlotRequestDayOfWeekEnum.Sunday, label: 'Niedziela' }]; get slots(): FormArray { return this.form.controls.slots; } }

@Component({ selector: 'app-onboarding-completion', standalone: true, imports: [MatButtonModule, MatCardModule, RouterLink], template: `<mat-card class="onboarding-card completion"><mat-card-header><mat-card-title><h2 tabindex="-1">Profil gotowy</h2></mat-card-title></mat-card-header><mat-card-content><p>Onboarding ukończony. Twój profil jest gotowy do użycia.</p></mat-card-content><mat-card-actions><a mat-flat-button routerLink="/catalog">Przejdź do katalogu</a></mat-card-actions></mat-card>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class OnboardingCompletionComponent {}
