import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output, computed, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MAT_DATE_LOCALE, MatNativeDateModule } from '@angular/material/core';
import { MatButtonModule } from '@angular/material/button';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatRadioModule } from '@angular/material/radio';
import { MatSelectModule } from '@angular/material/select';
import { ApiFacade } from '../core/api.facade';
import { ResponseError } from '../api/generated/src/runtime';
import type { InterviewView } from '../api/generated/src/models/InterviewView';
import type { NoteView } from '../api/generated/src/models/NoteView';
import type { Question } from '../api/generated/src/models/Question';
import { noteCategoryLabel, noteStatusLabel, questionOptions, questionSection, questionTitle, safeSnapshotText, selectionLabel } from './specialist-participant-workspace.presentation';

export type RecordPanelType = 'interview' | 'note';
type InterviewSection = { name: string; questions: Question[] };

const SECTION_ORDER = ['Cel wizyty', 'Zdrowie i bezpieczeństwo', 'Ból i urazy', 'Aktywność i codzienność', 'Zgody i ustalenia'];

@Component({
  selector: 'app-participant-documentation', standalone: true,
  imports: [MatButtonModule, MatDatepickerModule, MatFormFieldModule, MatInputModule, MatNativeDateModule, MatRadioModule, MatSelectModule, ReactiveFormsModule],
  providers: [{ provide: MAT_DATE_LOCALE, useValue: 'pl-PL' }],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styleUrl: './participant-documentation.component.scss',
  styles: [`.interview-actions{position:sticky;bottom:0;padding:.75rem 0;display:flex;gap:.5rem;flex-wrap:wrap;background:var(--mat-sys-surface,white);z-index:1}.section-tabs{display:grid;gap:.5rem;margin:0 0 1rem}.section-tabs button{text-align:left;border-left:3px solid var(--app-border,#ddd)}.section-tabs button.active{border-color:var(--app-primary,#6750a4);font-weight:700}.interview-question{display:block;margin:1rem 0}.interview-question mat-form-field{width:100%}.field-error{color:var(--mat-sys-error,#b3261e);margin:-.5rem 0 .5rem}.section-content{max-width:48rem}.record-panel-body{padding-bottom:4.5rem}.new-note-form{display:grid;gap:1.125rem;max-width:48rem;margin-top:1.5rem}.new-note-form mat-form-field{width:100%}.new-note-form textarea{min-height:10rem;resize:vertical}.new-note-actions{display:flex;flex-wrap:wrap;gap:.5rem;padding-top:1rem;border-top:1px solid var(--app-border,#ddd)}`],
  template: `<section class="records-workspace" aria-labelledby="records-title">
    <div class="records-heading"><div><h2 id="records-title">Wywiad i notatki</h2><p>Dokumentacja klienta</p></div></div>
    <p class="sr-only" aria-live="polite">{{ announcement() }}</p>
    <div class="records-summary-grid"><section class="record-summary" aria-labelledby="interview-summary-title"><div><h3 id="interview-summary-title">Wywiad</h3><p>{{ interviewSummary() }}</p></div>@if (latestInterview(); as current) { @if (can(current, 'SAVE_DRAFT')) { <button mat-stroked-button type="button" (click)="open('interview', current.id, 'edit')">Kontynuuj wywiad</button> } @else if (can(current, 'START_NEXT_INTERVIEW')) { <button mat-flat-button type="button" (click)="startInterview()" [disabled]="busy()">Aktualizuj wywiad</button> } @else { <button mat-stroked-button type="button" (click)="open('interview', current.id)">Otwórz</button> } } @else { <button mat-flat-button type="button" (click)="startInterview()" [disabled]="busy() || !ready()">Rozpocznij wywiad</button> }</section>
      <section class="record-summary" aria-labelledby="notes-summary-title"><div><h3 id="notes-summary-title">Notatki</h3><p>{{ notesSummary() }}</p></div><button mat-flat-button type="button" (click)="openNewNote()" [disabled]="busy() || !ready()">Nowa notatka</button>@if (latestNote(); as current) { <button mat-stroked-button type="button" (click)="open('note', current.id)">Ostatnia</button> }</section></div>
    @if (creatingNote()) { <form class="new-note-form" [formGroup]="newNoteForm" (ngSubmit)="createNote()"><h3>Nowa notatka</h3><mat-form-field><mat-label>Tytuł</mat-label><input matInput formControlName="title" required>@if (newNoteInvalid('title')) { <mat-error>Tytuł jest wymagany.</mat-error> }</mat-form-field><mat-form-field><mat-label>Kategoria</mat-label><mat-select formControlName="category" required><mat-option value="GENERAL">Notatka ogólna</mat-option><mat-option value="SESSION">Notatka ze spotkania</mat-option><mat-option value="HEALTH">Notatka zdrowotna</mat-option><mat-option value="OTHER">Inna notatka</mat-option></mat-select>@if (newNoteInvalid('category')) { <mat-error>Kategoria jest wymagana.</mat-error> }</mat-form-field><mat-form-field><mat-label>Treść</mat-label><textarea matInput formControlName="content" rows="7" required></textarea>@if (newNoteInvalid('content')) { <mat-error>Treść jest wymagana.</mat-error> }</mat-form-field><footer class="new-note-actions"><button mat-stroked-button type="button" (click)="cancelNewNote()">Anuluj</button><button mat-flat-button type="submit" [disabled]="busy() || newNoteForm.invalid">Zapisz notatkę</button></footer></form> }</section>
  @if (panelType && panelId) { <aside class="record-panel" role="dialog" aria-modal="false" tabindex="-1" aria-labelledby="record-panel-title" (keydown.escape)="closed.emit()"><header class="record-panel-header"><div><h2 id="record-panel-title">{{ panelType === 'interview' ? 'Wywiad' : 'Notatka' }}</h2></div><button type="button" class="goal-panel-close" aria-label="Zamknij panel" (click)="closed.emit()">×</button></header><div class="record-panel-body">@if (panelError()) { <p role="alert">{{ panelError() }}</p> }
    @if (panelType === 'interview') { @if (interview(); as item) { @if (panelMode === 'edit' && can(item, 'SAVE_DRAFT')) { <form [formGroup]="interviewForm"><nav class="section-tabs" aria-label="Sekcje wywiadu">@for (section of interviewSections(item.questions ?? []); track section.name; let index = $index) { <button mat-button type="button" [class.active]="selectedSection() === index" [attr.aria-current]="selectedSection() === index ? 'step' : null" (click)="selectSection(index)">{{ section.name }}</button> }</nav><div class="section-content">@if (currentSection(item.questions ?? []); as section) { <h3>{{ section.name }}</h3>@for (question of section.questions; track question.code) { <div class="interview-question">@if (isSelect(question)) { <mat-form-field><mat-label>{{ questionTitle(question) }}</mat-label><mat-select [formControlName]="question.code!" [multiple]="question.type === 'MULTI_SELECT'" [required]="!!question.required">@for (option of options(question); track option.value) { <mat-option [value]="option.value">{{ option.label }}</mat-option> }</mat-select></mat-form-field> } @else if (question.type === 'DATE') { <mat-form-field><mat-label>{{ questionTitle(question) }}</mat-label><input matInput [matDatepicker]="picker" [formControlName]="question.code!" [required]="!!question.required"><mat-datepicker-toggle matIconSuffix [for]="picker"></mat-datepicker-toggle><mat-datepicker #picker></mat-datepicker></mat-form-field> } @else { <mat-form-field><mat-label>{{ questionTitle(question) }}</mat-label><input matInput [type]="question.type === 'NUMBER' ? 'number' : 'text'" [formControlName]="question.code!" [required]="!!question.required"></mat-form-field> }@if (isInvalid(question)) { <p class="field-error">To pole jest wymagane.</p> }</div> } }</div><footer class="interview-actions"><button mat-stroked-button type="button" [disabled]="busy() || selectedSection() === 0" (click)="previousSection()">Wstecz</button><button mat-stroked-button type="button" [disabled]="busy() || selectedSection() === interviewSections(item.questions ?? []).length - 1" (click)="nextSection(item.questions ?? [])">Dalej</button><button mat-flat-button type="button" [disabled]="busy()" (click)="saveAndClose(item)">Zapisz i zamknij</button>@if (can(item, 'COMPLETE')) { <button mat-flat-button type="button" [disabled]="busy()" (click)="requestCompletion(item)">Zakończ wywiad</button> }</footer></form> } @else { <div class="section-content">@for (section of interviewSections(item.questions ?? []); track section.name) { @if (visibleAnswers(item, section.questions); as answers) { @if (answers.length) { <section><h3>{{ section.name }}</h3><dl class="record-facts">@for (question of answers; track question.code) { <dt>{{ questionTitle(question) }}</dt><dd>{{ answer(item, question) }}</dd> }</dl></section> } } }</div> } } @else { <p role="status">Wczytywanie wywiadu…</p> } }
    @else { @if (note(); as item) { @if (panelMode === 'edit' && can(item, 'UPDATE')) { <form [formGroup]="noteForm" (ngSubmit)="saveNote(item)"><label>Tytuł<input formControlName="title"></label><label>Kategoria<select formControlName="category"><option value="GENERAL">Notatka ogólna</option><option value="SESSION">Notatka ze spotkania</option><option value="HEALTH">Notatka zdrowotna</option><option value="OTHER">Inna notatka</option></select></label><label>Treść<textarea formControlName="content"></textarea></label><div class="record-actions"><button mat-flat-button type="submit" [disabled]="busy()">Zapisz</button>@if (can(item, 'FINALISE')) { <button mat-stroked-button type="button" [disabled]="busy()" (click)="finaliseNote(item)">Finalizuj</button> }@if (can(item, 'ARCHIVE')) { <button mat-stroked-button type="button" [disabled]="busy()" (click)="archiveNote(item)">Archiwizuj</button> }</div></form> } @else { <h3>{{ safeText(item.title, 'Bez tytułu') }}</h3><p>{{ noteCategory(item.category) }} · {{ noteStatus(item.status) }}</p><p class="record-content">{{ safeText(item.content, 'Brak treści') }}</p>@if (can(item, 'UPDATE')) { <button mat-stroked-button type="button" (click)="editNote(item)">Edytuj</button> } } } @else { <p role="status">Wczytywanie notatki…</p> } }</div></aside> }`,
})
export class ParticipantDocumentationComponent {
  private readonly api = inject(ApiFacade); private loadedContext = ''; private loadedPanel = '';
  @Input() participantId = ''; @Input() role?: 'TRAINER' | 'PHYSIOTHERAPIST'; @Input() panelType: RecordPanelType | null = null; @Input() panelId: string | null = null; @Input() panelMode: 'view' | 'edit' = 'view';
  @Output() opened = new EventEmitter<{ type: RecordPanelType; id: string; mode?: 'view' | 'edit' }>(); @Output() closed = new EventEmitter<void>(); @Output() changed = new EventEmitter<void>();
  protected readonly interviews = signal<InterviewView[]>([]); protected readonly notes = signal<NoteView[]>([]); protected readonly interview = signal<InterviewView | null>(null); protected readonly note = signal<NoteView | null>(null); protected readonly busy = signal(false); protected readonly panelError = signal(''); protected readonly announcement = signal(''); protected readonly selectedSection = signal(0);
  protected readonly latestInterview = computed(() => this.interviews()[0]); protected readonly latestNote = computed(() => this.notes()[0]); protected readonly ready = computed(() => !!this.participantId && !!this.role);
  protected interviewForm = new FormGroup<Record<string, FormControl<any>>>({}); protected noteForm = new FormGroup({ title: new FormControl('', { nonNullable: true, validators: [Validators.required] }), category: new FormControl('', { nonNullable: true, validators: [Validators.required] }), content: new FormControl('', { nonNullable: true, validators: [Validators.required] }) }); protected newNoteForm = new FormGroup({ title: new FormControl('', { nonNullable: true, validators: [Validators.required] }), category: new FormControl('GENERAL', { nonNullable: true, validators: [Validators.required] }), content: new FormControl('', { nonNullable: true, validators: [Validators.required] }) }); protected readonly creatingNote = signal(false);

  async ngOnChanges(): Promise<void> { if (!this.ready()) return; const context = `${this.participantId}:${this.role}`; if (context !== this.loadedContext) { this.loadedContext = context; await this.refresh(); } const panel = `${this.panelType}:${this.panelId}`; if (this.panelType && this.panelId && panel !== this.loadedPanel) await this.loadPanel(); }
  protected can(record: { availableActions?: string[] }, action: string) { return record.availableActions?.includes(action) ?? false; }
  protected interviewSummary() { const item = this.latestInterview(); return item ? item.status === 'COMPLETED' ? 'Uzupełniony' : 'Wymaga uzupełnienia' : 'Brak rozpoczętego wywiadu'; }
  protected notesSummary() { const all = this.notes(); const latest = all[0]; return `${all.length} ${all.length === 1 ? 'notatka' : 'notatek'}${latest?.updatedAt ? ` · ostatnia ${latest.updatedAt.toLocaleDateString('pl-PL')}` : ''}`; }
  protected interviewSections(questions: Question[]): InterviewSection[] { const grouped = new Map<string, Question[]>(); questions.forEach((question) => { const section = questionSection(question); grouped.set(section, [...(grouped.get(section) ?? []), question]); }); return [...grouped].sort(([a], [b]) => (SECTION_ORDER.indexOf(a) + 1 || 99) - (SECTION_ORDER.indexOf(b) + 1 || 99)).map(([name, groupedQuestions]) => ({ name, questions: groupedQuestions })); }
  protected currentSection(questions: Question[]) { const sections = this.interviewSections(questions); return sections[Math.min(this.selectedSection(), Math.max(sections.length - 1, 0))]; }
  protected selectSection(index: number) { this.selectedSection.set(index); this.panelError.set(''); }
  protected previousSection() { this.selectSection(Math.max(0, this.selectedSection() - 1)); }
  protected nextSection(questions: Question[]) { this.selectSection(Math.min(this.interviewSections(questions).length - 1, this.selectedSection() + 1)); }
  protected sectionCompletion(section: InterviewSection) { const required = section.questions.filter((question) => question.required); return { required: required.length, answered: required.filter((question) => this.hasValue(this.interviewForm.controls[question.code ?? '']?.value)).length }; }
  protected questionTitle = questionTitle;
  protected options = questionOptions;
  protected isSelect(question: Question) { return (question.type === 'SINGLE_SELECT' || question.type === 'MULTI_SELECT') && this.options(question).length > 0; }
  protected isInvalid(question: Question) { const control = this.interviewForm.controls[question.code ?? '']; return !!question.required && (control?.touched || this.panelError() === 'Uzupełnij wymagane pola przed zakończeniem wywiadu.') && !this.hasValue(control?.value); }
  protected visibleAnswers(item: InterviewView, questions: Question[]) { return questions.filter((question) => this.hasValue(this.answer(item, question))); }
  protected answer(item: InterviewView, question: Question) { const answer = item.answers?.find((entry) => entry.code === question.code); return answer?.textValue ?? answer?.numberValue?.toString() ?? answer?.dateValue?.toLocaleDateString('pl-PL') ?? answer?.selections?.map((value) => selectionLabel(question, value)).join(', '); }
  protected noteCategory = noteCategoryLabel;
  protected noteStatus = noteStatusLabel;
  protected safeText = safeSnapshotText;
  protected async open(type: RecordPanelType, id?: string, mode: 'view' | 'edit' = 'view') { if (id) this.opened.emit({ type, id, mode }); }
  protected async startInterview() { await this.mutate(async () => { const item = await this.api.participantDocumentation.startParticipantDocumentationInterview({ participantId: this.participantId, actingContext: this.role!, idempotencyKey: crypto.randomUUID() }); this.opened.emit({ type: 'interview', id: item.id!, mode: 'edit' }); }, 'Rozpoczęto wywiad.'); }
  protected openNewNote() { this.newNoteForm.reset({ title: '', category: 'GENERAL', content: '' }); this.creatingNote.set(true); }
  protected cancelNewNote() { this.creatingNote.set(false); }
  protected newNoteInvalid(name: 'title' | 'category' | 'content') { const control = this.newNoteForm.controls[name]; return control.invalid && control.touched; }
  protected async createNote() { const noteRequest = this.newNoteForm.getRawValue(); if (this.newNoteForm.invalid || !noteRequest.title.trim() || !noteRequest.content.trim()) { this.newNoteForm.markAllAsTouched(); return; } await this.mutate(async () => { const item = await this.api.participantDocumentation.createParticipantDocumentationNote({ participantId: this.participantId, actingContext: this.role!, idempotencyKey: crypto.randomUUID(), noteRequest }); this.creatingNote.set(false); this.opened.emit({ type: 'note', id: item.id!, mode: 'edit' }); }, 'Utworzono notatkę.'); }
  protected editNote(item: NoteView) { this.opened.emit({ type: 'note', id: item.id!, mode: 'edit' }); }
  protected async saveInterview(item: InterviewView) { await this.mutate(() => this.api.participantDocumentation.saveParticipantDocumentationInterviewDraft({ participantId: this.participantId, interviewId: item.id!, actingContext: this.role!, saveInterviewRequest: { expectedVersion: item.version ?? 0, answers: (item.questions ?? []).map((question) => this.answerRequest(question)) } }), 'Zapisano wersję roboczą wywiadu.'); }
  protected async saveAndClose(item: InterviewView) { await this.saveInterview(item); if (!this.panelError()) this.closed.emit(); }
  protected requestCompletion(item: InterviewView) { const firstIncomplete = this.interviewSections(item.questions ?? []).findIndex((section) => this.sectionCompletion(section).answered !== this.sectionCompletion(section).required); if (firstIncomplete >= 0) { this.selectedSection.set(firstIncomplete); Object.values(this.interviewForm.controls).forEach((control) => control.markAsTouched()); this.panelError.set('Uzupełnij wymagane pola przed zakończeniem wywiadu.'); return; } void this.completeInterview(item); }
  protected async completeInterview(item: InterviewView) { await this.mutate(() => this.api.participantDocumentation.completeParticipantDocumentationInterview({ participantId: this.participantId, interviewId: item.id!, actingContext: this.role!, idempotencyKey: crypto.randomUUID(), participantDocumentationVersionRequest: { expectedVersion: item.version ?? 0 } }), 'Zakończono wywiad.'); }
  protected async saveNote(item: NoteView) { if (this.noteForm.invalid) return; await this.mutate(() => this.api.participantDocumentation.updateParticipantDocumentationNote({ participantId: this.participantId, noteId: item.id!, actingContext: this.role!, updateNoteRequest: { ...this.noteForm.getRawValue(), expectedVersion: item.version ?? 0 } }), 'Zapisano notatkę.'); }
  protected async finaliseNote(item: NoteView) { await this.mutate(() => this.api.participantDocumentation.finaliseParticipantDocumentationNote({ participantId: this.participantId, noteId: item.id!, actingContext: this.role!, idempotencyKey: crypto.randomUUID(), participantDocumentationVersionRequest: { expectedVersion: item.version ?? 0 } }), 'Sfinalizowano notatkę.'); }
  protected async archiveNote(item: NoteView) { await this.mutate(() => this.api.participantDocumentation.archiveParticipantDocumentationNote({ participantId: this.participantId, noteId: item.id!, actingContext: this.role!, idempotencyKey: crypto.randomUUID(), participantDocumentationVersionRequest: { expectedVersion: item.version ?? 0 } }), 'Zarchiwizowano notatkę.'); }
  private answerRequest(question: Question) { const value = this.interviewForm.controls[question.code ?? '']?.value; return question.type === 'NUMBER' ? { code: question.code!, numberValue: value === '' || value == null ? undefined : Number(value) } : question.type === 'DATE' ? { code: question.code!, dateValue: value || undefined } : this.isSelect(question) && question.type === 'SINGLE_SELECT' ? { code: question.code!, selections: value ? [value] : undefined } : this.isSelect(question) && question.type === 'MULTI_SELECT' ? { code: question.code!, selections: value?.length ? value : undefined } : { code: question.code!, textValue: value || undefined }; }
  private hasValue(value: unknown) { return Array.isArray(value) ? value.length > 0 : value !== undefined && value !== null && value !== ''; }
  private async refresh() { const [interviews, notes] = await Promise.all([this.api.participantDocumentation.listParticipantDocumentationInterviews({ participantId: this.participantId, actingContext: this.role! }), this.api.participantDocumentation.listParticipantDocumentationNotes({ participantId: this.participantId, actingContext: this.role! })]); this.interviews.set([...interviews].sort((a, b) => (b.updatedAt?.getTime() ?? 0) - (a.updatedAt?.getTime() ?? 0))); this.notes.set([...notes].sort((a, b) => (b.updatedAt?.getTime() ?? 0) - (a.updatedAt?.getTime() ?? 0))); }
  private async loadPanel() { this.panelError.set(''); try { if (this.panelType === 'interview') { const item = await this.api.participantDocumentation.getParticipantDocumentationInterview({ participantId: this.participantId, interviewId: this.panelId!, actingContext: this.role! }); this.interview.set(item); this.selectedSection.set(0); this.interviewForm = new FormGroup(Object.fromEntries((item.questions ?? []).map((question) => [question.code!, new FormControl(question.type === 'MULTI_SELECT' ? (item.answers?.find((answer) => answer.code === question.code)?.selections ?? []) : question.type === 'SINGLE_SELECT' ? (item.answers?.find((answer) => answer.code === question.code)?.selections?.[0] ?? '') : question.type === 'DATE' ? item.answers?.find((answer) => answer.code === question.code)?.dateValue ?? null : this.answer(item, question) ?? '', { nonNullable: question.type !== 'DATE' })])) as Record<string, FormControl<any>>); } else { const item = await this.api.participantDocumentation.getParticipantDocumentationNote({ participantId: this.participantId, noteId: this.panelId!, actingContext: this.role! }); this.note.set(item); this.noteForm.setValue({ title: item.title ?? '', category: item.category ?? '', content: item.content ?? '' }); } this.loadedPanel = `${this.panelType}:${this.panelId}`; } catch (error) { this.panelError.set(this.errorMessage(error)); } }
  private async mutate(call: () => Promise<unknown>, success: string) { this.busy.set(true); this.panelError.set(''); try { await call(); await this.refresh(); this.loadedPanel = ''; if (this.panelType && this.panelId) await this.loadPanel(); this.announcement.set(success); this.changed.emit(); } catch (error) { if (error instanceof ResponseError && error.response.status === 409) { await this.refresh(); this.loadedPanel = ''; if (this.panelType && this.panelId) await this.loadPanel(); this.changed.emit(); } this.panelError.set(this.errorMessage(error)); } finally { this.busy.set(false); } }
  private errorMessage(error: unknown) { const status = error instanceof ResponseError ? error.response.status : 0; if (status === 409) return 'Dane zmieniły się. Odświeżono bieżący widok.'; if (status === 404) return 'Ten wpis nie jest już dostępny.'; if (status === 403) return 'Nie masz dostępu do tego wpisu.'; return 'Nie udało się zapisać zmian. Spróbuj ponownie.'; }
}
