import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { Router } from '@angular/router';
import { OnboardingStateService } from '../core/onboarding-state.service';
import { ParticipantClaimBootstrapService } from '../core/participant-claim-bootstrap.service';
import { ApiFacade } from '../core/api.facade';
import { AuthService } from '../core/auth.service';
import { ResponseError } from '../api/generated/src/runtime';

const errors: Record<string, string> = { expired: 'To zaproszenie wygasło.', revoked: 'To zaproszenie zostało wycofane.', contextinvalid: 'Link nie jest już ważny.', verificationrequired: 'Potwierdź adres e-mail, a następnie zaloguj się ponownie.', emailmismatch: 'Zalogowane konto ma inny adres e-mail.', alreadyclaimedother: 'Zaproszenie zostało już wykorzystane.', linkconflict: 'Nie można połączyć tego konta z kartoteką.' };
@Component({ standalone: true, imports: [MatButtonModule], changeDetection: ChangeDetectionStrategy.OnPush, template: `<main class="panel"><h1>Dostęp do Twoich danych</h1>@if (!auth.authenticated()) {<p>Po zalogowaniu potwierdzisz dostęp do swojej kartoteki.</p><button mat-flat-button (click)="login()">Zaloguj się</button><button mat-stroked-button (click)="register()">Utwórz konto</button>} @else if (needsOnboarding()) {<p>Dokończ najpierw konfigurację konta uczestnika.</p><button mat-flat-button (click)="onboarding()">Dokończ konfigurację</button>} @else if (wrongProfile()) {<p role="alert">To konto ma profil specjalisty i nie może zostać połączone z kartoteką uczestnika.</p>} @else {<p>Potwierdź połączenie z kartoteką.</p><button mat-flat-button [disabled]="busy()" (click)="claim()">Potwierdź dostęp</button>} @if(message()){<p role="alert">{{message()}}</p>}</main>` })
export class ParticipantClaimPage { protected readonly auth=inject(AuthService); private readonly api=inject(ApiFacade).participantAccess; private readonly router=inject(Router); private readonly onboardingState=inject(OnboardingStateService); private readonly bootstrap=inject(ParticipantClaimBootstrapService); protected readonly busy=signal(false); protected readonly message=signal(''); protected readonly needsOnboarding=signal(false); protected readonly wrongProfile=signal(false); constructor(){this.message.set(errors[this.bootstrap.failure()] ?? '');if(this.auth.authenticated())void this.checkOnboarding();} protected login=()=>void this.auth.login(`${window.location.origin}/participant/claim`); protected register=()=>void this.auth.register(`${window.location.origin}/participant/claim`); protected onboarding=()=>void this.router.navigateByUrl('/onboarding'); private async checkOnboarding(){try{const state=await this.onboardingState.get();this.needsOnboarding.set(state.stage!=='READY');this.wrongProfile.set(state.profileType==='SPECIALIST');}catch{}} protected async claim(){this.busy.set(true);this.message.set('');try { await this.api.claimParticipantAccess({}, { credentials:'include' }); await this.router.navigateByUrl('/sessions'); } catch (e) { const code=e instanceof ResponseError ? (await e.response.clone().json().catch(()=>({}))).code : ''; this.message.set(errors[String(code).toLowerCase().replace(/_/g, '')] ?? 'Nie udało się potwierdzić dostępu. Spróbuj ponownie.'); } finally {this.busy.set(false);} } }
