import { ChangeDetectionStrategy, Component, ElementRef, EventEmitter, Input, Output, afterNextRender, computed, inject, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { DatePipe } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiFacade } from '../core/api.facade';
import type { SpecialistParticipantWorkspaceView } from '../api/generated/src/models/SpecialistParticipantWorkspaceView';
import type { ParticipantTimelineEvent } from '../api/generated/src/models/ParticipantTimelineEvent';
import { groupEvents, overviewPosition, rangeDates, sortedEvents, timelineCategories, type TimelineCategory, type WorkspaceRange, type WorkspaceView } from './specialist-participant-workspace.geometry';

const actionLabels: Record<string, string> = { SCHEDULE_APPOINTMENT: 'Zaplanuj spotkanie' };
const categoryLabels: Record<string, string> = { GOALS: 'Cele', PLANS: 'Plany i zalecenia', SESSIONS: 'Sesje', EXECUTION: 'Wykonanie', PROGRESS: 'Postępy', PROBLEMS: 'Problemy', NOTES: 'Notatki', DOCUMENTS: 'Dokumenty' };
const stateLabels: Record<string, string> = { SCHEDULED: 'Zaplanowana', STARTED: 'Rozpoczęta', COMPLETED: 'Ukończona', SKIPPED: 'Pominięta', CANCELLED: 'Odwołana', NO_SHOW: 'Nieobecność', OPEN: 'Otwarte', RESOLVED: 'Rozwiązane' };
const safe = (value?: string) => value && !/^[0-9a-f]{8}-[0-9a-f]{4}-/i.test(value) ? value : undefined;
const label = (value: string | undefined, labels: Record<string, string>) => value ? labels[value] ?? value.replace(/_/g, ' ').toLocaleLowerCase('pl-PL') : 'Brak danych';

@Component({ selector: 'app-participant-workspace-header', standalone: true, imports: [MatButtonModule, DatePipe], changeDetection: ChangeDetectionStrategy.OnPush, template: `<header class="workspace-header"><div><h1 id="workspace-title">{{ workspace.participant?.displayName || 'Klient' }}</h1><p>{{ workspace.participant?.contextLabel }}@if (workspace.relationship?.status) { · {{ relationshipLabel }} }@if (workspace.nextAppointment?.startsAt) { · następne spotkanie: {{ workspace.nextAppointment?.startsAt | date:'d MMM, HH:mm' }} }</p></div>@if (actions.length) { <div class="quick-actions" aria-label="Szybkie działania">@for (action of actions; track action) { <button mat-stroked-button type="button" (click)="requested.emit(action)">{{ actionLabel(action) }}</button> }</div> }</header>` })
export class ParticipantWorkspaceHeaderComponent { @Input({required: true}) workspace!: SpecialistParticipantWorkspaceView; @Input() actions: string[] = []; @Output() requested = new EventEmitter<string>(); protected actionLabel = (a: string) => actionLabels[a] ?? a; protected get relationshipLabel() { return label(this.workspace.relationship?.status, { ACTIVE: 'aktywna współpraca', INACTIVE: 'nieaktywna współpraca' }); } }

@Component({ selector: 'app-participant-summary-strip', standalone: true, changeDetection: ChangeDetectionStrategy.OnPush, template: `<nav class="summary-strip" aria-label="Podsumowanie klienta"><button type="button" (click)="context.emit('PLANS')"><strong>Aktywny plan</strong><span>{{ workspace.activePlan?.name || 'Brak aktywnego planu' }}</span></button><button type="button" (click)="context.emit('GOALS')"><strong>Cele</strong><span>{{ workspace.goals?.length || 0 }} aktywne</span></button><button type="button" (click)="context.emit('EXECUTION')"><strong>Realizacja</strong><span>{{ workspace.adherenceSummary?.completedSessions ?? '—' }} wykonanych sesji</span></button><button type="button" (click)="context.emit('PROGRESS')"><strong>Ostatnia aktywność</strong><span>{{ workspace.recentProgress?.latestActivityAt ? 'Zarejestrowana' : 'Brak danych' }}</span></button><button type="button" (click)="context.emit('PROBLEMS')"><strong>Wymaga reakcji</strong><span>{{ workspace.activeProblems?.length || 0 }} problemów</span></button></nav>` })
export class ParticipantSummaryStripComponent { @Input({required: true}) workspace!: SpecialistParticipantWorkspaceView; @Output() context = new EventEmitter<TimelineCategory>(); }

@Component({ selector: 'app-patient-timeline-filters', standalone: true, changeDetection: ChangeDetectionStrategy.OnPush, template: `<div class="timeline-controls"><div class="ranges" aria-label="Zakres czasu">@for (item of ranges; track item.key) { <button type="button" [class.active]="range === item.key" (click)="rangeChange.emit(item.key)">{{ item.label }}</button> }</div><button type="button" (click)="all.emit()">Wszystkie</button>@for (type of categories; track type) { <label><input type="checkbox" [checked]="selected.includes(type)" (change)="toggle(type)"> {{ categoryLabel(type) }}</label> } @if (selected.length) { <button type="button" (click)="clear.emit()">Wyczyść filtry ({{ selected.length }})</button> } <button type="button" (click)="viewChange.emit(view === 'timeline' ? 'list' : 'timeline')">{{ view === 'timeline' ? 'Widok listy' : 'Widok osi czasu' }}</button></div>` })
export class PatientTimelineFiltersComponent { @Input() range: WorkspaceRange = '2w'; @Input() selected: TimelineCategory[] = []; @Input() view: WorkspaceView = 'timeline'; @Output() rangeChange = new EventEmitter<WorkspaceRange>(); @Output() selectedChange = new EventEmitter<TimelineCategory[]>(); @Output() clear = new EventEmitter<void>(); @Output() all = new EventEmitter<void>(); @Output() viewChange = new EventEmitter<WorkspaceView>(); protected readonly categories = timelineCategories; protected readonly ranges = [{key: '2w' as const,label:'2 tyg.'},{key:'3m' as const,label:'3 mies.'},{key:'12m' as const,label:'12 mies.'},{key:'all' as const,label:'Całość'}]; protected categoryLabel = (type: string) => categoryLabels[type]; protected toggle(type: TimelineCategory) { this.selectedChange.emit(this.selected.includes(type) ? this.selected.filter(item => item !== type) : [...this.selected, type]); } }

@Component({ selector: 'app-patient-timeline-overview', standalone: true, changeDetection: ChangeDetectionStrategy.OnPush, template: `<section class="overview" aria-labelledby="overview-title"><h2 id="overview-title">Przegląd okresu</h2><p id="overview-description" class="sr-only">Znaczniki celów, planów, sesji i problemów w wybranym zakresie. Szczegóły są dostępne także na liście poniżej.</p><svg viewBox="0 0 1000 120" role="img" aria-describedby="overview-description"><g aria-hidden="true">@for (track of tracks; track track; let i = $index) { <line x1="0" [attr.y1]="20 + i * 25" x2="1000" [attr.y2]="20 + i * 25" /> }</g>@for (event of events; track event.eventId) { <circle [attr.cx]="position(event) * 10" cy="45" r="7" tabindex="0" role="button" [attr.aria-label]="event.title || 'Zdarzenie'" (click)="opened.emit(event)" (keydown.enter)="opened.emit(event)" (keydown.space)="opened.emit(event)"></circle> }</svg></section>` })
export class PatientTimelineOverviewComponent { @Input() events: ParticipantTimelineEvent[] = []; @Input() from?: Date; @Input() to?: Date; @Output() opened = new EventEmitter<ParticipantTimelineEvent>(); protected readonly tracks = ['Cele','Plany','Sesje','Problemy']; protected position = (event: ParticipantTimelineEvent) => overviewPosition(event.effectiveFrom ?? event.recordedAt, this.from, this.to); }

@Component({ selector: 'app-timeline-event', standalone: true, imports: [DatePipe], changeDetection: ChangeDetectionStrategy.OnPush, template: `<article class="timeline-event"><button type="button" [attr.data-event-id]="event.eventId" (click)="opened.emit(event)"><span class="event-category">{{ category(event.category) }}</span><time>{{ event.effectiveFrom || event.recordedAt | date:'d MMM, HH:mm' }}</time><strong>{{ event.title || 'Zdarzenie' }}</strong><span>{{ event.summary || 'Brak krótkiego podsumowania' }}</span><span>Status: {{ status(event.status) }}</span>@if (event.source) { <small>Źródło: {{ event.source }}</small> }</button></article>` })
export class TimelineEventComponent { @Input({required:true}) event!: ParticipantTimelineEvent; @Output() opened = new EventEmitter<ParticipantTimelineEvent>(); protected category = (value?: string) => label(value, categoryLabels); protected status = (value?: string) => label(value, stateLabels); }

@Component({ selector: 'app-timeline-period-group', standalone: true, imports: [TimelineEventComponent], changeDetection: ChangeDetectionStrategy.OnPush, template: `<section class="period-group"><h2>{{ group.label }}</h2><ol>@for (event of group.items; track event.eventId) { <li><app-timeline-event [event]="event" (opened)="opened.emit($event)" /></li> }</ol></section>` })
export class TimelinePeriodGroupComponent { @Input({required:true}) group!: {label:string;items:ParticipantTimelineEvent[]}; @Output() opened = new EventEmitter<ParticipantTimelineEvent>(); }

@Component({ selector: 'app-patient-timeline', standalone: true, imports: [TimelinePeriodGroupComponent], changeDetection: ChangeDetectionStrategy.OnPush, template: `<section aria-label="Chronologiczna oś czasu">@for (group of groups; track group.label) { <app-timeline-period-group [group]="group" (opened)="opened.emit($event)" /> } @if (!groups.length) { <p>Brak zdarzeń w wybranym zakresie.</p> }</section>` })
export class PatientTimelineComponent { @Input() groups: Array<{label:string;items:ParticipantTimelineEvent[]}> = []; @Output() opened = new EventEmitter<ParticipantTimelineEvent>(); }

@Component({ selector: 'app-patient-timeline-list-view', standalone: true, imports: [TimelineEventComponent], changeDetection: ChangeDetectionStrategy.OnPush, template: `<section aria-label="Widok listy"><ol class="timeline-list">@for (event of events; track event.eventId) { <li><app-timeline-event [event]="event" (opened)="opened.emit($event)" /></li> }</ol></section>` })
export class PatientTimelineListViewComponent { @Input() events: ParticipantTimelineEvent[] = []; @Output() opened = new EventEmitter<ParticipantTimelineEvent>(); }

@Component({ selector: 'app-patient-timeline-event-panel', standalone: true, imports: [DatePipe], changeDetection: ChangeDetectionStrategy.OnPush, template: `<aside class="event-panel" role="dialog" aria-modal="false" aria-labelledby="event-panel-title" (keydown.escape)="closed.emit()"><button type="button" aria-label="Zamknij szczegóły zdarzenia" (click)="closed.emit()">×</button><h2 id="event-panel-title">{{ event.title || 'Szczegóły zdarzenia' }}</h2><p>{{ event.summary || 'Brak dodatkowego opisu.' }}</p><dl><dt>Czas zdarzenia</dt><dd>{{ event.effectiveFrom | date:'medium' }}</dd><dt>Zarejestrowano</dt><dd>{{ event.recordedAt | date:'medium' }}</dd>@if (event.actor) { <dt>Autor</dt><dd>{{ event.actor }}</dd> }@if (event.source) { <dt>Źródło</dt><dd>{{ event.source }}</dd> }</dl></aside>` })
export class PatientTimelineEventPanelComponent { @Input({required:true}) event!: ParticipantTimelineEvent; @Output() closed = new EventEmitter<void>(); }

@Component({ selector: 'app-schedule-appointment-dialog', standalone: true, imports: [ReactiveFormsModule, MatButtonModule], changeDetection: ChangeDetectionStrategy.OnPush, template: `<section class="appointment-dialog" role="dialog" aria-modal="true" aria-labelledby="appointment-dialog-title"><form [formGroup]="form" (ngSubmit)="submitted.emit(form.getRawValue())"><button class="dialog-close" type="button" aria-label="Zamknij planowanie spotkania" (click)="closed.emit()">×</button><h2 id="appointment-dialog-title">Zaplanuj spotkanie</h2><label>Termin rozpoczęcia<input type="datetime-local" formControlName="startsAt" required></label><label>Termin zakończenia<input type="datetime-local" formControlName="endsAt" required></label><label>Rodzaj spotkania<select formControlName="type"><option value="TRAINING">Trening</option><option value="PHYSIOTHERAPY">Fizjoterapia</option><option value="ASSESSMENT">Ocena</option><option value="CONSULTATION">Konsultacja</option></select></label><label>Forma<select formControlName="locationMode"><option value="IN_PERSON">Na miejscu</option><option value="REMOTE">Zdalnie</option><option value="PHONE">Telefonicznie</option></select></label><label>Miejsce lub link (opcjonalnie)<input formControlName="location" maxlength="200"></label><label>Krótki cel spotkania (opcjonalnie)<input formControlName="shortPurpose" maxlength="300"></label>@if (error) { <p role="alert">Nie udało się zaplanować spotkania. Sprawdź dane i spróbuj ponownie.</p> }<div><button mat-stroked-button type="button" (click)="closed.emit()">Anuluj</button><button mat-flat-button type="submit" [disabled]="form.invalid || saving">{{ saving ? 'Zapisywanie…' : 'Zaplanuj' }}</button></div></form></section>` })
export class ScheduleAppointmentDialogComponent {
  @Input() saving = false; @Input() error = false; @Output() closed = new EventEmitter<void>(); @Output() submitted = new EventEmitter<{startsAt:string;endsAt:string;type:string;locationMode:string;location:string;shortPurpose:string}>();
  protected readonly form = new FormGroup({ startsAt: new FormControl('', {nonNullable:true, validators:[Validators.required]}), endsAt: new FormControl('', {nonNullable:true, validators:[Validators.required]}), type: new FormControl('TRAINING', {nonNullable:true}), locationMode: new FormControl('IN_PERSON', {nonNullable:true}), location: new FormControl('', {nonNullable:true}), shortPurpose: new FormControl('', {nonNullable:true}) });
}

@Component({ selector: 'app-specialist-participant-workspace-page', standalone: true, imports: [ParticipantWorkspaceHeaderComponent, ParticipantSummaryStripComponent, PatientTimelineFiltersComponent, PatientTimelineOverviewComponent, PatientTimelineComponent, PatientTimelineListViewComponent, PatientTimelineEventPanelComponent, ScheduleAppointmentDialogComponent], styleUrl: './specialist-participant-workspace.page.scss', changeDetection: ChangeDetectionStrategy.OnPush, template: `<main class="workspace" [attr.aria-busy]="state() === 'loading'"><p class="sr-only" aria-live="polite">{{ announcement() }}</p>@if (state() === 'loading') { <p role="status">Wczytywanie kartoteki…</p> } @else if (state() === 'error') { <section role="alert"><h1>Nie udało się wczytać kartoteki</h1><button type="button" (click)="reload()">Spróbuj ponownie</button></section> } @else if (workspace(); as data) { <app-participant-workspace-header [workspace]="data" [actions]="safeActions()" (requested)="perform($event)" /><app-participant-summary-strip [workspace]="data" (context)="filterContext($event)" /><app-patient-timeline-filters [range]="range()" [selected]="types()" [view]="view()" (rangeChange)="setRange($event)" (selectedChange)="setTypes($event)" (clear)="setTypes([])" (all)="setTypes([])" (viewChange)="setView($event)" /><app-patient-timeline-overview [events]="events()" [from]="timelineFrom()" [to]="timelineTo()" (opened)="open($event)" /><div class="timeline-layout"><div>@if (view() === 'timeline') { <app-patient-timeline [groups]="groups()" (opened)="open($event)" /> } @else { <app-patient-timeline-list-view [events]="events()" (opened)="open($event)" /> } @if (nextCursor()) { <button class="older" type="button" (click)="older()">Pokaż wcześniejsze</button> }</div>@if (selected(); as event) { <app-patient-timeline-event-panel [event]="event" (closed)="close()" /> }</div>@if (scheduling()) { <app-schedule-appointment-dialog [saving]="savingAppointment()" [error]="appointmentError()" (closed)="closeSchedule()" (submitted)="schedule($event)" /> } }</main>` })
export class SpecialistParticipantWorkspacePage {
  private readonly api = inject(ApiFacade); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private readonly host = inject(ElementRef<HTMLElement>); private request = 0; private opener: HTMLElement | null = null;
  protected readonly state = signal<'loading'|'loaded'|'error'>('loading'); protected readonly workspace = signal<SpecialistParticipantWorkspaceView | null>(null); protected readonly events = signal<ParticipantTimelineEvent[]>([]); protected readonly nextCursor = signal<string | undefined>(undefined); protected readonly range = signal<WorkspaceRange>('2w'); protected readonly types = signal<TimelineCategory[]>([]); protected readonly view = signal<WorkspaceView>('timeline'); protected readonly selected = signal<ParticipantTimelineEvent | null>(null); protected readonly announcement = signal('');
  protected readonly timelineFrom = signal<Date | undefined>(undefined); protected readonly timelineTo = signal<Date | undefined>(undefined); protected readonly scheduling = signal(false); protected readonly savingAppointment = signal(false); protected readonly appointmentError = signal(false); protected readonly groups = computed(() => groupEvents(this.events(), rangeDates(this.range()).granularity)); protected readonly safeActions = computed(() => (this.workspace()?.quickActions ?? []).filter(action => !!actionLabels[action]));
  constructor() { this.route.queryParamMap.subscribe(params => { const range = params.get('range'); const view = params.get('view'); this.range.set(range === '3m' || range === '12m' || range === 'all' ? range : '2w'); this.view.set(view === 'list' ? 'list' : 'timeline'); this.types.set((params.get('types') ?? '').split(',').filter((type): type is TimelineCategory => (timelineCategories as readonly string[]).includes(type))); const id = params.get('eventId'); const participantId = this.route.snapshot.paramMap.get('participantId'); if (participantId) void this.load(participantId, id); }); }
  protected async reload(): Promise<void> { const id = this.route.snapshot.paramMap.get('participantId'); if (id) await this.load(id, this.route.snapshot.queryParamMap.get('eventId')); }
  private async load(participantId: string, selectedId: string | null): Promise<void> { const request = ++this.request; this.state.set('loading'); const dates = rangeDates(this.range()); try { const [workspace, timeline] = await Promise.all([this.api.participantWorkspace.workspace({participantId}), this.api.participantWorkspace.timeline({participantId, from: dates.from, to: dates.to, types: this.types().join(',') || undefined, granularity: dates.granularity, limit: 100})]); if (request !== this.request) return; this.workspace.set(workspace); this.events.set(sortedEvents(timeline.items ?? [])); this.nextCursor.set(timeline.nextCursor); this.timelineFrom.set(timeline.from ?? dates.from); this.timelineTo.set(timeline.to ?? dates.to); this.selected.set((timeline.items ?? []).find(event => event.eventId === selectedId) ?? null); this.state.set('loaded'); } catch { if (request === this.request) this.state.set('error'); } }
  protected setRange(range: WorkspaceRange) { void this.navigate({range, eventId: null}); } protected setTypes(types: TimelineCategory[]) { void this.navigate({types: types.length ? types.join(',') : null, eventId: null}); } protected setView(view: WorkspaceView) { void this.navigate({view}); } protected filterContext(type: TimelineCategory) { this.setTypes([type]); }
  protected open(event: ParticipantTimelineEvent) { this.opener = document.activeElement as HTMLElement | null; void this.navigate({eventId: event.eventId ?? null}); } protected close() { void this.navigate({eventId: null}); afterNextRender(() => this.opener?.focus()); }
  protected async older(): Promise<void> { const participantId = this.route.snapshot.paramMap.get('participantId'); const cursor = this.nextCursor(); if (!participantId || !cursor) return; const request = ++this.request; try { const timeline = await this.api.participantWorkspace.timeline({participantId, ...rangeDates(this.range()), types: this.types().join(',') || undefined, cursor, limit: 100}); if (request !== this.request) return; const ids = new Set(this.events().map(event => event.eventId)); this.events.update(events => sortedEvents([...events, ...(timeline.items ?? []).filter(event => !ids.has(event.eventId))])); this.nextCursor.set(timeline.nextCursor); } catch { this.announcement.set('Nie udało się pobrać wcześniejszych zdarzeń.'); } }
  protected perform(action: string) { if (action === 'SCHEDULE_APPOINTMENT') { this.appointmentError.set(false); this.scheduling.set(true); } }
  protected closeSchedule() { if (!this.savingAppointment()) this.scheduling.set(false); }
  protected async schedule(value: {startsAt:string;endsAt:string;type:string;locationMode:string;location:string;shortPurpose:string}): Promise<void> { const participantId = this.route.snapshot.paramMap.get('participantId'); const startsAt = new Date(value.startsAt); const endsAt = new Date(value.endsAt); if (!participantId || Number.isNaN(startsAt.getTime()) || Number.isNaN(endsAt.getTime()) || endsAt <= startsAt) { this.appointmentError.set(true); return; } this.savingAppointment.set(true); this.appointmentError.set(false); try { await this.api.appointments.create({ idempotencyKey: crypto.randomUUID(), createCommand: { participantId, startsAt, endsAt, type: value.type as 'TRAINING' | 'PHYSIOTHERAPY' | 'ASSESSMENT' | 'CONSULTATION', locationMode: value.locationMode as 'IN_PERSON' | 'REMOTE' | 'PHONE', location: value.location || undefined, shortPurpose: value.shortPurpose || undefined } }); this.scheduling.set(false); this.announcement.set('Spotkanie zaplanowano. Kartoteka została odświeżona.'); await this.reload(); } catch { this.appointmentError.set(true); } finally { this.savingAppointment.set(false); } }
  private navigate(queryParams: Record<string, string | null>) { return this.router.navigate([], {relativeTo: this.route, queryParams, queryParamsHandling: 'merge'}); }
}
