import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { ApiFacade } from '../core/api.facade';
import { ParticipantGoalsComponent } from './specialist-participant-workspace.page';
import { ResponseError } from '../api/generated/src/runtime';
import { ExerciseSetVersionPreviewComponent } from './exercise-sets/exercise-set-version-preview.component';

/** Participant-scoped task UI. The façade materializes hierarchy and snapshots; this page only selects sources. */
@Component({
  selector: 'app-specialist-plan-page', standalone: true,
  imports: [ReactiveFormsModule, MatButtonModule, RouterLink, DatePipe, ParticipantGoalsComponent, ExerciseSetVersionPreviewComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styleUrl: './specialist-plan.page.scss',
  template: `<main class="plan panel"><a [routerLink]="workspaceLink()">{{ own() ? '← Moje plany' : '← Kartoteka uczestnika' }}</a>
  @if (loading()) { <p role="status">Wczytywanie planu…</p> } @else if (error()) { <section class="error" role="alert"><h1>Nie udało się otworzyć planu</h1><p>{{ error() }}</p><button mat-stroked-button (click)="load()">Spróbuj ponownie</button></section> } @else if (plansIndex()) {
    <h1>{{ own() ? 'Plany własne' : 'Plany treningowe' }}</h1><p class="muted">Wybierz plan, aby wrócić do zapisanej rewizji.</p><a mat-flat-button [routerLink]="newPlanLink()">Utwórz plan</a>@if(!plans().length){<p>{{ own() ? 'Nie masz jeszcze planów.' : 'Brak planów dla tego uczestnika.' }}</p>}@for(plan of plans();track plan.planId){<article class="card"><h2>{{plan.name || 'Plan treningowy'}}</h2><p>{{plan.status}} @if(plan.purpose){ · {{plan.purpose}} }</p>@if(plan.planId && plan.currentRevisionId){<a mat-stroked-button [routerLink]="revisionLink(plan.planId, plan.currentRevisionId)">Otwórz rewizję</a>}</article>}
  } @else if (newPlan()) {
    <h1>Nowy plan treningowy</h1><p class="muted">{{ own() ? 'Wybierz własny aktywny cel. Snapshot celu tworzy serwer.' : 'Wybierz cel uczestnika. Snapshot celu tworzy serwer.' }}</p>
    <form [formGroup]="createForm" (ngSubmit)="create()" class="card"><div class="grid"><label>Nazwa planu<input formControlName="name" required maxlength="160" /></label><label>Cel<select formControlName="goalId" required><option value="">Wybierz cel</option>@for (goal of planningGoals(); track goal.id){<option [value]="goal.id">{{goal.title}} · {{goal.status}}</option>}</select></label><label>Od<input type="date" formControlName="validFrom" required /></label><label>Do<input type="date" formControlName="validTo" required /></label></div><p class="muted">Dostępne są aktywne cele. Ostateczną zgodność celu, uczestnika i kompetencji sprawdza serwer.</p><label>Cel praktyczny / etap<input formControlName="phaseIntent" maxlength="160" /></label>@if(mutationError()){<p class="error">{{mutationError()}}</p>}<button mat-flat-button [disabled]="createForm.invalid || saving()">Utwórz plan</button></form>
    @if(own() && !planningGoals().length){<p class="muted">Nie ma właściwego celu? Poproś swojego specjalistę o jego ustalenie.</p>} @if(!own()){<details><summary>Nie ma właściwego celu? Utwórz go w istniejącym przepływie</summary><app-participant-goals [participantId]="participantId()" [role]="role()" (changed)="loadGoals()" /></details>}
  } @else if (editor(); as value) { <header><h1>{{value.name || 'Plan treningowy'}}</h1><p>Status rewizji: <strong>{{revision()?.status || 'Brak danych'}}</strong></p></header>
    <section class="card"><h2>Cel i okres</h2>@for(goal of revision()?.goals || [];track goal.sourceParticipantGoalId){<p><strong>{{goal.title}}</strong> · {{goal.category}} · {{goal.targetDate ? (goal.targetDate | date:'longDate':'':'pl') : 'bez terminu'}}</p>} @if (editable()) {<form [formGroup]="periodForm" (ngSubmit)="savePeriod()" class="grid"><label>Od<input type="date" formControlName="validFrom" required /></label><label>Do<input type="date" formControlName="validTo" required /></label><button mat-stroked-button [disabled]="periodForm.invalid || saving()">Zapisz okres</button></form>} @else {<p>{{revision()?.validFrom | date:'longDate':'':'pl'}} — {{revision()?.validTo | date:'longDate':'':'pl'}}</p>}</section>
    <section class="card"><h2>Sesje</h2>@if (!sessions().length){<p>Brak zaplanowanych sesji.</p>} @for(session of sessions();track session.id){<article class="card"><h3>{{session.title || 'Sesja'}}</h3><p>{{session.scheduledDate | date:'longDate':'':'pl'}} @if(session.availableFrom){ · dostępna od {{session.availableFrom | date:'short':'':'pl'}} }</p><p>Wersja zestawu: {{session.sourceExerciseSetVersionId || 'historyczny snapshot'}} · {{session.expectedDurationMinutes || '—'}} min</p><details><summary>Podgląd utrwalonej zawartości ({{session.prescriptions?.length || 0}} ćwiczeń)</summary>@for(p of session.prescriptions || [];track p.id){<div class="dose">{{snapshotDose(p)}}</div>}</details>@if(editable() && session.id){<button mat-stroked-button (click)="editSession(session)">Edytuj sesję</button><button mat-stroked-button (click)="removeSession(session.id)">Usuń</button>}</article>}
      @if(editable()){<form [formGroup]="sessionForm" (ngSubmit)="saveSession()" class="card"><h3>{{editingId() ? 'Edytuj sesję' : 'Dodaj sesję'}}</h3><div class="grid"><label>Tytuł<input formControlName="title" required maxlength="160" /></label><label>Data<input type="date" formControlName="scheduledDate" required /></label><label>Przewidywany czas (min)<input type="number" formControlName="duration" min="1" max="720" /></label><label>Zestaw ćwiczeń<select formControlName="setVersionId" required (change)="previewSelectedSet()"><option value="">Wybierz opublikowaną wersję</option>@for(option of publishedVersions();track option.id){<option [value]="option.id">{{option.title}} · v{{option.versionNumber}} · {{option.count}} ćwiczeń</option>}</select></label></div><label>Dostępna od (opcjonalnie, {{browserTimeZone}})<input type="datetime-local" formControlName="availableFrom" /></label><label>Dostępna do (opcjonalnie, {{browserTimeZone}})<input type="datetime-local" formControlName="availableTo" /></label>@if(setPreview();as set){<app-exercise-set-version-preview [version]="set" />}<div class="actions"><button mat-flat-button [disabled]="sessionForm.invalid || saving()">{{editingId() ? 'Zapisz sesję' : 'Dodaj sesję'}}</button>@if(editingId()){<button mat-stroked-button type="button" (click)="cancelEdit()">Anuluj</button>}</div></form>}</section>
    <section class="card"><h2>Walidacja i aktywacja</h2><p>Walidacja struktury, bezpieczeństwa i obciążenia jest wykonywana przez serwer.</p><div class="actions">@if(editable()){<button mat-stroked-button (click)="validateStructural()">Sprawdź strukturę</button><button mat-flat-button (click)="validateWorkflow()">Waliduj plan</button>}@if(workflow()){<button mat-stroked-button (click)="reloadWorkflow()">Odśwież status</button>}</div>@if(structural();as result){<p><strong>{{result.result === 'PASS' ? 'Struktura poprawna' : 'Wymaga korekty struktury'}}</strong></p>@for(item of result.violations || [];track item){<p class="error">{{human(item)}}</p>}}@if(workflow();as flow){<p>Status: <strong>{{flow.state?.status || revision()?.status}}</strong></p>@for(factor of flow.assessment?.factors || [];track factor.id){<article [class.error]="factor.result === 'HARD_BLOCK'"><strong>{{factor.result === 'HARD_BLOCK' ? 'Blokada' : factor.result === 'WARNING' ? 'Ostrzeżenie' : 'Informacja'}}</strong>: {{human(factor.explanationCode || factor.ruleCode || 'Ocena bezpieczeństwa/obciążenia')}} @if(factor.channel){<span> ({{factor.channel}})</span>}</article>}@if(warnings().length && editable() && (role()==='TRAINER' || own())){<label>Uzasadnienie potwierdzenia ostrzeżeń<textarea [value]="rationale()" (input)="rationale.set($any($event.target).value)" maxlength="500"></textarea></label><button mat-stroked-button [disabled]="!rationale().trim()" (click)="acknowledge()">Potwierdź ostrzeżenia</button>}@else if(warnings().length && editable()){<p class="muted">Ostrzeżenia wymagają korekty rewizji albo potwierdzenia przez uprawnionego trenera.</p>}@if(canActivate()){<button mat-flat-button (click)="activate()">Aktywuj rewizję</button>}}</section>
    @if(!editable()){<section class="card"><p>Ta rewizja jest historyczna i niemutowalna.</p><button mat-flat-button (click)="createRevision()">Utwórz nową rewizję</button></section>}
  }</main>`
})
export class SpecialistPlanPage {
  private readonly api = inject(ApiFacade); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private readonly fb = inject(FormBuilder);
  readonly participantId = signal(''); readonly role = signal<'TRAINER'|'PHYSIOTHERAPIST'|undefined>(undefined); readonly loading = signal(true); readonly error = signal(''); readonly saving = signal(false); readonly mutationError = signal(''); readonly goals = signal<any[]>([]); readonly plans = signal<any[]>([]); readonly editor = signal<any>(null); readonly workflow = signal<any>(null); readonly structural = signal<any>(null); readonly setPreview = signal<any>(null); readonly sets = signal<any[]>([]); readonly editingId = signal<string | null>(null); readonly rationale = signal('');
  readonly own = computed(() => this.route.snapshot.data?.['plannerActor'] === 'PARTICIPANT'); readonly plansIndex = computed(() => !!this.route.snapshot.data?.['plansIndex']); readonly newPlan = computed(() => !this.plansIndex() && !this.route.snapshot.paramMap.get('planId')); readonly revision = computed(() => this.editor()?.revision); readonly editable = computed(() => this.revision()?.status === 'DRAFT');
  readonly sessions = computed(() => (this.revision()?.cycles || []).flatMap((c:any) => (c.microcycles || []).flatMap((m:any) => m.sessions || [])));
  readonly warnings = computed(() => (this.workflow()?.assessment?.factors || []).filter((f:any) => f.result === 'WARNING' && f.id && !this.workflow()?.acknowledgedWarningFactorIds?.has(f.id)));
  readonly planningGoals = computed(() => this.goals().filter((goal:any) => goal.status === 'ACTIVE' && (!this.own() || ['PERFORMANCE','FUNCTIONAL'].includes(goal.category))));
  readonly canActivate = computed(() => ['READY', 'NEEDS_REVIEW'].includes(this.workflow()?.state?.status) && !this.warnings().length);
  readonly publishedVersions = computed(() => this.sets().flatMap((set:any) => (set.versions || []).filter((v:any) => v.status === 'PUBLISHED').map((v:any) => ({...v,title:v.title || set.title || 'Zestaw',count:v.itemCount || v.items?.length || 0}))));
  readonly createForm = this.fb.group({name:['',Validators.required],goalId:['',Validators.required],validFrom:['',Validators.required],validTo:['',Validators.required],phaseIntent:['']});
  readonly periodForm = this.fb.group({validFrom:['',Validators.required],validTo:['',Validators.required]});
  readonly sessionForm = this.fb.group({title:['',Validators.required],scheduledDate:['',Validators.required],duration:[null as number|null],setVersionId:['',Validators.required],availableFrom:[''],availableTo:['']});
  readonly browserTimeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  constructor(){ this.participantId.set(this.route.snapshot.paramMap.get('participantId') || ''); void this.load(); }
  workspaceLink=()=>this.own()?['/my-plans']:['/specialist/clients',this.participantId()]; newPlanLink=()=>this.own()?['/my-plans','new']:['/specialist/clients',this.participantId(),'plans','new']; revisionLink=(planId:string,revisionId:string)=>this.own()?['/my-plans',planId,'revisions',revisionId]:['/specialist/clients',this.participantId(),'plans',planId,'revisions',revisionId]; private context(){return this.role() || 'TRAINER';}
  async load(){this.loading.set(true);this.error.set('');try{if(!this.own()){const onboarding=await this.api.onboarding.state();const kind=onboarding.profile?.specialistKind;this.role.set(kind==='PHYSIOTHERAPIST'?'PHYSIOTHERAPIST':'TRAINER');}await Promise.all([this.loadGoals(),this.loadSets()]);if(this.plansIndex()){this.plans.set(this.own()?await this.api.participantPlans.listOwnParticipantPlans():await this.api.specialistPlans.listSpecialistPlans({participantId:this.participantId(),role:this.context() as any}));return;}const planId=this.route.snapshot.paramMap.get('planId');const revisionId=this.route.snapshot.paramMap.get('revisionId');if(planId&&revisionId){const view=this.own()?await this.api.planningV2.editor({revisionId}):await this.api.specialistPlans.readSpecialistPlanRevision({participantId:this.participantId(),planId,revisionId});if(view.planId!==planId)throw new Error('PLAN_REVISION_MISMATCH');this.applyEditor(view);await this.reloadWorkflow();}else if(planId){const latest:any=this.own()?(await this.api.participantPlans.listOwnParticipantPlans()).find((p:any)=>p.planId===planId): (await this.api.specialistPlans.listSpecialistPlanRevisions({participantId:this.participantId(),planId})).at(-1);if(latest?.currentRevisionId||latest?.revisionId)await this.router.navigate(this.revisionLink(planId,latest.currentRevisionId||latest.revisionId),{replaceUrl:true});}}catch(e){this.error.set(this.message(e));}finally{this.loading.set(false);}}
  async loadGoals(){try{this.goals.set(this.own()?await this.api.ownGoals.listOwnParticipantGoals():await this.api.participantGoals.listParticipantGoals({participantId:this.participantId(),actingContext:this.context() as any}));}catch{this.goals.set([]);}}
  async loadSets(){try{this.sets.set(this.own()?(await this.api.participantExerciseSets.list3()).map((v:any)=>({title:v.title,versions:[{id:v.versionId,exerciseSetId:v.exerciseSetId,versionNumber:v.versionNumber,status:'PUBLISHED'}]})):await this.api.exerciseSets.list());const preset=this.route.snapshot.queryParamMap?.get('exerciseSetVersionId');if(this.own()&&preset&&this.publishedVersions().some((v:any)=>v.id===preset))this.sessionForm.patchValue({setVersionId:preset});}catch{this.sets.set([]);}}
  private applyEditor(value:any){this.editor.set(value);const r=value.revision;this.periodForm.patchValue({validFrom:this.date(r?.validFrom),validTo:this.date(r?.validTo)});}
  async create(){if(this.createForm.invalid)return;await this.mutate(async()=>{const v=this.createForm.getRawValue();const editor=this.own()?await this.api.participantPlans.createOwnParticipantPlan({ownCreatePlanCommand:{name:v.name!,participantGoalId:v.goalId!,validFrom:new Date(v.validFrom!),validTo:new Date(v.validTo!),phaseIntent:v.phaseIntent||undefined}}):await this.api.specialistPlans.createSpecialistPlan({participantId:this.participantId(),createPlanCommand:{participantId:this.participantId(),name:v.name!,participantGoalId:v.goalId!,validFrom:new Date(v.validFrom!),validTo:new Date(v.validTo!),phaseIntent:v.phaseIntent||undefined,actingContext:this.context() as any}});await this.router.navigate(this.revisionLink(editor.planId!,editor.revision?.revisionId!));});}
  async savePeriod(){if(this.periodForm.invalid)return;const args={planId:this.editor().planId,revisionId:this.revision().revisionId,periodCommand:{expectedVersion:this.revision().revisionVersion,validFrom:new Date(this.periodForm.value.validFrom!),validTo:new Date(this.periodForm.value.validTo!)}};await this.mutate(()=>this.own()?this.api.practicalPlans.updatePeriod(args):this.api.specialistPlans.updateSpecialistPlanPeriod({participantId:this.participantId(),...args}));}
  async previewSelectedSet(){const id=this.sessionForm.value.setVersionId;const option=this.publishedVersions().find((x:any)=>x.id===id);if(!id||!option?.exerciseSetId){this.setPreview.set(null);return;}try{this.setPreview.set(this.own()?await this.api.participantExerciseSets.version1({versionId:id}):await this.api.exerciseSets.version({setId:option.exerciseSetId,versionId:id}));}catch{this.setPreview.set(null);}}
  async saveSession(){if(this.sessionForm.invalid)return;await this.mutate(async()=>{const v=this.sessionForm.getRawValue();const common={expectedVersion:this.revision().revisionVersion,title:v.title!,scheduledDate:new Date(v.scheduledDate!),availableFrom:v.availableFrom?new Date(v.availableFrom):undefined,availableTo:v.availableTo?new Date(v.availableTo):undefined,expectedDurationMinutes:v.duration||undefined,exerciseSetVersionId:v.setVersionId!};const args={planId:this.editor().planId,revisionId:this.revision().revisionId};if(this.own())return this.editingId()?this.api.practicalPlans.updateSession({...args,sessionUpdateCommand:{...common,sessionId:this.editingId()!}}):this.api.practicalPlans.addSession({...args,sessionCommand:common});return this.editingId()?this.api.specialistPlans.updateSpecialistPlanSession({participantId:this.participantId(),...args,sessionUpdateCommand:{...common,sessionId:this.editingId()!}}):this.api.specialistPlans.addSpecialistPlanSession({participantId:this.participantId(),...args,sessionCommand:common});});this.cancelEdit();}
  editSession(s:any){this.editingId.set(s.id);this.sessionForm.patchValue({title:s.title,scheduledDate:this.date(s.scheduledDate),duration:s.expectedDurationMinutes,setVersionId:s.sourceExerciseSetVersionId,availableFrom:this.dateTime(s.availableFrom),availableTo:this.dateTime(s.availableTo)});this.setPreview.set(null);}
  cancelEdit(){this.editingId.set(null);this.sessionForm.reset();this.setPreview.set(null);}
  async removeSession(id:string){const args={planId:this.editor().planId,revisionId:this.revision().revisionId,sessionId:id,expectedVersion:this.revision().revisionVersion};await this.mutate(()=>this.own()?this.api.practicalPlans.deleteSession1(args):this.api.specialistPlans.deleteSpecialistPlanSession({participantId:this.participantId(),...args}));}
  async validateStructural(){await this.mutate(async()=>{this.structural.set(await this.api.planningV2.validateStructurally({revisionId:this.revision().revisionId,validateCommand:{expectedVersion:this.revision().revisionVersion}}));return this.editor();},false);}
  async validateWorkflow(){await this.mutate(()=>this.api.planWorkflow.validate({revisionId:this.revision().revisionId,validateWorkflowCommand:this.own()?{expectedVersion:this.revision().revisionVersion}:{expectedVersion:this.revision().revisionVersion,actingContext:this.context() as any}}));await this.reloadWorkflow();}
  async reloadWorkflow(){if(!this.revision()?.revisionId)return;try{this.workflow.set(await this.api.planWorkflow.status({revisionId:this.revision().revisionId,activateWorkflowCommand:this.own()?{}:{actingContext:this.context() as any}}));}catch{this.workflow.set(null);}}
  async acknowledge(){const ids=this.warnings().map((x:any)=>x.id);if(!ids.length)return;await this.mutate(()=>this.api.planWorkflow.acknowledge({revisionId:this.revision().revisionId,acknowledgeWarningCommand:this.own()?{factorIds:new Set(ids),rationale:this.rationale().trim()}:{actingContext:this.context() as any,factorIds:new Set(ids),rationale:this.rationale().trim()}}));await this.reloadWorkflow();}
  async activate(){await this.mutate(()=>this.api.planWorkflow.activate({revisionId:this.revision().revisionId,idempotencyKey:crypto.randomUUID(),activateWorkflowCommand:this.own()?{}:{actingContext:this.context() as any}}),false);if(!this.own())await this.router.navigate(this.workspaceLink());else {const first=this.sessions()[0];await this.router.navigate(first?.id?['/sessions']:this.workspaceLink(),first?.id?{queryParams:{sessionId:first.id}}:undefined);}}
  async createRevision(){await this.mutate(async()=>{const e=this.own()?await this.api.planningV2.createRevision({planId:this.editor().planId,createRevisionCommand:{basedOnRevisionId:this.revision().revisionId}}):await this.api.specialistPlans.createSpecialistPlanRevision({participantId:this.participantId(),planId:this.editor().planId,createRevisionCommand:{basedOnRevisionId:this.revision().revisionId,actingContext:this.context() as any}});await this.router.navigate(this.revisionLink(e.planId!,e.revision?.revisionId!));},false);}
  private async mutate(call:()=>Promise<any>,refresh=true){this.saving.set(true);this.mutationError.set('');try{const result=await call();if(result?.revision)this.applyEditor(result);if(refresh&&this.editor())await this.load();}catch(e){this.mutationError.set(this.message(e));}finally{this.saving.set(false);}}
  dose(value:any){return value?Object.entries(value).filter(([key])=>key!=='type').map(([key,v])=>`${key}: ${v}`).join(' · '):'Brak dawki';} snapshotDose(p:any){try{const raw=p.materializedSnapshot?JSON.parse(p.materializedSnapshot):p;return this.dose(raw.dose||raw);}catch{return this.dose(p);}} human(value:string){return value.replace(/[_-]+/g,' ').toLocaleLowerCase('pl-PL');} private date(v:any){return v?new Date(v).toISOString().slice(0,10):'';} private dateTime(v:any){if(!v)return '';const d=new Date(v);const pad=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;} private message(e:any){return e instanceof ResponseError?`Nie można zapisać planu (${e.response.status}). Sprawdź dane, uprawnienia i stan rewizji.`:'Nie udało się wykonać operacji. Spróbuj ponownie.';}
}
