import { ChangeDetectionStrategy, Component, ElementRef, EventEmitter, Input, Output, ViewEncapsulation, afterNextRender, computed, inject, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiFacade } from '../core/api.facade';
import type { SpecialistParticipantWorkspaceView } from '../api/generated/src/models/SpecialistParticipantWorkspaceView';
import type { ParticipantTimelineEvent } from '../api/generated/src/models/ParticipantTimelineEvent';
import { groupEvents, rangeDates, sortedEvents, timelineCategories, type TimelineCategory, type WorkspaceRange, type WorkspaceView } from './specialist-participant-workspace.geometry';
import { appointmentLocation, appointmentPurpose, appointmentTypeLabel, attentionSummary, categoryLabel, eventDescription, eventTimeLabel, goalsSummary, humanEventTitle, isPastScheduled, realizationSummary, statusLabel } from './specialist-participant-workspace.presentation';

const actionLabels: Record<string, string> = { SCHEDULE_APPOINTMENT: 'Zaplanuj spotkanie' };
const label = (value: string | undefined, labels: Record<string, string>) => value ? labels[value] ?? value.replace(/_/g, ' ').toLocaleLowerCase('pl-PL') : 'Brak danych';

@Component({ selector: 'app-participant-workspace-header', standalone: true, imports: [MatButtonModule], changeDetection: ChangeDetectionStrategy.OnPush, template: `<header class="workspace-header"><div><h1 id="workspace-title">{{ workspace.participant?.displayName || 'Klient' }}</h1><div class="header-badges"><span>{{ relationshipLabel }}</span><span>{{ accountLabel }}</span></div>@if (workspace.nextAppointment?.startsAt) { <p>Następne spotkanie: <time>{{ nextAppointment }}</time></p> } @else { <p>Brak nadchodzącego spotkania.</p> }</div>@if (actions.length) { <div class="quick-actions" aria-label="Szybkie działania">@for (action of actions; track action) { <button mat-flat-button type="button" (click)="requested.emit(action)">{{ actionLabel(action) }}</button> }</div> }</header>` })
export class ParticipantWorkspaceHeaderComponent {
  @Input({ required: true }) workspace!: SpecialistParticipantWorkspaceView; @Input() accessStatus?: string; @Input() accessStatusAvailable = true; @Input() actions: string[] = []; @Output() requested = new EventEmitter<string>();
  protected actionLabel = (action: string) => actionLabels[action] ?? action;
  protected get nextAppointment() { return eventTimeLabel({ effectiveFrom: this.workspace.nextAppointment?.startsAt }); }
  protected get relationshipLabel() { return label(this.workspace.relationship?.status, { ACTIVE: 'Aktywna współpraca', INACTIVE: 'Nieaktywna współpraca' }); }
  protected get accountLabel() { return this.accessStatusAvailable ? `Konto: ${label(this.accessStatus, { ACTIVE: 'aktywne', INVITED: 'zaproszone', NO_ACCOUNT: 'bez konta', NONE: 'bez konta' })}` : 'Status konta niedostępny'; }
}

@Component({ selector: 'app-participant-summary-strip', standalone: true, changeDetection: ChangeDetectionStrategy.OnPush, template: `<section class="summary-strip" aria-label="Podsumowanie klienta"><div><strong>Aktywny plan</strong><span>{{ workspace.activePlan?.name || 'Brak aktywnego planu' }}</span></div><div><strong>Cele</strong><span>{{ goals(workspace.goals?.length) }}</span></div><div><strong>Realizacja</strong><span>{{ realization(workspace.adherenceSummary?.completedSessions) }}</span></div><div><strong>Ostatnia aktywność</strong><span>{{ workspace.recentProgress?.latestActivityAt ? 'Zarejestrowana' : 'Brak danych' }}</span></div><div><strong>Wymaga reakcji</strong><span>{{ attention(workspace.activeProblems?.length) }}</span></div></section>` })
export class ParticipantSummaryStripComponent { @Input({ required: true }) workspace!: SpecialistParticipantWorkspaceView; protected goals = goalsSummary; protected realization = realizationSummary; protected attention = attentionSummary; }

@Component({ selector: 'app-patient-timeline-filters', standalone: true, changeDetection: ChangeDetectionStrategy.OnPush, template: `<section class="timeline-controls" aria-label="Filtry osi czasu"><div class="ranges" role="group" aria-label="Zakres czasu">@for (item of ranges; track item.key) { <button type="button" [attr.aria-pressed]="range === item.key" [class.active]="range === item.key" (click)="rangeChange.emit(item.key)">{{ item.label }}</button> }</div><button class="filter-toggle" type="button" [attr.aria-expanded]="filtersOpen" aria-controls="timeline-filter-chips" (click)="filtersOpen = !filtersOpen">Filtry{{ selected.length ? ' (' + selected.length + ')' : '' }}</button>@if (filtersOpen) { <div id="timeline-filter-chips" class="filter-chips">@for (type of categories; track type) { <button type="button" [attr.aria-pressed]="selected.includes(type)" [class.active]="selected.includes(type)" (click)="toggle(type)">{{ categoryLabel(type) }}</button> } @if (selected.length) { <button type="button" (click)="clear.emit()">Wyczyść</button> }</div> } <button type="button" (click)="viewChange.emit(view === 'timeline' ? 'list' : 'timeline')">{{ view === 'timeline' ? 'Widok listy' : 'Widok osi czasu' }}</button></section>` })
export class PatientTimelineFiltersComponent {
  @Input() range: WorkspaceRange = '2w'; @Input() selected: TimelineCategory[] = []; @Input() view: WorkspaceView = 'timeline'; @Output() rangeChange = new EventEmitter<WorkspaceRange>(); @Output() selectedChange = new EventEmitter<TimelineCategory[]>(); @Output() clear = new EventEmitter<void>(); @Output() viewChange = new EventEmitter<WorkspaceView>();
  protected filtersOpen = false; protected readonly categories = timelineCategories; protected readonly ranges = [{ key: '2w' as const, label: '2 tyg.' }, { key: '3m' as const, label: '3 mies.' }, { key: '12m' as const, label: '12 mies.' }];
  protected categoryLabel = (type: string) => ({ APPOINTMENT: 'Spotkania', SESSION: 'Planowane sesje', EXECUTION: 'Wykonania' })[type] ?? type;
  protected toggle(type: TimelineCategory) { this.selectedChange.emit(this.selected.includes(type) ? this.selected.filter(item => item !== type) : [...this.selected, type]); }
}

@Component({ selector: 'app-timeline-event', standalone: true, changeDetection: ChangeDetectionStrategy.OnPush, template: `<article class="timeline-event"><button type="button" [attr.data-event-id]="event.eventId" (click)="opened.emit(event)"><span class="event-category">{{ category(event.category) }}</span>@if (time(event)) { <time>{{ time(event) }}</time> }<strong>{{ title(event) }}</strong>@if (description(event); as description) { <span class="event-description">{{ description }}</span> }@if (status(event); as state) { <span class="event-status" [class.stale]="pastScheduled(event)">Status: {{ state }}</span> }</button></article>` })
export class TimelineEventComponent { @Input({ required: true }) event!: ParticipantTimelineEvent; @Output() opened = new EventEmitter<ParticipantTimelineEvent>(); protected category = categoryLabel; protected description = eventDescription; protected pastScheduled = isPastScheduled; protected status = statusLabel; protected time = eventTimeLabel; protected title = humanEventTitle; }

@Component({ selector: 'app-timeline-period-group', standalone: true, imports: [TimelineEventComponent], changeDetection: ChangeDetectionStrategy.OnPush, template: `<section class="period-group"><h3>{{ group.label }}</h3><ol>@for (event of group.items; track event.eventId) { <li><app-timeline-event [event]="event" (opened)="opened.emit($event)" /></li> }</ol></section>` })
export class TimelinePeriodGroupComponent { @Input({ required: true }) group!: { label: string; items: ParticipantTimelineEvent[] }; @Output() opened = new EventEmitter<ParticipantTimelineEvent>(); }
@Component({ selector: 'app-patient-timeline', standalone: true, imports: [TimelinePeriodGroupComponent], changeDetection: ChangeDetectionStrategy.OnPush, template: `<section aria-label="Chronologiczna oś czasu">@for (group of groups; track group.label) { <app-timeline-period-group [group]="group" (opened)="opened.emit($event)" /> } @if (!groups.length) { <p>Brak zdarzeń w wybranym zakresie.</p> }</section>` })
export class PatientTimelineComponent { @Input() groups: Array<{ label: string; items: ParticipantTimelineEvent[] }> = []; @Output() opened = new EventEmitter<ParticipantTimelineEvent>(); }
@Component({ selector: 'app-patient-timeline-list-view', standalone: true, imports: [TimelineEventComponent], changeDetection: ChangeDetectionStrategy.OnPush, template: `<section aria-label="Widok listy"><ol class="timeline-list">@for (event of events; track event.eventId) { <li><app-timeline-event [event]="event" (opened)="opened.emit($event)" /></li> }</ol></section>` })
export class PatientTimelineListViewComponent { @Input() events: ParticipantTimelineEvent[] = []; @Output() opened = new EventEmitter<ParticipantTimelineEvent>(); }
@Component({ selector: 'app-patient-timeline-event-panel', standalone: true, changeDetection: ChangeDetectionStrategy.OnPush, template: `<aside class="event-panel" role="dialog" aria-modal="false" aria-labelledby="event-panel-title" tabindex="-1" (keydown.escape)="closed.emit()"><button type="button" aria-label="Zamknij szczegóły zdarzenia" (click)="closed.emit()">×</button><h2 id="event-panel-title">{{ title(event) }}</h2>@if (description(event); as description) { <p>{{ description }}</p> }<dl>@if (appointmentType(event); as type) { <dt>Rodzaj spotkania</dt><dd>{{ type }}</dd> }@if (time(event)) { <dt>Czas zdarzenia</dt><dd>{{ time(event) }}</dd> }@if (status(event); as state) { <dt>Status</dt><dd [class.stale]="pastScheduled(event)">{{ state }}</dd> }@if (location(event); as location) { <dt>Miejsce</dt><dd>{{ location }}</dd> }@if (purpose(event); as purpose) { <dt>Cel spotkania</dt><dd>{{ purpose }}</dd> }</dl></aside>` })
export class PatientTimelineEventPanelComponent { @Input({ required: true }) event!: ParticipantTimelineEvent; @Input() participantDisplayName?: string; @Output() closed = new EventEmitter<void>(); protected appointmentType = appointmentTypeLabel; protected description = eventDescription; protected location = appointmentLocation; protected pastScheduled = isPastScheduled; protected purpose = appointmentPurpose; protected status = statusLabel; protected time = eventTimeLabel; protected title = humanEventTitle; }

@Component({ selector: 'app-schedule-appointment-dialog', standalone: true, imports: [ReactiveFormsModule, MatButtonModule], changeDetection: ChangeDetectionStrategy.OnPush, template: `<section class="appointment-dialog" role="dialog" aria-modal="true" aria-labelledby="appointment-dialog-title"><form [formGroup]="form" (ngSubmit)="submitted.emit(form.getRawValue())"><button class="dialog-close" type="button" aria-label="Zamknij planowanie spotkania" (click)="closed.emit()">×</button><h2 id="appointment-dialog-title">Zaplanuj spotkanie</h2><label>Termin rozpoczęcia<input type="datetime-local" formControlName="startsAt" required></label><label>Termin zakończenia<input type="datetime-local" formControlName="endsAt" required></label><label>Rodzaj spotkania<select formControlName="type"><option value="TRAINING">Trening</option><option value="PHYSIOTHERAPY">Fizjoterapia</option><option value="ASSESSMENT">Ocena</option><option value="CONSULTATION">Konsultacja</option></select></label><label>Forma<select formControlName="locationMode"><option value="IN_PERSON">Na miejscu</option><option value="REMOTE">Zdalnie</option><option value="PHONE">Telefonicznie</option></select></label><label>Miejsce lub link (opcjonalnie)<input formControlName="location" maxlength="200"></label><label>Krótki cel spotkania (opcjonalnie)<input formControlName="shortPurpose" maxlength="300"></label>@if (error) { <p role="alert">Nie udało się zaplanować spotkania. Sprawdź dane i spróbuj ponownie.</p> }<div><button mat-stroked-button type="button" (click)="closed.emit()">Anuluj</button><button mat-flat-button type="submit" [disabled]="form.invalid || saving">{{ saving ? 'Zapisywanie…' : 'Zaplanuj' }}</button></div></form></section>` })
export class ScheduleAppointmentDialogComponent { @Input() saving = false; @Input() error = false; @Output() closed = new EventEmitter<void>(); @Output() submitted = new EventEmitter<{ startsAt: string; endsAt: string; type: string; locationMode: string; location: string; shortPurpose: string }>(); protected readonly form = new FormGroup({ startsAt: new FormControl('', { nonNullable: true, validators: [Validators.required] }), endsAt: new FormControl('', { nonNullable: true, validators: [Validators.required] }), type: new FormControl('TRAINING', { nonNullable: true }), locationMode: new FormControl('IN_PERSON', { nonNullable: true }), location: new FormControl('', { nonNullable: true }), shortPurpose: new FormControl('', { nonNullable: true }) }); }

@Component({ selector: 'app-specialist-participant-workspace-page', standalone: true, imports: [ParticipantWorkspaceHeaderComponent, ParticipantSummaryStripComponent, PatientTimelineFiltersComponent, PatientTimelineComponent, PatientTimelineListViewComponent, PatientTimelineEventPanelComponent, ScheduleAppointmentDialogComponent], styleUrl: './specialist-participant-workspace.page.scss', encapsulation: ViewEncapsulation.None, changeDetection: ChangeDetectionStrategy.OnPush, template: `<main class="workspace" [class.event-selected]="!!selected()" [attr.aria-busy]="state() === 'loading'"><p class="sr-only" aria-live="polite">{{ announcement() }}</p>@if (state() === 'loading') { <section class="state-card" role="status"><h1>Wczytywanie kartoteki…</h1><p>Przygotowujemy bieżący obraz pracy z klientem.</p></section> } @else if (state() === 'error') { <section class="state-card" role="alert"><h1>Nie udało się wczytać kartoteki</h1><p>Spróbuj ponownie za chwilę.</p><button mat-stroked-button type="button" (click)="reload()">Spróbuj ponownie</button></section> } @else if (workspace(); as data) { <app-participant-workspace-header [workspace]="data" [accessStatus]="accessStatus()" [accessStatusAvailable]="accessStatusAvailable()" [actions]="safeActions()" (requested)="perform($event)" /><app-participant-summary-strip [workspace]="data" /><section class="workspace-content"><section class="workspace-timeline" aria-labelledby="workspace-overview-title"><h2 id="workspace-overview-title">Historia współpracy</h2>@if (hasAttention(data)) { <section class="attention-alerts" aria-labelledby="attention-title"><h3 id="attention-title">Wymaga uwagi</h3>@for (item of data.attentionItems ?? []; track item.id) { <article role="alert"><strong>{{ item.title || 'Wymaga sprawdzenia' }}</strong>@if (item.neutralReason) { <p>{{ item.neutralReason }}</p> }</article> }@for (problem of data.activeProblems ?? []; track problem.problemId) { <article role="alert"><strong>Aktywny problem</strong>@if (problem.shortDescription) { <p>{{ problem.shortDescription }}</p> }</article> }</section> }<app-patient-timeline-filters [range]="range()" [selected]="types()" [view]="view()" (rangeChange)="setRange($event)" (selectedChange)="setTypes($event)" (clear)="setTypes([])" (viewChange)="setView($event)" />@if (view() === 'timeline') { <app-patient-timeline [groups]="groups()" (opened)="open($event)" /> } @else { <app-patient-timeline-list-view [events]="events()" (opened)="open($event)" /> }@if (nextCursor()) { <button class="older" type="button" (click)="older()">Pokaż wcześniejsze</button> }</section>@if (selected(); as event) { <app-patient-timeline-event-panel [event]="event" [participantDisplayName]="data.participant?.displayName" (closed)="close()" /> }</section>@if (scheduling()) { <app-schedule-appointment-dialog [saving]="savingAppointment()" [error]="appointmentError()" (closed)="closeSchedule()" (submitted)="schedule($event)" /> } }</main>` })
export class SpecialistParticipantWorkspacePage {
  private readonly api = inject(ApiFacade); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private readonly host = inject(ElementRef<HTMLElement>); private request = 0; private opener: HTMLElement | null = null;
  protected readonly state = signal<'loading' | 'loaded' | 'error'>('loading'); protected readonly workspace = signal<SpecialistParticipantWorkspaceView | null>(null); protected readonly events = signal<ParticipantTimelineEvent[]>([]); protected readonly nextCursor = signal<string | undefined>(undefined); protected readonly range = signal<WorkspaceRange>('2w'); protected readonly types = signal<TimelineCategory[]>([]); protected readonly view = signal<WorkspaceView>('timeline'); protected readonly selected = signal<ParticipantTimelineEvent | null>(null); protected readonly announcement = signal('');
  protected readonly accessStatus = signal<string | undefined>(undefined); protected readonly accessStatusAvailable = signal(true); protected readonly scheduling = signal(false); protected readonly savingAppointment = signal(false); protected readonly appointmentError = signal(false); protected readonly groups = computed(() => groupEvents(this.events(), rangeDates(this.range()).granularity)); protected readonly safeActions = computed(() => (this.workspace()?.quickActions ?? []).filter(action => !!actionLabels[action]));
  constructor() { this.route.queryParamMap.subscribe(params => { const range = params.get('range'); const view = params.get('view'); this.range.set(range === '3m' || range === '12m' ? range : '2w'); this.view.set(view === 'list' ? 'list' : 'timeline'); this.types.set((params.get('types') ?? '').split(',').filter((type): type is TimelineCategory => (timelineCategories as readonly string[]).includes(type))); const id = params.get('eventId'); const participantId = this.route.snapshot.paramMap.get('participantId'); if (participantId) void this.load(participantId, id); }); }
  protected hasAttention(data: SpecialistParticipantWorkspaceView) { return !!(data.attentionItems?.length || data.activeProblems?.length); }
  protected async reload(): Promise<void> { const id = this.route.snapshot.paramMap.get('participantId'); if (id) await this.load(id, this.route.snapshot.queryParamMap.get('eventId')); }
  private async load(participantId: string, selectedId: string | null): Promise<void> { const request = ++this.request; this.state.set('loading'); const dates = rangeDates(this.range()); try { const [workspace, timeline, clients] = await Promise.all([this.api.participantWorkspace.workspace({ participantId }), this.api.participantWorkspace.timeline({ participantId, from: dates.from, to: dates.to, types: this.types().join(',') || undefined, granularity: dates.granularity, limit: 100 }), this.api.specialistClients.list1().catch(() => undefined)]); if (request !== this.request) return; const client = clients?.find(item => item.participantId === participantId); this.accessStatus.set(client?.accessStatus); this.accessStatusAvailable.set(clients !== undefined); this.workspace.set(workspace); this.events.set(sortedEvents(timeline.items ?? [])); this.nextCursor.set(timeline.nextCursor); this.selected.set((timeline.items ?? []).find(event => event.eventId === selectedId) ?? null); this.state.set('loaded'); } catch { if (request === this.request) this.state.set('error'); } }
  protected setRange(range: WorkspaceRange) { void this.navigate({ range, eventId: null }); } protected setTypes(types: TimelineCategory[]) { void this.navigate({ types: types.length ? types.join(',') : null, eventId: null }); } protected setView(view: WorkspaceView) { void this.navigate({ view }); }
  protected open(event: ParticipantTimelineEvent) { this.opener = document.activeElement as HTMLElement | null; void this.navigate({ eventId: event.eventId ?? null }); afterNextRender(() => { const panel = this.host.nativeElement.querySelector('.event-panel'); if (panel instanceof HTMLElement) panel.focus(); }); } protected close() { void this.navigate({ eventId: null }); afterNextRender(() => this.opener?.focus()); }
  protected async older(): Promise<void> { const participantId = this.route.snapshot.paramMap.get('participantId'); const cursor = this.nextCursor(); if (!participantId || !cursor) return; const request = ++this.request; try { const timeline = await this.api.participantWorkspace.timeline({ participantId, ...rangeDates(this.range()), types: this.types().join(',') || undefined, cursor, limit: 100 }); if (request !== this.request) return; const ids = new Set(this.events().map(event => event.eventId)); this.events.update(events => sortedEvents([...events, ...(timeline.items ?? []).filter(event => !ids.has(event.eventId))])); this.nextCursor.set(timeline.nextCursor); } catch { this.announcement.set('Nie udało się pobrać wcześniejszych zdarzeń.'); } }
  protected perform(action: string) { if (action === 'SCHEDULE_APPOINTMENT') { this.appointmentError.set(false); this.scheduling.set(true); } } protected closeSchedule() { if (!this.savingAppointment()) this.scheduling.set(false); }
  protected async schedule(value: { startsAt: string; endsAt: string; type: string; locationMode: string; location: string; shortPurpose: string }): Promise<void> { const participantId = this.route.snapshot.paramMap.get('participantId'); const startsAt = new Date(value.startsAt); const endsAt = new Date(value.endsAt); if (!participantId || Number.isNaN(startsAt.getTime()) || Number.isNaN(endsAt.getTime()) || endsAt <= startsAt) { this.appointmentError.set(true); return; } this.savingAppointment.set(true); this.appointmentError.set(false); try { await this.api.appointments.create2({ idempotencyKey: crypto.randomUUID(), createCommand: { participantId, startsAt, endsAt, type: value.type as 'TRAINING' | 'PHYSIOTHERAPY' | 'ASSESSMENT' | 'CONSULTATION', locationMode: value.locationMode as 'IN_PERSON' | 'REMOTE' | 'PHONE', location: value.location || undefined, shortPurpose: value.shortPurpose || undefined } }); this.scheduling.set(false); this.announcement.set('Spotkanie zaplanowano. Kartoteka została odświeżona.'); await this.reload(); } catch { this.appointmentError.set(true); } finally { this.savingAppointment.set(false); } }
  private navigate(queryParams: Record<string, string | null>) { return this.router.navigate([], { relativeTo: this.route, queryParams, queryParamsHandling: 'merge' }); }
}
