package com.motionecosystem.exerciseimport;

import com.motionecosystem.audit.AuditRecorder;
import com.motionecosystem.exerciseimport.api.*;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ResponseStatusException;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.time.Clock;
import java.time.Instant;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

@Service @RequiredArgsConstructor
class ExerciseImportService {
    private static final Set<String> MEDIA_TYPES=Set.of("application/x-ndjson","application/jsonl","application/json","text/plain","application/octet-stream"), INCOMPLETE=Set.of("RECEIVED","PARSED","NORMALIZED"), BLOCKED=Set.of("INVALID","BLOCKED_BY_MAPPING","BLOCKED_BY_LICENSE","MATCH_CANDIDATES");
    private final ExerciseImportSourceRepository sources; private final ExerciseImportBatchRepository batches; private final ExerciseImportArtifactRepository importArtifacts; private final ExerciseImportRecordRepository records; private final ExerciseImportMappingRepository mappings; private final ExerciseImportIssueRepository issues; private final ExerciseImportMatchCandidateRepository candidates; private final ImportCatalogReadRepository catalog;
    private final ObjectMapper json; private final Clock clock; private final TransactionTemplate transactions; private final ImportArtifactStorage artifacts; private final ExerciseImportJobLauncher jobs; private final NormalizeImportRecord normalizer; private final ValidateImportRecord validator; private final FindExerciseMatch matcher; private final CreateExerciseDraft drafts; private final AuditRecorder audit;
    @Value("${exercise-import.limits.file-bytes}") private long maximumFileBytes;

    SourceView createSource(String actor,CreateSource request){if(request==null)throw badRequest("source is required");var e=new ExerciseImportSourceEntity();e.id=UUID.randomUUID();e.code=code(request.code(),80);e.displayName=text(request.displayName(),160,"display name");e.defaultLocale=locale(request.defaultLocale());e.licenseCode=text(request.licenseCode(),120,"license code");e.licenseVerified=request.licenseVerified();e.active=true;e.createdAt=clock.instant();e.createdBySubject=actor;try{sources.saveAndFlush(e);}catch(DataIntegrityViolationException x){throw new ResponseStatusException(HttpStatus.CONFLICT,"source code already exists",x);}audit.record(actor,"EXERCISE_IMPORT_SOURCE_CREATED","ImportSource",e.id);return sourceView(e);}
    List<SourceView> sources(){return sources.findAllByOrderByCodeAscIdAsc().stream().map(this::sourceView).toList();}
    BatchView upload(String actor,UUID sourceId,String requestKey,boolean force,MultipartFile file){if(sourceId==null||file==null||file.isEmpty())throw badRequest("sourceId and a non-empty JSONL file are required");String key=text(requestKey,160,"Idempotency-Key");String type=file.getContentType()==null?"application/octet-stream":file.getContentType().toLowerCase(Locale.ROOT);if(!MEDIA_TYPES.contains(type))throw new ResponseStatusException(HttpStatus.UNSUPPORTED_MEDIA_TYPE,"expected JSONL media type");source(sourceId);UUID artifactId=UUID.randomUUID();ImportArtifactStorage.StoredArtifact stored;try(InputStream input=file.getInputStream()){stored=artifacts.store(artifactId,filename(file.getOriginalFilename()),input,maximumFileBytes);}catch(FileSystemImportArtifactStorage.ArtifactTooLargeException x){throw new ResponseStatusException(HttpStatus.PAYLOAD_TOO_LARGE,x.getMessage());}catch(IOException x){throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"cannot persist import artifact");}var existing=batchByRequest(sourceId,key);if(existing!=null){delete(stored.storageKey());if(existing.artifact().sha256().equals(stored.sha256()))return existing;throw idempotencyConflict();}UUID previous=importArtifacts.findBySourceIdAndSha256OrderBySubmittedAt(sourceId,stored.sha256(),PageRequest.of(0,1)).stream().map(a->a.batchId).findFirst().orElse(null);if(previous!=null&&!force){delete(stored.storageKey());return batch(previous);}if(force&&previous==null){delete(stored.storageKey());throw new ResponseStatusException(HttpStatus.CONFLICT,"forceReprocess requires a previous identical batch");}UUID batchId=UUID.randomUUID();Instant now=clock.instant();try{transactions.executeWithoutResult(s->{var b=new ExerciseImportBatchEntity();b.id=batchId;b.sourceId=sourceId;b.requestKey=key;b.status="QUEUED";b.forcedFromBatchId=force?previous:null;b.submittedBySubject=actor;b.submittedAt=now;batches.save(b);var a=new ExerciseImportArtifactEntity();a.id=artifactId;a.batchId=batchId;a.storageKey=stored.storageKey();a.originalFilename=filename(file.getOriginalFilename());a.mediaType=type;a.byteSize=stored.byteSize();a.sha256=stored.sha256();a.createdAt=now;importArtifacts.save(a);audit.record(actor,force?"EXERCISE_IMPORT_FORCE_REPROCESS_REQUESTED":"EXERCISE_IMPORT_BATCH_RECEIVED","ImportBatch",batchId);});}catch(RuntimeException x){delete(stored.storageKey());var raced=batchByRequest(sourceId,key);if(raced!=null){if(raced.artifact().sha256().equals(stored.sha256()))return raced;throw idempotencyConflict();}throw x;}jobs.launch(batchId);return batch(batchId);}
    void restart(UUID batchId){transactions.executeWithoutResult(s->{var b=batchEntity(batchId);if(!b.status.equals("FAILED"))throw new ResponseStatusException(HttpStatus.CONFLICT,"only a failed batch can be restarted");b.status="QUEUED";b.completedAt=null;});jobs.launch(batchId);}
    BatchView batch(UUID id){var b=batchEntity(id);return batchView(b,importArtifacts.findByBatchId(id).orElseThrow(()->notFound("import artifact not found")));}
    RecordPage records(UUID batchId,String status,String severity,int page,int size){page(page,size);batch(batchId);var result=records.findPage(batchId,blank(status),blank(severity),PageRequest.of(page,size));return new RecordPage(result.stream().map(this::summary).toList(),page,size,result.getTotalElements());}
    RecordDetail record(UUID id){return detail(records.findById(id).orElseThrow(()->notFound("import record not found")));}
    RecordDetail decideMatch(String actor,UUID recordId,MatchDecision request){if(request==null||request.candidateId()==null||request.decision()==null)throw badRequest("candidateId and decision are required");String decision=request.decision().toUpperCase(Locale.ROOT);if(!Set.of("SAME","DIFFERENT","UNSURE").contains(decision))throw badRequest("decision must be SAME, DIFFERENT or UNSURE");transactions.executeWithoutResult(s->{var c=candidates.findLockedByIdAndRecordId(request.candidateId(),recordId).orElseThrow(()->notFound("match candidate not found"));var r=records.findLockedById(recordId).orElseThrow(()->notFound("import record not found"));c.decision=decision;c.decidedBySubject=actor;c.decidedAt=clock.instant();if(r.draftVersionId==null){if(decision.equals("SAME")){r.matchedExerciseId=c.exerciseId;r.status="READY_FOR_DRAFT";}else if(decision.equals("UNSURE"))r.status="MATCH_CANDIDATES";else if(!candidates.existsUndecidedOrNotDecision(recordId,"DIFFERENT")){r.matchedExerciseId=null;r.status="READY_FOR_DRAFT";}r.updatedAt=clock.instant();}audit.record(actor,"EXERCISE_IMPORT_MATCH_DECIDED","ImportRecord",recordId);});var r=records.findById(recordId).orElseThrow(()->notFound("import record not found"));if(r.status.equals("READY_FOR_DRAFT")&&r.draftVersionId==null)try{createDraft(actor,recordId);}catch(RuntimeException x){draftIssue(r);audit.record(actor,"EXERCISE_IMPORT_DRAFT_CREATION_FAILED","ImportRecord",recordId);}refresh(r.batchId);return record(recordId);}
    MappingView decideMapping(String actor,UUID mappingId,MappingDecision request){if(request==null||request.decision()==null)throw badRequest("mapping decision is required");String decision=request.decision().toUpperCase(Locale.ROOT);if(!Set.of("APPROVED","REJECTED").contains(decision))throw badRequest("decision must be APPROVED or REJECTED");var m=mappings.findById(mappingId).orElseThrow(()->notFound("mapping not found"));String canonical=decision.equals("APPROVED")?code(request.canonicalValue(),240):null;if(canonical!=null&&!catalog.activeDictionaryContains(m.dictionaryType,canonical))throw badRequest("canonical dictionary value does not exist");m.status=decision;m.canonicalValue=canonical;m.decidedBySubject=actor;m.decidedAt=clock.instant();mappings.save(m);audit.record(actor,"EXERCISE_IMPORT_MAPPING_DECIDED","ImportMapping",mappingId);if(decision.equals("APPROVED")){for(var r:records.findBlockedForMapping(m.sourceId,"BLOCKED_BY_MAPPING",m.sourceValue)){transactions.executeWithoutResult(s->{issues.deleteByRecordIdAndCode(r.id,"MAPPING_REQUIRED");var locked=records.findLockedById(r.id).orElseThrow();locked.status="PARSED";locked.normalizedPayload=null;locked.normalizedSha256=null;locked.normalizationVersion=null;locked.updatedAt=clock.instant();});normalizer.normalize(r.id);validator.validate(r.id);matcher.findMatches(r.id);var resolved=records.findById(r.id).orElseThrow();if(resolved.status.equals("READY_FOR_DRAFT")&&resolved.draftVersionId==null)try{createDraft(actor,r.id);}catch(RuntimeException x){draftIssue(resolved);audit.record(actor,"EXERCISE_IMPORT_DRAFT_CREATION_FAILED","ImportRecord",r.id);}}batches.findBySourceId(m.sourceId).forEach(b->refresh(b.id));}return mappingView(mappings.findById(mappingId).orElseThrow());}
    UUID createDraft(String actor,UUID recordId){UUID id=drafts.createDraft(recordId,actor);refresh(records.findById(recordId).orElseThrow(()->notFound("import record not found")).batchId);return id;}
    String exportIssues(UUID batchId,String severity,boolean csv){batch(batchId);String filter=blank(severity);var all=issues.findByBatchIdOrderByRowNumberAscSeverityAscCodeAscIdAsc(batchId).stream().filter(i->filter==null||filter.equals(i.severity)).map(this::issueView).toList();if(!csv)return all.stream().map(json::writeValueAsString).reduce("",(a,b)->a+b+"\n");StringBuilder out=new StringBuilder("rowNumber,sourceRecordKey,severity,stage,code,jsonPointer,message\n");all.forEach(i->out.append(i.rowNumber==null?"":i.rowNumber).append(',').append(csv(i.sourceRecordKey)).append(',').append(i.severity).append(',').append(i.stage).append(',').append(csv(i.code)).append(',').append(csv(i.jsonPointer)).append(',').append(csv(i.message)).append('\n'));return out.toString();}
    private SourceView source(UUID id){return sourceView(sources.findById(id).orElseThrow(()->notFound("import source not found")));}private ExerciseImportBatchEntity batchEntity(UUID id){return batches.findById(id).orElseThrow(()->notFound("import batch not found"));}private BatchView batchByRequest(UUID sourceId,String key){return batches.findBySourceIdAndRequestKey(sourceId,key).map(b->batchView(b,importArtifacts.findByBatchId(b.id).orElseThrow())).orElse(null);}
    private RecordDetail detail(ExerciseImportRecordEntity r){JsonNode raw=parse(r.rawPayload);UUID sourceId=batchEntity(r.batchId).sourceId;return new RecordDetail(r.id,r.batchId,r.rowNumber,r.sourceRecordKey,r.status,raw,nullable(r.normalizedPayload),r.rawSha256,r.normalizedSha256,r.normalizationVersion,r.matchedExerciseId,r.draftVersionId,r.createdAt,r.updatedAt,r.version,issues.findByRecordIdOrderBySeverityAscCodeAscIdAsc(r.id).stream().map(this::issueView).toList(),candidates.findByRecordIdOrderByRankAscIdAsc(r.id).stream().map(c->new CandidateView(c.id,c.exerciseId,catalog.canonicalName(c.exerciseId),c.rank,c.score,parse(c.reasons),c.algorithmVersion,c.decision,c.decidedBySubject,c.decidedAt,c.version)).toList(),mappings.findBySourceIdOrderByDictionaryTypeAscSourceValueAsc(sourceId).stream().filter(mapping->raw.toString().toUpperCase(Locale.ROOT).contains(mapping.sourceValue)).map(this::mappingProposal).toList(),licenseRemediation(r));}
    private IssueView issueView(ExerciseImportIssueEntity i){return new IssueView(i.id,i.recordId,i.rowNumber,i.recordId==null?null:records.findById(i.recordId).map(r->r.sourceRecordKey).orElse(null),i.code,i.stage,i.severity,i.jsonPointer,i.message,i.createdAt,i.resolvedAt);}private SourceView sourceView(ExerciseImportSourceEntity s){return new SourceView(s.id,s.code,s.displayName,s.defaultLocale,s.licenseCode,s.licenseVerified,s.active,s.createdAt,s.version);}private BatchView batchView(ExerciseImportBatchEntity b,ExerciseImportArtifactEntity a){return new BatchView(b.id,b.sourceId,b.requestKey,b.status,b.forcedFromBatchId,b.submittedBySubject,b.submittedAt,b.startedAt,b.completedAt,b.totalCount,b.validCount,b.invalidCount,b.blockedCount,b.draftedCount,b.unchangedCount,b.version,new ArtifactView(a.originalFilename,a.mediaType,a.byteSize,a.sha256));}private RecordSummary summary(ExerciseImportRecordEntity r){return new RecordSummary(r.id,r.rowNumber,r.sourceRecordKey,r.status,r.rawSha256,r.normalizedSha256,r.matchedExerciseId,r.draftVersionId,r.version);}private MappingView mappingView(ExerciseImportMappingEntity m){return new MappingView(m.id,m.sourceId,m.dictionaryType,m.sourceValue,m.canonicalValue,m.status,m.decidedBySubject,m.decidedAt,m.version);}private MappingProposal mappingProposal(ExerciseImportMappingEntity mapping){return new MappingProposal(mapping.id,mapping.dictionaryType,mappingField(mapping.dictionaryType),mapping.sourceValue,mapping.canonicalValue,mapping.status,catalog.activeDictionaryOptions(mapping.dictionaryType).stream().map(item->new DictionaryChoice(item.value(),item.displayName())).toList());}private static String mappingField(String type){return switch(type){case "EQUIPMENT"->"/equipment";case "POSITION"->"/position";case "DOSE_UNIT"->"/doseCapabilities/*/unit";default->"/"+type.toLowerCase(Locale.ROOT);};}private LicenseRemediation licenseRemediation(ExerciseImportRecordEntity record){return record.status.equals("BLOCKED_BY_LICENSE")?new LicenseRemediation("CREATE_REPLACEMENT_SOURCE_AND_REUPLOAD","Source license metadata is immutable after submission; create a replacement source with verified license metadata, then upload the artifact again.","CREATE_SOURCE"):null;}
    private void refresh(UUID batchId){transactions.executeWithoutResult(s->{var b=batchEntity(batchId);var all=records.findByBatchId(batchId);var allIssues=issues.findByBatchIdOrderByRowNumberAscSeverityAscCodeAscIdAsc(batchId);b.totalCount=all.size();b.validCount=(int)all.stream().filter(r->!Set.of("INVALID","BLOCKED_BY_MAPPING","BLOCKED_BY_LICENSE","REJECTED").contains(r.status)).count();b.invalidCount=(int)all.stream().filter(r->r.status.equals("INVALID")).count();var failed=allIssues.stream().filter(i->i.recordId!=null&&i.code.equals("DRAFT_CREATION_FAILED")&&i.resolvedAt==null).map(i->i.recordId).collect(Collectors.toSet());b.blockedCount=(int)all.stream().filter(r->BLOCKED.contains(r.status)||failed.contains(r.id)).count();b.draftedCount=(int)all.stream().filter(r->r.status.equals("DRAFTED")).count();b.unchangedCount=(int)all.stream().filter(r->r.status.equals("UNCHANGED")).count();boolean complete=all.stream().noneMatch(r->INCOMPLETE.contains(r.status)),hasIssues=all.stream().anyMatch(r->BLOCKED.contains(r.status))||allIssues.stream().anyMatch(i->i.resolvedAt==null&&Set.of("ERROR","BLOCKER").contains(i.severity));if(!b.status.equals("FAILED"))b.status=!complete?"PROCESSING":hasIssues?"COMPLETED_WITH_ISSUES":"COMPLETED";b.completedAt=!all.isEmpty()&&complete?(b.completedAt==null?clock.instant():b.completedAt):null;});}
    private void draftIssue(ExerciseImportRecordEntity r){if(issues.existsByRecordIdAndCodeAndResolvedAtIsNull(r.id,"DRAFT_CREATION_FAILED"))return;transactions.executeWithoutResult(s->{var i=new ExerciseImportIssueEntity();i.id=UUID.randomUUID();i.batchId=r.batchId;i.recordId=r.id;i.rowNumber=r.rowNumber;i.code="DRAFT_CREATION_FAILED";i.stage="CREATE_DRAFT";i.severity="ERROR";i.jsonPointer="/";i.message="Nie można było utworzyć szkicu. Rekord pozostaje gotowy do bezpiecznego ponowienia.";i.createdAt=clock.instant();issues.save(i);});}private JsonNode parse(String x){return json.readTree(x);}private JsonNode nullable(String x){return x==null?null:parse(x);}private void delete(String key){try{artifacts.delete(key);}catch(IOException ignored){}}
    private static void page(int p,int s){if(p<0||s<1||s>100)throw badRequest("page must be >= 0 and size between 1 and 100");}private static String filename(String x){String n=x==null?"import.jsonl":x.replace('\\','/');n=n.substring(n.lastIndexOf('/')+1);return n.isBlank()?"import.jsonl":n.substring(0,Math.min(255,n.length()));}private static String text(String x,int max,String field){String v=x==null?"":x.trim();if(v.isBlank()||v.length()>max)throw badRequest(field+" is required and limited to "+max+" characters");return v;}private static String code(String x,int max){String v=text(x,max,"code").toUpperCase(Locale.ROOT);if(!v.matches("[A-Z0-9_:-]+"))throw badRequest("code contains unsupported characters");return v;}private static String locale(String x){Locale l=Locale.forLanguageTag(text(x,35,"locale").replace('_','-'));if(l.getLanguage().isBlank())throw badRequest("invalid locale");return l.toLanguageTag();}private static String blank(String x){return x==null||x.isBlank()?null:x.toUpperCase(Locale.ROOT);}private static String csv(String x){return "\""+(x==null?"":x.replace("\"","\"\""))+"\"";}private static ResponseStatusException badRequest(String x){return new ResponseStatusException(HttpStatus.BAD_REQUEST,x);}private static ResponseStatusException notFound(String x){return new ResponseStatusException(HttpStatus.NOT_FOUND,x);}private static ResponseStatusException idempotencyConflict(){return new ResponseStatusException(HttpStatus.CONFLICT,"Idempotency-Key was already used with different content");}
    record CreateSource(String code,String displayName,String defaultLocale,String licenseCode,boolean licenseVerified){}record SourceView(UUID id,String code,String displayName,String defaultLocale,String licenseCode,boolean licenseVerified,boolean active,Instant createdAt,long version){}record ArtifactView(String originalFilename,String mediaType,long byteSize,String sha256){}record BatchView(UUID id,UUID sourceId,String requestKey,String status,UUID forcedFromBatchId,String submittedBySubject,Instant submittedAt,Instant startedAt,Instant completedAt,int totalCount,int validCount,int invalidCount,int blockedCount,int draftedCount,int unchangedCount,long version,ArtifactView artifact){}record RecordSummary(UUID id,long rowNumber,String sourceRecordKey,String status,String rawSha256,String normalizedSha256,UUID matchedExerciseId,UUID draftVersionId,long version){}record RecordPage(List<RecordSummary> content,int page,int size,long totalElements){}record IssueView(UUID id,UUID recordId,Long rowNumber,String sourceRecordKey,String code,String stage,String severity,String jsonPointer,String message,Instant createdAt,Instant resolvedAt){}record CandidateView(UUID id,UUID exerciseId,String exerciseName,int rank,java.math.BigDecimal score,JsonNode reasons,String algorithmVersion,String decision,String decidedBySubject,Instant decidedAt,long version){}record RecordDetail(UUID id,UUID batchId,long rowNumber,String sourceRecordKey,String status,JsonNode raw,JsonNode normalized,String rawSha256,String normalizedSha256,String normalizationVersion,UUID matchedExerciseId,UUID draftVersionId,Instant createdAt,Instant updatedAt,long version,List<IssueView> issues,List<CandidateView> matchCandidates,List<MappingProposal> mappingProposals,LicenseRemediation licenseRemediation){}record MappingProposal(UUID id,String dictionaryType,String field,String rawValue,String proposedCanonicalValue,String status,List<DictionaryChoice> canonicalChoices){}record DictionaryChoice(String value,String displayName){}record LicenseRemediation(String code,String message,String action){}record MatchDecision(UUID candidateId,String decision){}record MappingDecision(String decision,String canonicalValue){}record MappingView(UUID id,UUID sourceId,String dictionaryType,String sourceValue,String canonicalValue,String status,String decidedBySubject,Instant decidedAt,long version){}
}
