package com.motionecosystem.participantmeasurements;
import com.motionecosystem.identityaccess.api.*; import com.motionecosystem.identityaccess.api.SpecialistAuthorizationPort.*; import com.motionecosystem.participant.ParticipantRecordRepository; import com.motionecosystem.participant.api.ParticipantMetricCatalog; import com.motionecosystem.participant.api.ParticipantMetricCatalog.*; import com.motionecosystem.participantmeasurements.api.ParticipantMeasurementQueryPort; import java.math.BigDecimal; import java.time.*; import java.util.*; import org.springframework.data.domain.PageRequest; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Propagation; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
@Service public class ParticipantMeasurementService implements ParticipantMeasurementQueryPort {
 private final ParticipantMeasurementRepository measurements; private final ParticipantRecordRepository participants; private final CurrentAccountService accounts; private final SpecialistAuthorizationPort authorization; private final Clock clock;
 public ParticipantMeasurementService(ParticipantMeasurementRepository m,ParticipantRecordRepository p,CurrentAccountService a,SpecialistAuthorizationPort z,Clock c){measurements=m;participants=p;accounts=a;authorization=z;clock=c;}
 @Transactional(readOnly=true) public List<ParticipantMeasurementPresetView> catalog(String subject,UUID participant){authorize(subject,participant);return ParticipantMetricCatalog.views();}
 @Transactional(readOnly=true) public List<ParticipantMeasurementView> list(String subject,UUID participant,Integer limit){authorize(subject,participant);return measurements.findByParticipantIdOrderByMeasuredAtDescRecordedAtDescIdDesc(participant,PageRequest.of(0,Math.min(limit==null?50:limit,100))).stream().map(this::view).toList();}
 @Override @Transactional(readOnly=true) public List<MeasurementSnapshot> recent(UUID participant,int limit){return measurements.findByParticipantIdOrderByMeasuredAtDescRecordedAtDescIdDesc(participant,page(limit)).stream().map(this::snapshot).toList();}
 @Override @Transactional(readOnly=true) public List<MeasurementSnapshot> timeline(UUID participant,Instant from,Instant to,int limit){return measurements.findByParticipantIdAndMeasuredAtGreaterThanEqualAndMeasuredAtLessThanOrderByMeasuredAtDescRecordedAtDescIdDesc(participant,from,to,page(limit)).stream().map(this::snapshot).toList();}
 @Override @Transactional(readOnly=true) public List<MeasurementSnapshot> forAppointment(UUID participant,UUID appointment,int limit){return measurements.findByParticipantIdAndAppointmentIdOrderByMeasuredAtDescRecordedAtDescIdDesc(participant,appointment,page(limit)).stream().map(this::snapshot).toList();}
 @Override @Transactional(readOnly=true) public Optional<MeasurementSnapshot> find(UUID participant,UUID measurement){return measurements.findByIdAndParticipantId(measurement,participant).map(this::snapshot);}
 /**
  * The caller owns the transaction so saving the fact and projecting goal progress
  * can commit or roll back together. Locking the canonical participant row keeps
  * concurrent requests for the same idempotency tuple out of an aborted duplicate-key
  * transaction; the second caller performs a clean replay read after the lock.
  */
 @Transactional(propagation=Propagation.MANDATORY) public RecordResult record(String subject,UUID participant,String key,ParticipantMeasurementCommand c){return record(subject,participant,key,c,()->{});}
 public RecordResult record(String subject,UUID participant,String key,ParticipantMeasurementCommand c,Runnable beforeCreate){ UUID actor=authorize(subject,participant); String idem=required(key,"Idempotency-Key",120); participants.lockById(participant).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"participant not found")); var replay=measurements.findByRecordedByAccountIdAndParticipantIdAndIdempotencyKey(actor,participant,idem); if(replay.isPresent())return new RecordResult(view(replay.get()),false); if(c==null||c.value()==null||c.value().signum()<0)bad("value is required and must not be negative"); if(beforeCreate!=null)beforeCreate.run(); var d=ParticipantMetricCatalog.derive(c.presetId(),c.bodyArea(),c.customLabel(),c.exercise(),c.activity(),c.unit()); Instant measured=c.measuredAt()==null?clock.instant():c.measuredAt(); Instant recorded=clock.instant(); ParticipantMeasurement saved=measurements.saveAndFlush(new ParticipantMeasurement(UUID.randomUUID(),participant,c.appointmentId(),d.metricCode(),c.value(),d.unit(),d.measurementMethod(),measured,optional(c.note(),500),actor,recorded,idem)); return new RecordResult(view(saved),true); }
 private UUID authorize(String s,UUID p){if(p==null)bad("participantId is required");var a=accounts.requireActive(s);if(!a.hasProfile(ProfileType.SPECIALIST))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"specialist profile is required");authorization.requireActiveRelationship(a.id(),p);return a.id();}
 private ParticipantMeasurementView view(ParticipantMeasurement m){return new ParticipantMeasurementView(m.id,m.participantId,m.appointmentId,m.metricCode,m.value,m.unit,m.measurementMethod,m.measuredAt,m.note,m.recordedByAccountId,m.recordedAt,m.source);}
 private MeasurementSnapshot snapshot(ParticipantMeasurement m){return new MeasurementSnapshot(m.id(),m.participantId(),m.appointmentId(),m.metricCode(),m.value(),m.unit(),m.measurementMethod(),m.measuredAt(),m.note(),m.recordedByAccountId(),m.recordedAt(),m.source());}
 private static PageRequest page(int limit){if(limit<1||limit>100)throw new IllegalArgumentException("limit must be from 1 to 100");return PageRequest.of(0,limit);}
 private static String required(String v,String f,int n){if(v==null||v.isBlank()||v.trim().length()>n)bad(f+" is required");return v.trim();} private static String optional(String v,int n){if(v==null||v.isBlank())return null;if(v.trim().length()>n)bad("note is too long");return v.trim();} private static void bad(String s){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,s);}
 public record ParticipantMeasurementCommand(PresetId presetId,BigDecimal value,String unit,Instant measuredAt,String note,String bodyArea,String exercise,String activity,String customLabel,UUID appointmentId){ public ParticipantMeasurementCommand(PresetId presetId,BigDecimal value,String unit,Instant measuredAt,String note,String bodyArea,String exercise,String activity,String customLabel){this(presetId,value,unit,measuredAt,note,bodyArea,exercise,activity,customLabel,null);} } public record ParticipantMeasurementView(UUID id,UUID participantId,UUID appointmentId,String metricCode,BigDecimal value,String unit,String measurementMethod,Instant measuredAt,String note,UUID recordedByAccountId,Instant recordedAt,String source){} public record RecordResult(ParticipantMeasurementView measurement,boolean created){}
}
