CREATE SCHEMA IF NOT EXISTS participant_documentation;
CREATE TABLE participant_documentation.participant_interview (id UUID PRIMARY KEY, participant_id UUID NOT NULL CONSTRAINT fk_participant_documentation_interview_participant REFERENCES participant.participant_record(id), specialist_account_id UUID NOT NULL CONSTRAINT fk_participant_documentation_interview_specialist REFERENCES identity_access.principal_account(id), status VARCHAR(16) NOT NULL, template_code VARCHAR(80) NOT NULL, template_version INTEGER NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, completed_at TIMESTAMPTZ, version BIGINT NOT NULL DEFAULT 0, CONSTRAINT ck_participant_documentation_interview_status CHECK (status IN ('DRAFT','COMPLETED','SUPERSEDED')));
CREATE INDEX ix_participant_documentation_interview_owner ON participant_documentation.participant_interview(participant_id,specialist_account_id,created_at DESC);
CREATE TABLE participant_documentation.participant_interview_answer (id UUID PRIMARY KEY, interview_id UUID NOT NULL CONSTRAINT fk_participant_documentation_interview_answer_interview REFERENCES participant_documentation.participant_interview(id) ON DELETE CASCADE, question_code VARCHAR(80) NOT NULL, section_title VARCHAR(120) NOT NULL, question_title VARCHAR(240) NOT NULL, question_type VARCHAR(30) NOT NULL, required_question BOOLEAN NOT NULL, text_value VARCHAR(4000), number_value NUMERIC, date_value DATE, selection_values TEXT[], CONSTRAINT uq_participant_documentation_interview_answer UNIQUE(interview_id,question_code));
CREATE TABLE participant_documentation.participant_note (id UUID PRIMARY KEY, participant_id UUID NOT NULL CONSTRAINT fk_participant_documentation_note_participant REFERENCES participant.participant_record(id), specialist_account_id UUID NOT NULL CONSTRAINT fk_participant_documentation_note_specialist REFERENCES identity_access.principal_account(id), status VARCHAR(16) NOT NULL, category VARCHAR(50) NOT NULL, title VARCHAR(160) NOT NULL, content VARCHAR(8000) NOT NULL, appointment_id UUID, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, finalised_at TIMESTAMPTZ, archived_at TIMESTAMPTZ, version BIGINT NOT NULL DEFAULT 0, CONSTRAINT ck_participant_documentation_note_status CHECK(status IN ('DRAFT','FINAL','ARCHIVED')));
CREATE INDEX ix_participant_documentation_note_owner ON participant_documentation.participant_note(participant_id,specialist_account_id,updated_at DESC);
CREATE TABLE participant_documentation.participant_documentation_idempotency (id UUID PRIMARY KEY,specialist_account_id UUID NOT NULL CONSTRAINT fk_participant_documentation_idempotency_specialist REFERENCES identity_access.principal_account(id),operation VARCHAR(100) NOT NULL,idempotency_key VARCHAR(120) NOT NULL,documentation_id UUID NOT NULL,created_at TIMESTAMPTZ NOT NULL,CONSTRAINT uq_participant_documentation_idempotency UNIQUE(specialist_account_id,operation,idempotency_key));
CREATE TABLE participant_documentation.participant_documentation_event (id UUID PRIMARY KEY,documentation_id UUID NOT NULL,participant_id UUID NOT NULL CONSTRAINT fk_participant_documentation_event_participant REFERENCES participant.participant_record(id),record_type VARCHAR(20) NOT NULL,action VARCHAR(30) NOT NULL,effective_at TIMESTAMPTZ NOT NULL,recorded_at TIMESTAMPTZ NOT NULL,neutral_title VARCHAR(180) NOT NULL);
CREATE INDEX ix_participant_documentation_event_timeline ON participant_documentation.participant_documentation_event(participant_id,effective_at DESC);
